// 語彙パック: TOEIC500 バンド 追加分H（頻出基礎語）。
// ejdict-hand(CC0) 取込→並列サブエージェントで語義是正・機能語除去したもの。
// 既存の全 eikaiwa 語と word・ja が重複しないよう調整済み（意味は全トラックで一意）。
import type { VocabEntry, VocabUnitMeta } from "./types";

export const TOEIC500_H_UNITS: VocabUnitMeta[] = [
  { unit: 65, title: "頻出基礎語（TOEIC500・その65）", lesson: "よく使う基礎語を英語→日本語の4択でおぼえよう。" },
  { unit: 66, title: "頻出基礎語（TOEIC500・その66）", lesson: "よく使う基礎語を英語→日本語の4択でおぼえよう。" },
  { unit: 67, title: "頻出基礎語（TOEIC500・その67）", lesson: "よく使う基礎語を英語→日本語の4択でおぼえよう。" },
  { unit: 68, title: "頻出基礎語（TOEIC500・その68）", lesson: "よく使う基礎語を英語→日本語の4択でおぼえよう。" },
  { unit: 69, title: "頻出基礎語（TOEIC500・その69）", lesson: "よく使う基礎語を英語→日本語の4択でおぼえよう。" },
  { unit: 70, title: "頻出基礎語（TOEIC500・その70）", lesson: "よく使う基礎語を英語→日本語の4択でおぼえよう。" },
];

export const TOEIC500_H_VOCAB: VocabEntry[] = [
  { word: "shadow", pos: "名", ja: "影", example: "a long shadow（長い影）", unit: 65 },
  { word: "solemn", pos: "形", ja: "厳粛な", example: "a solemn promise（厳粛な約束）", unit: 65 },
  { word: "swing", pos: "動", ja: "揺れる", example: "swing back and forth（前後に揺れる）", unit: 65 },
  { word: "tribe", pos: "名", ja: "部族", example: "an ancient tribe（古代の部族）", unit: 65 },
  { word: "trick", pos: "名", ja: "いたずら", example: "play a trick（いたずらをする）", unit: 65 },
  { word: "trouble", pos: "名", ja: "困りごと", example: "cause trouble（困りごとを起こす）", unit: 65 },
  { word: "trust", pos: "動", ja: "信頼する", example: "trust a friend（友達を信頼する）", unit: 65 },
  { word: "truth", pos: "名", ja: "真実", example: "tell the truth（真実を話す）", unit: 65 },
  { word: "try", pos: "動", ja: "試す", example: "try again（もう一度試す）", unit: 65 },
  { word: "tune", pos: "名", ja: "メロディー", example: "a catchy tune（覚えやすいメロディー）", unit: 65 },
  { word: "turn", pos: "動", ja: "回す", example: "turn the handle（ハンドルを回す）", unit: 65 },
  { word: "twist", pos: "動", ja: "ねじる", example: "twist the cap（ふたをねじる）", unit: 65 },
  { word: "ugly", pos: "形", ja: "醜い", example: "an ugly monster（醜い怪物）", unit: 65 },
  { word: "uncle", pos: "名", ja: "おじ", example: "my uncle（私のおじ）", unit: 65 },
  { word: "understand", pos: "動", ja: "理解する", example: "understand the question（質問を理解する）", unit: 65 },
  { word: "union", pos: "名", ja: "組合", example: "a labor union（労働組合）", unit: 65 },
  { word: "unit", pos: "名", ja: "単位", example: "a unit of length（長さの単位）", unit: 65 },
  { word: "unite", pos: "動", ja: "団結する", example: "unite as a team（チームとして団結する）", unit: 65 },
  { word: "unity", pos: "名", ja: "団結", example: "team unity（チームの団結）", unit: 65 },
  { word: "universal", pos: "形", ja: "普遍的な", example: "a universal rule（普遍的な規則）", unit: 65 },
  { word: "universe", pos: "名", ja: "宇宙", example: "explore the universe（宇宙を探検する）", unit: 66 },
  { word: "upper", pos: "形", ja: "上のほうの", example: "the upper floor（上のほうの階）", unit: 66 },
  { word: "upset", pos: "形", ja: "動揺した", example: "feel upset（動揺する）", unit: 66 },
  { word: "urge", pos: "動", ja: "促す", example: "urge them to hurry（急ぐよう促す）", unit: 66 },
  { word: "urgent", pos: "形", ja: "緊急の", example: "an urgent message（緊急の連絡）", unit: 66 },
  { word: "usual", pos: "形", ja: "いつもの", example: "the usual place（いつもの場所）", unit: 66 },
  { word: "valley", pos: "名", ja: "谷", example: "a deep valley（深い谷）", unit: 66 },
  { word: "valuable", pos: "形", ja: "価値のある", example: "a valuable lesson（価値のある教訓）", unit: 66 },
  { word: "value", pos: "名", ja: "価値", example: "the value of money（お金の価値）", unit: 66 },
  { word: "various", pos: "形", ja: "さまざまな", example: "various colors（さまざまな色）", unit: 66 },
  { word: "veil", pos: "名", ja: "ベール", example: "a white veil（白いベール）", unit: 66 },
  { word: "verb", pos: "名", ja: "動詞", example: "an action verb（動作を表す動詞）", unit: 66 },
  { word: "very", pos: "副", ja: "とても", example: "very happy（とても幸せ）", unit: 66 },
  { word: "victory", pos: "名", ja: "勝利", example: "a great victory（大きな勝利）", unit: 66 },
  { word: "view", pos: "名", ja: "景色", example: "a beautiful view（美しい景色）", unit: 66 },
  { word: "village", pos: "名", ja: "村", example: "a small village（小さな村）", unit: 66 },
  { word: "violence", pos: "名", ja: "暴力", example: "an act of violence（暴力行為）", unit: 66 },
  { word: "violent", pos: "形", ja: "暴力的な", example: "a violent crime（暴力的な犯罪）", unit: 66 },
  { word: "virtue", pos: "名", ja: "美徳", example: "a great virtue（大きな美徳）", unit: 66 },
  { word: "visit", pos: "動", ja: "訪ねる", example: "visit a friend（友達を訪ねる）", unit: 66 },
  { word: "visitor", pos: "名", ja: "訪問者", example: "a foreign visitor（外国からの訪問者）", unit: 67 },
  { word: "voice", pos: "名", ja: "声", example: "a loud voice（大きな声）", unit: 67 },
  { word: "vote", pos: "名", ja: "票", example: "count the votes（票を数える）", unit: 67 },
  { word: "voyage", pos: "名", ja: "航海", example: "a long voyage（長い航海）", unit: 67 },
  { word: "wage", pos: "名", ja: "賃金", example: "a low wage（低い賃金）", unit: 67 },
  { word: "wait", pos: "動", ja: "待つ", example: "wait for a bus（バスを待つ）", unit: 67 },
  { word: "waiter", pos: "名", ja: "ウェイター", example: "call the waiter（ウェイターを呼ぶ）", unit: 67 },
  { word: "wake", pos: "動", ja: "目を覚ます", example: "wake up early（早く目を覚ます）", unit: 67 },
  { word: "walk", pos: "動", ja: "歩く", example: "walk to school（学校まで歩く）", unit: 67 },
  { word: "wall", pos: "名", ja: "壁", example: "a high wall（高い壁）", unit: 67 },
  { word: "wander", pos: "動", ja: "歩き回る", example: "wander in the park（公園を歩き回る）", unit: 67 },
  { word: "want", pos: "動", ja: "ほしい", example: "want a new bike（新しい自転車がほしい）", unit: 67 },
  { word: "war", pos: "名", ja: "戦争", example: "start a war（戦争を始める）", unit: 67 },
  { word: "warm", pos: "形", ja: "暖かい", example: "a warm room（暖かい部屋）", unit: 67 },
  { word: "warmth", pos: "名", ja: "暖かさ", example: "the warmth of the sun（太陽の暖かさ）", unit: 67 },
  { word: "warn", pos: "動", ja: "警告する", example: "warn of danger（危険を警告する）", unit: 67 },
  { word: "wash", pos: "動", ja: "洗う", example: "wash your hands（手を洗う）", unit: 67 },
  { word: "waste", pos: "動", ja: "むだにする", example: "waste money（お金をむだにする）", unit: 67 },
  { word: "water", pos: "名", ja: "水", example: "drink water（水を飲む）", unit: 67 },
  { word: "wave", pos: "名", ja: "波", example: "a big wave（大きな波）", unit: 67 },
  { word: "wax", pos: "名", ja: "ろう", example: "a candle made of wax（ろうでできたろうそく）", unit: 68 },
  { word: "way", pos: "名", ja: "道", example: "the way home（家への道）", unit: 68 },
  { word: "weak", pos: "形", ja: "弱い", example: "a weak body（弱い体）", unit: 68 },
  { word: "weaken", pos: "動", ja: "弱める", example: "weaken the enemy（敵を弱める）", unit: 68 },
  { word: "wealth", pos: "名", ja: "富", example: "great wealth（大きな富）", unit: 68 },
  { word: "weapon", pos: "名", ja: "武器", example: "a dangerous weapon（危険な武器）", unit: 68 },
  { word: "wear", pos: "動", ja: "着ている", example: "wear a coat（コートを着ている）", unit: 68 },
  { word: "weather", pos: "名", ja: "天気", example: "good weather（良い天気）", unit: 68 },
  { word: "weave", pos: "動", ja: "織る", example: "weave cloth（布を織る）", unit: 68 },
  { word: "week", pos: "名", ja: "週", example: "next week（来週）", unit: 68 },
  { word: "weekend", pos: "名", ja: "週末", example: "this weekend（今週末）", unit: 68 },
  { word: "weigh", pos: "動", ja: "重さを量る", example: "weigh the bag（かばんの重さを量る）", unit: 68 },
  { word: "weight", pos: "名", ja: "重さ", example: "lose weight（体重を減らす）", unit: 68 },
  { word: "welcome", pos: "動", ja: "歓迎する", example: "welcome guests（客を歓迎する）", unit: 68 },
  { word: "well", pos: "副", ja: "上手に", example: "sing well（上手に歌う）", unit: 68 },
  { word: "west", pos: "名", ja: "西", example: "to the west（西へ）", unit: 68 },
  { word: "western", pos: "形", ja: "西の", example: "western countries（西の国々）", unit: 68 },
  { word: "wet", pos: "形", ja: "ぬれた", example: "wet clothes（ぬれた服）", unit: 68 },
  { word: "wheel", pos: "名", ja: "車輪", example: "a car wheel（車の車輪）", unit: 68 },
  { word: "whip", pos: "名", ja: "むち", example: "crack a whip（むちを鳴らす）", unit: 68 },
  { word: "whisper", pos: "動", ja: "ささやく", example: "whisper a secret（秘密をささやく）", unit: 69 },
  { word: "whistle", pos: "動", ja: "口笛を吹く", example: "whistle a tune（口笛で曲を吹く）", unit: 69 },
  { word: "white", pos: "形", ja: "白い", example: "a white shirt（白いシャツ）", unit: 69 },
  { word: "wide", pos: "形", ja: "幅の広い", example: "a wide road（幅の広い道）", unit: 69 },
  { word: "widow", pos: "名", ja: "未亡人", example: "a young widow（若い未亡人）", unit: 69 },
  { word: "width", pos: "名", ja: "幅", example: "the width of the road（道の幅）", unit: 69 },
  { word: "wife", pos: "名", ja: "妻", example: "my wife（私の妻）", unit: 69 },
  { word: "wild", pos: "形", ja: "野生の", example: "wild animals（野生の動物）", unit: 69 },
  { word: "win", pos: "動", ja: "勝つ", example: "win the game（試合に勝つ）", unit: 69 },
  { word: "wind", pos: "名", ja: "風", example: "a strong wind（強い風）", unit: 69 },
  { word: "window", pos: "名", ja: "窓", example: "open the window（窓を開ける）", unit: 69 },
  { word: "wine", pos: "名", ja: "ワイン", example: "a glass of wine（一杯のワイン）", unit: 69 },
  { word: "wing", pos: "名", ja: "翼", example: "a bird's wing（鳥の翼）", unit: 69 },
  { word: "winter", pos: "名", ja: "冬", example: "a cold winter（寒い冬）", unit: 69 },
  { word: "wipe", pos: "動", ja: "ふく", example: "wipe the table（テーブルをふく）", unit: 69 },
  { word: "wire", pos: "名", ja: "針金", example: "a copper wire（銅の針金）", unit: 69 },
  { word: "wisdom", pos: "名", ja: "知恵", example: "great wisdom（すぐれた知恵）", unit: 69 },
  { word: "wish", pos: "動", ja: "願う", example: "wish for peace（平和を願う）", unit: 69 },
  { word: "witness", pos: "名", ja: "目撃者", example: "a witness to the accident（事故の目撃者）", unit: 69 },
  { word: "wonder", pos: "動", ja: "不思議に思う", example: "I wonder why（なぜだろうと思う）", unit: 69 },
  { word: "wood", pos: "名", ja: "木材", example: "a table made of wood（木材でできた机）", unit: 70 },
  { word: "wooden", pos: "形", ja: "木製の", example: "a wooden box（木製の箱）", unit: 70 },
  { word: "word", pos: "名", ja: "単語", example: "a new word（新しい単語）", unit: 70 },
  { word: "work", pos: "動", ja: "働く", example: "work hard（一生懸命働く）", unit: 70 },
  { word: "world", pos: "名", ja: "世界", example: "travel the world（世界を旅する）", unit: 70 },
  { word: "worry", pos: "動", ja: "心配する", example: "worry about money（お金を心配する）", unit: 70 },
  { word: "worse", pos: "形", ja: "より悪い", example: "get worse（より悪くなる）", unit: 70 },
  { word: "worship", pos: "動", ja: "崇拝する", example: "worship a god（神を崇拝する）", unit: 70 },
  { word: "worth", pos: "形", ja: "価値がある", example: "worth trying（試す価値がある）", unit: 70 },
  { word: "wound", pos: "名", ja: "傷", example: "a deep wound（深い傷）", unit: 70 },
  { word: "wrap", pos: "動", ja: "包む", example: "wrap a gift（贈り物を包む）", unit: 70 },
  { word: "wreck", pos: "動", ja: "大破させる", example: "wreck a car（車を大破させる）", unit: 70 },
  { word: "wrist", pos: "名", ja: "手首", example: "hurt my wrist（手首を痛める）", unit: 70 },
  { word: "write", pos: "動", ja: "書く", example: "write a letter（手紙を書く）", unit: 70 },
  { word: "wrong", pos: "形", ja: "間違った", example: "the wrong answer（間違った答え）", unit: 70 },
  { word: "year", pos: "名", ja: "年", example: "last year（去年）", unit: 70 },
  { word: "yellow", pos: "形", ja: "黄色い", example: "a yellow flower（黄色い花）", unit: 70 },
  { word: "yesterday", pos: "副", ja: "きのう", example: "I saw him yesterday（きのう彼に会った）", unit: 70 },
  { word: "yield", pos: "動", ja: "譲る", example: "yield to a car（車に道を譲る）", unit: 70 },
  { word: "young", pos: "形", ja: "若い", example: "a young girl（若い女の子）", unit: 70 },
];
