// 語彙パック: TOEIC500 バンド 追加分D（頻出基礎語・第2バッチ）。
// ejdict-hand(CC0) 取込→並列サブエージェントで語義是正・機能語除去したもの。
// 既存の全 eikaiwa 語と word・ja が重複しないよう調整済み（意味は全トラックで一意）。
import type { VocabEntry, VocabUnitMeta } from "./types";

export const TOEIC500_D_UNITS: VocabUnitMeta[] = [
  { unit: 17, title: "頻出基礎語（TOEIC500・その17）", lesson: "よく使う基礎語を英語→日本語の4択でおぼえよう。" },
  { unit: 18, title: "頻出基礎語（TOEIC500・その18）", lesson: "よく使う基礎語を英語→日本語の4択でおぼえよう。" },
  { unit: 19, title: "頻出基礎語（TOEIC500・その19）", lesson: "よく使う基礎語を英語→日本語の4択でおぼえよう。" },
  { unit: 20, title: "頻出基礎語（TOEIC500・その20）", lesson: "よく使う基礎語を英語→日本語の4択でおぼえよう。" },
  { unit: 21, title: "頻出基礎語（TOEIC500・その21）", lesson: "よく使う基礎語を英語→日本語の4択でおぼえよう。" },
  { unit: 22, title: "頻出基礎語（TOEIC500・その22）", lesson: "よく使う基礎語を英語→日本語の4択でおぼえよう。" },
  { unit: 23, title: "頻出基礎語（TOEIC500・その23）", lesson: "よく使う基礎語を英語→日本語の4択でおぼえよう。" },
  { unit: 24, title: "頻出基礎語（TOEIC500・その24）", lesson: "よく使う基礎語を英語→日本語の4択でおぼえよう。" },
  { unit: 25, title: "頻出基礎語（TOEIC500・その25）", lesson: "よく使う基礎語を英語→日本語の4択でおぼえよう。" },
  { unit: 26, title: "頻出基礎語（TOEIC500・その26）", lesson: "よく使う基礎語を英語→日本語の4択でおぼえよう。" },
  { unit: 27, title: "頻出基礎語（TOEIC500・その27）", lesson: "よく使う基礎語を英語→日本語の4択でおぼえよう。" },
];

export const TOEIC500_D_VOCAB: VocabEntry[] = [
  { word: "base", pos: "名", ja: "土台", example: "the base of a wall（壁の土台）", unit: 17 },
  { word: "beam", pos: "名", ja: "光線", example: "a beam of light（一筋の光）", unit: 17 },
  { word: "bit", pos: "副", ja: "少し", example: "a bit tired（少し疲れた）", unit: 17 },
  { word: "bow", pos: "名", ja: "弓", example: "shoot a bow（弓を射る）", unit: 17 },
  { word: "brass", pos: "名", ja: "真ちゅう", example: "a brass band（ブラスバンド）", unit: 17 },
  { word: "bus", pos: "名", ja: "バス", example: "take a bus（バスに乗る）", unit: 17 },
  { word: "car", pos: "名", ja: "自動車", example: "drive a car（車を運転する）", unit: 17 },
  { word: "card", pos: "名", ja: "カード", example: "a birthday card（誕生日カード）", unit: 17 },
  { word: "care", pos: "名", ja: "世話", example: "take care of（世話をする）", unit: 17 },
  { word: "chief", pos: "名", ja: "長", example: "the chief of police（警察署長）", unit: 17 },
  { word: "club", pos: "名", ja: "クラブ", example: "join a club（クラブに入る）", unit: 17 },
  { word: "come", pos: "動", ja: "来る", example: "come here（こっちに来て）", unit: 17 },
  { word: "corner", pos: "名", ja: "角", example: "turn the corner（角を曲がる）", unit: 17 },
  { word: "critic", pos: "名", ja: "評論家", example: "a film critic（映画評論家）", unit: 17 },
  { word: "cut", pos: "動", ja: "切る", example: "cut the paper（紙を切る）", unit: 17 },
  { word: "damage", pos: "名", ja: "損害", example: "cause damage（損害を与える）", unit: 17 },
  { word: "damp", pos: "形", ja: "湿った", example: "a damp cloth（湿った布）", unit: 17 },
  { word: "dance", pos: "動", ja: "踊る", example: "dance together（一緒に踊る）", unit: 17 },
  { word: "danger", pos: "名", ja: "危険", example: "in danger（危険な状態で）", unit: 17 },
  { word: "dark", pos: "形", ja: "暗い", example: "a dark room（暗い部屋）", unit: 17 },
  { word: "date", pos: "名", ja: "日付", example: "today's date（今日の日付）", unit: 18 },
  { word: "daughter", pos: "名", ja: "娘", example: "my daughter（私の娘）", unit: 18 },
  { word: "day", pos: "名", ja: "日", example: "a sunny day（晴れた日）", unit: 18 },
  { word: "daylight", pos: "名", ja: "日中", example: "in daylight（日中に）", unit: 18 },
  { word: "dead", pos: "形", ja: "死んだ", example: "a dead bird（死んだ鳥）", unit: 18 },
  { word: "deal", pos: "動", ja: "扱う", example: "deal with a problem（問題を扱う）", unit: 18 },
  { word: "dear", pos: "形", ja: "親愛な", example: "a dear friend（親しい友）", unit: 18 },
  { word: "death", pos: "名", ja: "死", example: "a sudden death（突然の死）", unit: 18 },
  { word: "debt", pos: "名", ja: "借金", example: "pay a debt（借金を返す）", unit: 18 },
  { word: "decay", pos: "動", ja: "腐る", example: "teeth decay（歯が虫歯になる）", unit: 18 },
  { word: "decision", pos: "名", ja: "決定", example: "make a decision（決定する）", unit: 18 },
  { word: "deed", pos: "名", ja: "行為", example: "a good deed（善い行い）", unit: 18 },
  { word: "deep", pos: "形", ja: "深い", example: "a deep river（深い川）", unit: 18 },
  { word: "delicate", pos: "形", ja: "繊細な", example: "a delicate flower（繊細な花）", unit: 18 },
  { word: "delight", pos: "名", ja: "大喜び", example: "to my delight（うれしいことに）", unit: 18 },
  { word: "desire", pos: "動", ja: "切望する", example: "desire success（成功を切望する）", unit: 18 },
  { word: "desk", pos: "名", ja: "机", example: "sit at a desk（机に向かう）", unit: 18 },
  { word: "destruction", pos: "名", ja: "破壊", example: "cause destruction（破壊を招く）", unit: 18 },
  { word: "detail", pos: "名", ja: "細部", example: "in detail（詳しく）", unit: 18 },
  { word: "devil", pos: "名", ja: "悪魔", example: "fight the devil（悪魔と戦う）", unit: 18 },
  { word: "dictionary", pos: "名", ja: "辞書", example: "use a dictionary（辞書を引く）", unit: 19 },
  { word: "die", pos: "動", ja: "死ぬ", example: "die young（若くして死ぬ）", unit: 19 },
  { word: "difference", pos: "名", ja: "違い", example: "tell the difference（違いがわかる）", unit: 19 },
  { word: "different", pos: "形", ja: "異なった", example: "a different way（違う方法）", unit: 19 },
  { word: "dig", pos: "動", ja: "掘る", example: "dig a hole（穴を掘る）", unit: 19 },
  { word: "dine", pos: "動", ja: "食事する", example: "dine out（外食する）", unit: 19 },
  { word: "dinner", pos: "名", ja: "夕食", example: "have dinner（夕食を食べる）", unit: 19 },
  { word: "dip", pos: "動", ja: "浸す", example: "dip in water（水に浸す）", unit: 19 },
  { word: "direction", pos: "名", ja: "方向", example: "in that direction（その方向へ）", unit: 19 },
  { word: "dirt", pos: "名", ja: "汚れ", example: "covered in dirt（汚れだらけ）", unit: 19 },
  { word: "disagree", pos: "動", ja: "反対する", example: "disagree with him（彼に反対する）", unit: 19 },
  { word: "disappear", pos: "動", ja: "消える", example: "suddenly disappear（突然消える）", unit: 19 },
  { word: "dish", pos: "名", ja: "料理", example: "a tasty dish（おいしい料理）", unit: 19 },
  { word: "dive", pos: "動", ja: "飛び込む", example: "dive into the pool（プールに飛び込む）", unit: 19 },
  { word: "doctor", pos: "名", ja: "医者", example: "see a doctor（医者に診てもらう）", unit: 19 },
  { word: "dog", pos: "名", ja: "犬", example: "walk the dog（犬を散歩させる）", unit: 19 },
  { word: "dollar", pos: "名", ja: "ドル", example: "ten dollars（10ドル）", unit: 19 },
  { word: "door", pos: "名", ja: "ドア", example: "open the door（ドアを開ける）", unit: 19 },
  { word: "dozen", pos: "名", ja: "ダース", example: "a dozen eggs（卵1ダース）", unit: 19 },
  { word: "drag", pos: "動", ja: "引きずる", example: "drag a chair（椅子を引きずる）", unit: 19 },
  { word: "dream", pos: "名", ja: "夢", example: "have a dream（夢を見る）", unit: 20 },
  { word: "dress", pos: "名", ja: "ドレス", example: "wear a dress（ドレスを着る）", unit: 20 },
  { word: "drink", pos: "動", ja: "飲む", example: "drink water（水を飲む）", unit: 20 },
  { word: "drop", pos: "動", ja: "落とす", example: "drop a glass（グラスを落とす）", unit: 20 },
  { word: "drum", pos: "名", ja: "太鼓", example: "play the drums（ドラムを叩く）", unit: 20 },
  { word: "dry", pos: "形", ja: "乾いた", example: "dry clothes（乾いた服）", unit: 20 },
  { word: "duck", pos: "名", ja: "アヒル", example: "a yellow duck（黄色いアヒル）", unit: 20 },
  { word: "dust", pos: "名", ja: "ほこり", example: "wipe the dust（ほこりを拭く）", unit: 20 },
  { word: "ear", pos: "名", ja: "耳", example: "cover your ears（耳をふさぐ）", unit: 20 },
  { word: "early", pos: "形", ja: "早い", example: "an early start（早い出発）", unit: 20 },
  { word: "earth", pos: "名", ja: "地球", example: "life on earth（地球上の生命）", unit: 20 },
  { word: "east", pos: "名", ja: "東", example: "in the east（東の方に）", unit: 20 },
  { word: "eastern", pos: "形", ja: "東の", example: "eastern Japan（東日本）", unit: 20 },
  { word: "easy", pos: "形", ja: "簡単な", example: "an easy test（簡単なテスト）", unit: 20 },
  { word: "eat", pos: "動", ja: "食べる", example: "eat breakfast（朝食を食べる）", unit: 20 },
  { word: "edge", pos: "名", ja: "端", example: "the edge of a table（テーブルの端）", unit: 20 },
  { word: "educator", pos: "名", ja: "教育者", example: "a famous educator（有名な教育者）", unit: 20 },
  { word: "efficiency", pos: "名", ja: "効率", example: "work efficiency（作業効率）", unit: 20 },
  { word: "egg", pos: "名", ja: "卵", example: "boil an egg（卵をゆでる）", unit: 20 },
  { word: "elder", pos: "形", ja: "年上の", example: "my elder sister（私の姉）", unit: 20 },
  { word: "electric", pos: "形", ja: "電気の", example: "an electric car（電気自動車）", unit: 21 },
  { word: "elephant", pos: "名", ja: "ゾウ", example: "a big elephant（大きなゾウ）", unit: 21 },
  { word: "end", pos: "名", ja: "終わり", example: "the end of the story（物語の終わり）", unit: 21 },
  { word: "engine", pos: "名", ja: "エンジン", example: "start the engine（エンジンをかける）", unit: 21 },
  { word: "enjoy", pos: "動", ja: "楽しむ", example: "enjoy the party（パーティーを楽しむ）", unit: 21 },
  { word: "entertain", pos: "動", ja: "もてなす", example: "entertain guests（客をもてなす）", unit: 21 },
  { word: "envy", pos: "名", ja: "ねたみ", example: "full of envy（ねたみでいっぱい）", unit: 21 },
  { word: "especially", pos: "副", ja: "特に", example: "especially cold（特に寒い）", unit: 21 },
  { word: "evening", pos: "名", ja: "夕方", example: "this evening（今晩）", unit: 21 },
  { word: "evil", pos: "形", ja: "邪悪な", example: "an evil plan（邪悪な計画）", unit: 21 },
  { word: "example", pos: "名", ja: "例", example: "for example（例えば）", unit: 21 },
  { word: "excess", pos: "名", ja: "過剰", example: "in excess（過剰に）", unit: 21 },
  { word: "explosion", pos: "名", ja: "爆発", example: "a loud explosion（大きな爆発）", unit: 21 },
  { word: "explosive", pos: "形", ja: "爆発性の", example: "explosive gas（爆発性のガス）", unit: 21 },
  { word: "extension", pos: "名", ja: "延長", example: "an extension of time（期間の延長）", unit: 21 },
  { word: "extra", pos: "形", ja: "余分な", example: "an extra chair（余分な椅子）", unit: 21 },
  { word: "eye", pos: "名", ja: "目", example: "close your eyes（目を閉じる）", unit: 21 },
  { word: "face", pos: "名", ja: "顔", example: "wash your face（顔を洗う）", unit: 21 },
  { word: "faint", pos: "形", ja: "かすかな", example: "a faint sound（かすかな音）", unit: 21 },
  { word: "fall", pos: "動", ja: "落ちる", example: "leaves fall（葉が落ちる）", unit: 21 },
  { word: "family", pos: "名", ja: "家族", example: "a big family（大家族）", unit: 22 },
  { word: "fan", pos: "名", ja: "扇風機", example: "turn on the fan（扇風機をつける）", unit: 22 },
  { word: "fancy", pos: "形", ja: "高級な", example: "a fancy hotel（高級ホテル）", unit: 22 },
  { word: "far", pos: "副", ja: "遠くに", example: "far away（遠く離れて）", unit: 22 },
  { word: "farm", pos: "名", ja: "農場", example: "work on a farm（農場で働く）", unit: 22 },
  { word: "fast", pos: "形", ja: "速い", example: "a fast car（速い車）", unit: 22 },
  { word: "fat", pos: "名", ja: "脂肪", example: "body fat（体脂肪）", unit: 22 },
  { word: "fate", pos: "名", ja: "運命", example: "decide one's fate（運命を決める）", unit: 22 },
  { word: "father", pos: "名", ja: "父", example: "my father（私の父）", unit: 22 },
  { word: "feather", pos: "名", ja: "羽", example: "a soft feather（柔らかい羽）", unit: 22 },
  { word: "feel", pos: "動", ja: "感じる", example: "feel happy（幸せに感じる）", unit: 22 },
  { word: "female", pos: "形", ja: "女性の", example: "a female doctor（女性の医師）", unit: 22 },
  { word: "fence", pos: "名", ja: "塀", example: "build a fence（塀を作る）", unit: 22 },
  { word: "field", pos: "名", ja: "野原", example: "a green field（緑の野原）", unit: 22 },
  { word: "fight", pos: "動", ja: "戦う", example: "fight for peace（平和のために戦う）", unit: 22 },
  { word: "figure", pos: "名", ja: "数字", example: "sales figures（売上の数字）", unit: 22 },
  { word: "film", pos: "名", ja: "映画", example: "watch a film（映画を見る）", unit: 22 },
  { word: "find", pos: "動", ja: "見つける", example: "find a key（鍵を見つける）", unit: 22 },
  { word: "fine", pos: "形", ja: "立派な", example: "a fine artist（立派な芸術家）", unit: 22 },
  { word: "finger", pos: "名", ja: "指", example: "point a finger（指をさす）", unit: 22 },
  { word: "fire", pos: "名", ja: "火", example: "make a fire（火をおこす）", unit: 23 },
  { word: "fish", pos: "名", ja: "魚", example: "catch a fish（魚を捕まえる）", unit: 23 },
  { word: "fit", pos: "形", ja: "適した", example: "fit for the job（仕事に適した）", unit: 23 },
  { word: "flag", pos: "名", ja: "旗", example: "a national flag（国旗）", unit: 23 },
  { word: "flame", pos: "名", ja: "炎", example: "a bright flame（明るい炎）", unit: 23 },
  { word: "flash", pos: "名", ja: "閃光", example: "a flash of light（光の閃光）", unit: 23 },
  { word: "flesh", pos: "名", ja: "肉体", example: "human flesh（人間の肉体）", unit: 23 },
  { word: "flood", pos: "名", ja: "洪水", example: "a big flood（大きな洪水）", unit: 23 },
  { word: "floor", pos: "名", ja: "床", example: "clean the floor（床を掃除する）", unit: 23 },
  { word: "flower", pos: "名", ja: "花", example: "a red flower（赤い花）", unit: 23 },
  { word: "fly", pos: "動", ja: "飛ぶ", example: "birds fly（鳥が飛ぶ）", unit: 23 },
  { word: "food", pos: "名", ja: "食物", example: "healthy food（健康的な食べ物）", unit: 23 },
  { word: "fool", pos: "名", ja: "ばか者", example: "call him a fool（彼をばか者と呼ぶ）", unit: 23 },
  { word: "foot", pos: "名", ja: "足", example: "my left foot（私の左足）", unit: 23 },
  { word: "force", pos: "名", ja: "力", example: "use force（力を使う）", unit: 23 },
  { word: "foreign", pos: "形", ja: "外国の", example: "a foreign country（外国）", unit: 23 },
  { word: "forest", pos: "名", ja: "森林", example: "a deep forest（深い森）", unit: 23 },
  { word: "forget", pos: "動", ja: "忘れる", example: "forget the name（名前を忘れる）", unit: 23 },
  { word: "fork", pos: "名", ja: "フォーク", example: "use a fork（フォークを使う）", unit: 23 },
  { word: "form", pos: "名", ja: "形", example: "a round form（丸い形）", unit: 23 },
  { word: "former", pos: "形", ja: "かつての", example: "a former teacher（元教師）", unit: 24 },
  { word: "forward", pos: "副", ja: "前方へ", example: "move forward（前へ進む）", unit: 24 },
  { word: "frame", pos: "名", ja: "骨組み", example: "a picture frame（額縁）", unit: 24 },
  { word: "free", pos: "形", ja: "自由な", example: "free time（自由な時間）", unit: 24 },
  { word: "friend", pos: "名", ja: "友人", example: "a close friend（親友）", unit: 24 },
  { word: "friendly", pos: "形", ja: "親しみやすい", example: "a friendly smile（親しみやすい笑顔）", unit: 24 },
  { word: "front", pos: "名", ja: "前面", example: "the front door（正面のドア）", unit: 24 },
  { word: "fruit", pos: "名", ja: "果物", example: "fresh fruit（新鮮な果物）", unit: 24 },
  { word: "full", pos: "形", ja: "いっぱいの", example: "a full glass（いっぱいのグラス）", unit: 24 },
  { word: "fun", pos: "名", ja: "楽しみ", example: "have fun（楽しむ）", unit: 24 },
  { word: "funny", pos: "形", ja: "おかしい", example: "a funny story（おかしい話）", unit: 24 },
  { word: "fur", pos: "名", ja: "毛皮", example: "soft fur（柔らかい毛皮）", unit: 24 },
  { word: "game", pos: "名", ja: "試合", example: "play a game（試合をする）", unit: 24 },
  { word: "gap", pos: "名", ja: "隙間", example: "a wide gap（広い隙間）", unit: 24 },
  { word: "garage", pos: "名", ja: "車庫", example: "park in the garage（車庫に停める）", unit: 24 },
  { word: "garden", pos: "名", ja: "庭", example: "a flower garden（花の庭）", unit: 24 },
  { word: "gas", pos: "名", ja: "気体", example: "natural gas（天然ガス）", unit: 24 },
  { word: "gate", pos: "名", ja: "門", example: "open the gate（門を開ける）", unit: 24 },
  { word: "general", pos: "形", ja: "全般的な", example: "general rules（一般的な規則）", unit: 24 },
  { word: "gentle", pos: "形", ja: "優しい", example: "a gentle voice（優しい声）", unit: 24 },
  { word: "gentleman", pos: "名", ja: "紳士", example: "a kind gentleman（親切な紳士）", unit: 25 },
  { word: "gift", pos: "名", ja: "贈り物", example: "a birthday gift（誕生日の贈り物）", unit: 25 },
  { word: "girl", pos: "名", ja: "女の子", example: "a little girl（小さな女の子）", unit: 25 },
  { word: "give", pos: "動", ja: "与える", example: "give a gift（贈り物をあげる）", unit: 25 },
  { word: "glad", pos: "形", ja: "うれしい", example: "I'm glad（うれしいです）", unit: 25 },
  { word: "glass", pos: "名", ja: "ガラス", example: "a glass of water（コップ一杯の水）", unit: 25 },
  { word: "glory", pos: "名", ja: "栄光", example: "win glory（栄光を得る）", unit: 25 },
  { word: "god", pos: "名", ja: "神", example: "believe in god（神を信じる）", unit: 25 },
  { word: "gold", pos: "名", ja: "金", example: "pure gold（純金）", unit: 25 },
  { word: "golden", pos: "形", ja: "金色の", example: "golden hair（金色の髪）", unit: 25 },
  { word: "good", pos: "形", ja: "よい", example: "a good idea（よい考え）", unit: 25 },
  { word: "govern", pos: "動", ja: "統治する", example: "govern a country（国を統治する）", unit: 25 },
  { word: "governor", pos: "名", ja: "知事", example: "the state governor（州知事）", unit: 25 },
  { word: "grace", pos: "名", ja: "優雅さ", example: "move with grace（優雅に動く）", unit: 25 },
  { word: "gradual", pos: "形", ja: "段階的な", example: "a gradual change（段階的な変化）", unit: 25 },
  { word: "grain", pos: "名", ja: "穀物", example: "grain and rice（穀物と米）", unit: 25 },
  { word: "grand", pos: "形", ja: "壮大な", example: "a grand hotel（壮大なホテル）", unit: 25 },
  { word: "grass", pos: "名", ja: "草", example: "green grass（緑の草）", unit: 25 },
  { word: "grateful", pos: "形", ja: "感謝している", example: "I'm grateful（感謝しています）", unit: 25 },
  { word: "grave", pos: "名", ja: "墓", example: "visit a grave（墓参りをする）", unit: 25 },
  { word: "great", pos: "形", ja: "偉大な", example: "a great writer（偉大な作家）", unit: 26 },
  { word: "green", pos: "形", ja: "緑の", example: "a green leaf（緑の葉）", unit: 26 },
  { word: "greet", pos: "動", ja: "あいさつする", example: "greet a guest（客にあいさつする）", unit: 26 },
  { word: "grind", pos: "動", ja: "すりつぶす", example: "grind coffee（コーヒーを挽く）", unit: 26 },
  { word: "ground", pos: "名", ja: "地面", example: "fall to the ground（地面に落ちる）", unit: 26 },
  { word: "group", pos: "名", ja: "集団", example: "a group of people（人々の集団）", unit: 26 },
  { word: "grow", pos: "動", ja: "成長する", example: "grow fast（速く成長する）", unit: 26 },
  { word: "growth", pos: "名", ja: "成長", example: "economic growth（経済成長）", unit: 26 },
  { word: "guard", pos: "名", ja: "警備員", example: "a security guard（警備員）", unit: 26 },
  { word: "guess", pos: "動", ja: "推測する", example: "guess the answer（答えを推測する）", unit: 26 },
  { word: "guide", pos: "動", ja: "案内する", example: "guide a tourist（観光客を案内する）", unit: 26 },
  { word: "guilt", pos: "名", ja: "罪悪感", example: "feel guilt（罪悪感を抱く）", unit: 26 },
  { word: "gun", pos: "名", ja: "銃", example: "fire a gun（銃を撃つ）", unit: 26 },
  { word: "hair", pos: "名", ja: "髪", example: "long hair（長い髪）", unit: 26 },
  { word: "half", pos: "名", ja: "半分", example: "half an hour（30分）", unit: 26 },
  { word: "hall", pos: "名", ja: "広間", example: "a large hall（大広間）", unit: 26 },
  { word: "hand", pos: "名", ja: "手", example: "raise your hand（手を挙げる）", unit: 26 },
  { word: "hang", pos: "動", ja: "掛ける", example: "hang a picture（絵を掛ける）", unit: 26 },
  { word: "happen", pos: "動", ja: "起こる", example: "what happened（何が起きたのか）", unit: 26 },
  { word: "happy", pos: "形", ja: "幸福な", example: "a happy family（幸せな家族）", unit: 26 },
  { word: "hardly", pos: "副", ja: "ほとんど〜ない", example: "hardly know（ほとんど知らない）", unit: 27 },
  { word: "harm", pos: "名", ja: "害", example: "do harm（害を与える）", unit: 27 },
  { word: "harvest", pos: "名", ja: "収穫", example: "a good harvest（豊作）", unit: 27 },
  { word: "haste", pos: "名", ja: "急ぎ", example: "in haste（急いで）", unit: 27 },
  { word: "hat", pos: "名", ja: "帽子", example: "wear a hat（帽子をかぶる）", unit: 27 },
  { word: "hate", pos: "動", ja: "憎む", example: "hate lying（うそをつくのが嫌い）", unit: 27 },
  { word: "hatred", pos: "名", ja: "憎しみ", example: "deep hatred（深い憎しみ）", unit: 27 },
  { word: "head", pos: "名", ja: "頭", example: "turn your head（頭を回す）", unit: 27 },
  { word: "heal", pos: "動", ja: "治す", example: "heal a wound（傷を治す）", unit: 27 },
  { word: "health", pos: "名", ja: "健康", example: "good health（健康）", unit: 27 },
  { word: "heap", pos: "名", ja: "山積み", example: "a heap of sand（砂の山）", unit: 27 },
  { word: "hear", pos: "動", ja: "聞こえる", example: "hear a sound（音が聞こえる）", unit: 27 },
  { word: "heart", pos: "名", ja: "心臓", example: "a strong heart（丈夫な心臓）", unit: 27 },
  { word: "heaven", pos: "名", ja: "天国", example: "go to heaven（天国へ行く）", unit: 27 },
  { word: "heavy", pos: "形", ja: "重い", example: "a heavy bag（重いかばん）", unit: 27 },
  { word: "height", pos: "名", ja: "高さ", example: "the height of a wall（壁の高さ）", unit: 27 },
  { word: "help", pos: "動", ja: "手伝う", example: "help a friend（友達を助ける）", unit: 27 },
  { word: "hesitate", pos: "動", ja: "ためらう", example: "hesitate to ask（尋ねるのをためらう）", unit: 27 },
  { word: "hide", pos: "動", ja: "隠す", example: "hide a key（鍵を隠す）", unit: 27 },
  { word: "high", pos: "形", ja: "高い", example: "a high mountain（高い山）", unit: 27 },
];
