// 語彙パック: TOEIC500 バンド 追加分G（頻出基礎語）。
// ejdict-hand(CC0) 取込→並列サブエージェントで語義是正・機能語除去したもの。
// 既存の全 eikaiwa 語と word・ja が重複しないよう調整済み（意味は全トラックで一意）。
import type { VocabEntry, VocabUnitMeta } from "./types";

export const TOEIC500_G_UNITS: VocabUnitMeta[] = [
  { unit: 53, title: "頻出基礎語（TOEIC500・その53）", lesson: "よく使う基礎語を英語→日本語の4択でおぼえよう。" },
  { unit: 54, title: "頻出基礎語（TOEIC500・その54）", lesson: "よく使う基礎語を英語→日本語の4択でおぼえよう。" },
  { unit: 55, title: "頻出基礎語（TOEIC500・その55）", lesson: "よく使う基礎語を英語→日本語の4択でおぼえよう。" },
  { unit: 56, title: "頻出基礎語（TOEIC500・その56）", lesson: "よく使う基礎語を英語→日本語の4択でおぼえよう。" },
  { unit: 57, title: "頻出基礎語（TOEIC500・その57）", lesson: "よく使う基礎語を英語→日本語の4択でおぼえよう。" },
  { unit: 58, title: "頻出基礎語（TOEIC500・その58）", lesson: "よく使う基礎語を英語→日本語の4択でおぼえよう。" },
  { unit: 59, title: "頻出基礎語（TOEIC500・その59）", lesson: "よく使う基礎語を英語→日本語の4択でおぼえよう。" },
  { unit: 60, title: "頻出基礎語（TOEIC500・その60）", lesson: "よく使う基礎語を英語→日本語の4択でおぼえよう。" },
  { unit: 61, title: "頻出基礎語（TOEIC500・その61）", lesson: "よく使う基礎語を英語→日本語の4択でおぼえよう。" },
  { unit: 62, title: "頻出基礎語（TOEIC500・その62）", lesson: "よく使う基礎語を英語→日本語の4択でおぼえよう。" },
  { unit: 63, title: "頻出基礎語（TOEIC500・その63）", lesson: "よく使う基礎語を英語→日本語の4択でおぼえよう。" },
  { unit: 64, title: "頻出基礎語（TOEIC500・その64）", lesson: "よく使う基礎語を英語→日本語の4択でおぼえよう。" },
];

export const TOEIC500_G_VOCAB: VocabEntry[] = [
  { word: "mechanism", pos: "名", ja: "仕組み", example: "a simple mechanism（単純な仕組み）", unit: 53 },
  { word: "package", pos: "名", ja: "小包", example: "send a package（小包を送る）", unit: 53 },
  { word: "piece", pos: "名", ja: "一切れ", example: "a piece of cake（ケーキ一切れ）", unit: 53 },
  { word: "rapid", pos: "形", ja: "急速な", example: "rapid growth（急速な成長）", unit: 53 },
  { word: "regular", pos: "形", ja: "定期的な", example: "a regular meeting（定期的な会議）", unit: 53 },
  { word: "save", pos: "動", ja: "節約する", example: "save money（お金を節約する）", unit: 53 },
  { word: "seem", pos: "動", ja: "～に見える", example: "seem happy（幸せそうに見える）", unit: 53 },
  { word: "sell", pos: "動", ja: "売る", example: "sell a car（車を売る）", unit: 53 },
  { word: "send", pos: "動", ja: "送る", example: "send an email（メールを送る）", unit: 53 },
  { word: "sense", pos: "名", ja: "感覚", example: "a sense of humor（ユーモアの感覚）", unit: 53 },
  { word: "sensitive", pos: "形", ja: "敏感な", example: "sensitive skin（敏感な肌）", unit: 53 },
  { word: "sentence", pos: "名", ja: "文", example: "write a sentence（文を書く）", unit: 53 },
  { word: "separation", pos: "名", ja: "分離", example: "a long separation（長い分離）", unit: 53 },
  { word: "serious", pos: "形", ja: "深刻な", example: "a serious problem（深刻な問題）", unit: 53 },
  { word: "servant", pos: "名", ja: "召使い", example: "a loyal servant（忠実な召使い）", unit: 53 },
  { word: "serve", pos: "動", ja: "出す", example: "serve dinner（夕食を出す）", unit: 53 },
  { word: "service", pos: "名", ja: "サービス", example: "good service（良いサービス）", unit: 53 },
  { word: "set", pos: "動", ja: "置く", example: "set the cup down（カップを置く）", unit: 53 },
  { word: "settle", pos: "動", ja: "解決する", example: "settle the dispute（争いを解決する）", unit: 53 },
  { word: "severe", pos: "形", ja: "厳しい", example: "severe weather（厳しい天候）", unit: 53 },
  { word: "sew", pos: "動", ja: "縫う", example: "sew a button（ボタンを縫う）", unit: 54 },
  { word: "shade", pos: "名", ja: "日陰", example: "sit in the shade（日陰に座る）", unit: 54 },
  { word: "shake", pos: "動", ja: "振る", example: "shake the bottle（瓶を振る）", unit: 54 },
  { word: "shallow", pos: "形", ja: "浅い", example: "shallow water（浅い水）", unit: 54 },
  { word: "shame", pos: "名", ja: "恥", example: "feel shame（恥を感じる）", unit: 54 },
  { word: "share", pos: "動", ja: "分け合う", example: "share the pizza（ピザを分け合う）", unit: 54 },
  { word: "sharp", pos: "形", ja: "鋭い", example: "a sharp knife（鋭いナイフ）", unit: 54 },
  { word: "shave", pos: "動", ja: "そる", example: "shave one's beard（ひげをそる）", unit: 54 },
  { word: "sheep", pos: "名", ja: "羊", example: "a flock of sheep（羊の群れ）", unit: 54 },
  { word: "sheet", pos: "名", ja: "シーツ", example: "a clean sheet（きれいなシーツ）", unit: 54 },
  { word: "shelf", pos: "名", ja: "棚", example: "a book on the shelf（棚の本）", unit: 54 },
  { word: "shell", pos: "名", ja: "貝がら", example: "a seashell（貝がら）", unit: 54 },
  { word: "shelter", pos: "名", ja: "避難所", example: "a shelter from rain（雨宿りの場所）", unit: 54 },
  { word: "shield", pos: "名", ja: "盾", example: "raise a shield（盾を構える）", unit: 54 },
  { word: "shine", pos: "動", ja: "光る", example: "the stars shine（星が光る）", unit: 54 },
  { word: "ship", pos: "名", ja: "船", example: "a big ship（大きな船）", unit: 54 },
  { word: "shirt", pos: "名", ja: "シャツ", example: "a white shirt（白いシャツ）", unit: 54 },
  { word: "shock", pos: "名", ja: "衝撃", example: "a big shock（大きな衝撃）", unit: 54 },
  { word: "shoe", pos: "名", ja: "靴", example: "new shoes（新しい靴）", unit: 54 },
  { word: "shoot", pos: "動", ja: "撃つ", example: "shoot an arrow（矢を撃つ）", unit: 54 },
  { word: "shop", pos: "名", ja: "店", example: "a small shop（小さな店）", unit: 55 },
  { word: "shore", pos: "名", ja: "岸", example: "walk on the shore（岸を歩く）", unit: 55 },
  { word: "short", pos: "形", ja: "短い", example: "a short story（短い話）", unit: 55 },
  { word: "shoulder", pos: "名", ja: "肩", example: "a sore shoulder（痛む肩）", unit: 55 },
  { word: "shout", pos: "動", ja: "叫ぶ", example: "shout loudly（大声で叫ぶ）", unit: 55 },
  { word: "show", pos: "動", ja: "見せる", example: "show a photo（写真を見せる）", unit: 55 },
  { word: "shower", pos: "名", ja: "シャワー", example: "take a shower（シャワーを浴びる）", unit: 55 },
  { word: "shut", pos: "動", ja: "閉める", example: "shut the window（窓を閉める）", unit: 55 },
  { word: "side", pos: "名", ja: "側", example: "the other side（反対側）", unit: 55 },
  { word: "sight", pos: "名", ja: "光景", example: "a beautiful sight（美しい光景）", unit: 55 },
  { word: "sign", pos: "名", ja: "標識", example: "a road sign（道路標識）", unit: 55 },
  { word: "signal", pos: "名", ja: "信号", example: "a stop signal（停止信号）", unit: 55 },
  { word: "silence", pos: "名", ja: "静けさ", example: "total silence（完全な静けさ）", unit: 55 },
  { word: "silver", pos: "名", ja: "銀", example: "a silver ring（銀の指輪）", unit: 55 },
  { word: "simplicity", pos: "名", ja: "簡素さ", example: "the simplicity of design（デザインの簡素さ）", unit: 55 },
  { word: "sincere", pos: "形", ja: "誠実な", example: "a sincere apology（誠実な謝罪）", unit: 55 },
  { word: "sing", pos: "動", ja: "歌う", example: "sing a song（歌を歌う）", unit: 55 },
  { word: "single", pos: "形", ja: "たった一つの", example: "a single word（たった一つの言葉）", unit: 55 },
  { word: "sink", pos: "動", ja: "沈む", example: "the ship sinks（船が沈む）", unit: 55 },
  { word: "sister", pos: "名", ja: "姉妹", example: "my little sister（私の妹）", unit: 55 },
  { word: "sit", pos: "動", ja: "座る", example: "sit on a chair（いすに座る）", unit: 56 },
  { word: "situation", pos: "名", ja: "状況", example: "a difficult situation（難しい状況）", unit: 56 },
  { word: "size", pos: "名", ja: "大きさ", example: "the right size（ちょうどいい大きさ）", unit: 56 },
  { word: "skill", pos: "名", ja: "技術", example: "a useful skill（役立つ技術）", unit: 56 },
  { word: "skin", pos: "名", ja: "肌", example: "soft skin（柔らかい肌）", unit: 56 },
  { word: "skirt", pos: "名", ja: "スカート", example: "a long skirt（長いスカート）", unit: 56 },
  { word: "sky", pos: "名", ja: "空", example: "a blue sky（青い空）", unit: 56 },
  { word: "slave", pos: "名", ja: "奴隷", example: "free the slaves（奴隷を解放する）", unit: 56 },
  { word: "slavery", pos: "名", ja: "奴隷制度", example: "abolish slavery（奴隷制度を廃止する）", unit: 56 },
  { word: "sleep", pos: "動", ja: "眠る", example: "sleep well（よく眠る）", unit: 56 },
  { word: "slide", pos: "動", ja: "滑る", example: "slide on the ice（氷の上を滑る）", unit: 56 },
  { word: "slight", pos: "形", ja: "わずかな", example: "a slight change（わずかな変化）", unit: 56 },
  { word: "slope", pos: "名", ja: "坂", example: "a steep slope（急な坂）", unit: 56 },
  { word: "slow", pos: "形", ja: "遅い", example: "a slow train（遅い電車）", unit: 56 },
  { word: "small", pos: "形", ja: "小さい", example: "a small dog（小さい犬）", unit: 56 },
  { word: "smell", pos: "動", ja: "においがする", example: "smell nice（いいにおいがする）", unit: 56 },
  { word: "smile", pos: "動", ja: "ほほえむ", example: "smile at me（私にほほえむ）", unit: 56 },
  { word: "smoke", pos: "名", ja: "煙", example: "black smoke（黒い煙）", unit: 56 },
  { word: "smooth", pos: "形", ja: "滑らかな", example: "smooth skin（滑らかな肌）", unit: 56 },
  { word: "snake", pos: "名", ja: "ヘビ", example: "a big snake（大きなヘビ）", unit: 56 },
  { word: "snow", pos: "名", ja: "雪", example: "white snow（白い雪）", unit: 57 },
  { word: "soap", pos: "名", ja: "石けん", example: "wash with soap（石けんで洗う）", unit: 57 },
  { word: "social", pos: "形", ja: "社会の", example: "a social problem（社会の問題）", unit: 57 },
  { word: "society", pos: "名", ja: "社会", example: "modern society（現代社会）", unit: 57 },
  { word: "soft", pos: "形", ja: "柔らかい", example: "a soft pillow（柔らかい枕）", unit: 57 },
  { word: "soften", pos: "動", ja: "柔らかくする", example: "soften the butter（バターを柔らかくする）", unit: 57 },
  { word: "soil", pos: "名", ja: "土", example: "rich soil（豊かな土）", unit: 57 },
  { word: "soldier", pos: "名", ja: "兵士", example: "a brave soldier（勇敢な兵士）", unit: 57 },
  { word: "solid", pos: "形", ja: "固体の", example: "a solid object（固体の物）", unit: 57 },
  { word: "solution", pos: "名", ja: "解決策", example: "find a solution（解決策を見つける）", unit: 57 },
  { word: "solve", pos: "動", ja: "解く", example: "solve a problem（問題を解く）", unit: 57 },
  { word: "somehow", pos: "副", ja: "どうにかして", example: "manage somehow（どうにかしてやりくりする）", unit: 57 },
  { word: "sometimes", pos: "副", ja: "ときどき", example: "sometimes late（ときどき遅れる）", unit: 57 },
  { word: "son", pos: "名", ja: "息子", example: "my son（私の息子）", unit: 57 },
  { word: "song", pos: "名", ja: "歌", example: "sing a song（歌を歌う）", unit: 57 },
  { word: "soon", pos: "副", ja: "間もなく", example: "see you soon（間もなく会おう）", unit: 57 },
  { word: "sort", pos: "名", ja: "種類", example: "a sort of fruit（ある種類の果物）", unit: 57 },
  { word: "soul", pos: "名", ja: "魂", example: "a kind soul（優しい魂）", unit: 57 },
  { word: "sound", pos: "名", ja: "音", example: "a loud sound（大きな音）", unit: 57 },
  { word: "soup", pos: "名", ja: "スープ", example: "hot soup（熱いスープ）", unit: 57 },
  { word: "south", pos: "名", ja: "南", example: "to the south（南へ）", unit: 58 },
  { word: "space", pos: "名", ja: "空間", example: "empty space（空いた空間）", unit: 58 },
  { word: "speak", pos: "動", ja: "話す", example: "speak English（英語を話す）", unit: 58 },
  { word: "special", pos: "形", ja: "特別な", example: "a special day（特別な日）", unit: 58 },
  { word: "speech", pos: "名", ja: "演説", example: "give a speech（演説をする）", unit: 58 },
  { word: "speed", pos: "名", ja: "速さ", example: "high speed（高い速さ）", unit: 58 },
  { word: "spell", pos: "動", ja: "つづる", example: "spell the word（単語をつづる）", unit: 58 },
  { word: "spend", pos: "動", ja: "使う", example: "spend money（お金を使う）", unit: 58 },
  { word: "spirit", pos: "名", ja: "精神", example: "a strong spirit（強い精神）", unit: 58 },
  { word: "split", pos: "動", ja: "割る", example: "split the wood（木を割る）", unit: 58 },
  { word: "sport", pos: "名", ja: "スポーツ", example: "play a sport（スポーツをする）", unit: 58 },
  { word: "spread", pos: "動", ja: "広げる", example: "spread the map（地図を広げる）", unit: 58 },
  { word: "spring", pos: "名", ja: "春", example: "in spring（春に）", unit: 58 },
  { word: "square", pos: "名", ja: "正方形", example: "draw a square（正方形を描く）", unit: 58 },
  { word: "stage", pos: "名", ja: "舞台", example: "on the stage（舞台の上で）", unit: 58 },
  { word: "stair", pos: "名", ja: "階段", example: "climb the stairs（階段をのぼる）", unit: 58 },
  { word: "stamp", pos: "名", ja: "切手", example: "put a stamp（切手を貼る）", unit: 58 },
  { word: "stand", pos: "動", ja: "立つ", example: "stand up（立ち上がる）", unit: 58 },
  { word: "standard", pos: "名", ja: "基準", example: "a high standard（高い基準）", unit: 58 },
  { word: "star", pos: "名", ja: "星", example: "a bright star（明るい星）", unit: 58 },
  { word: "start", pos: "動", ja: "始める", example: "start work（仕事を始める）", unit: 59 },
  { word: "station", pos: "名", ja: "駅", example: "the train station（電車の駅）", unit: 59 },
  { word: "stay", pos: "動", ja: "とどまる", example: "stay home（家にとどまる）", unit: 59 },
  { word: "steady", pos: "形", ja: "安定した", example: "a steady job（安定した仕事）", unit: 59 },
  { word: "steam", pos: "名", ja: "蒸気", example: "hot steam（熱い蒸気）", unit: 59 },
  { word: "steel", pos: "名", ja: "鋼鉄", example: "made of steel（鋼鉄でできた）", unit: 59 },
  { word: "steep", pos: "形", ja: "急な", example: "a steep hill（急な丘）", unit: 59 },
  { word: "stem", pos: "名", ja: "茎", example: "a flower stem（花の茎）", unit: 59 },
  { word: "step", pos: "名", ja: "一歩", example: "take a step（一歩ふみ出す）", unit: 59 },
  { word: "stiff", pos: "形", ja: "硬い", example: "a stiff board（硬い板）", unit: 59 },
  { word: "stir", pos: "動", ja: "かき混ぜる", example: "stir the soup（スープをかき混ぜる）", unit: 59 },
  { word: "stock", pos: "名", ja: "在庫", example: "out of stock（在庫切れ）", unit: 59 },
  { word: "stomach", pos: "名", ja: "胃", example: "an empty stomach（空腹）", unit: 59 },
  { word: "stone", pos: "名", ja: "石", example: "throw a stone（石を投げる）", unit: 59 },
  { word: "stop", pos: "動", ja: "止める", example: "stop the car（車を止める）", unit: 59 },
  { word: "storm", pos: "名", ja: "嵐", example: "a heavy storm（激しい嵐）", unit: 59 },
  { word: "story", pos: "名", ja: "話", example: "tell a story（話をする）", unit: 59 },
  { word: "stove", pos: "名", ja: "こんろ", example: "cook on the stove（こんろで料理する）", unit: 59 },
  { word: "straight", pos: "形", ja: "まっすぐな", example: "a straight line（まっすぐな線）", unit: 59 },
  { word: "straighten", pos: "動", ja: "まっすぐにする", example: "straighten your back（背筋をまっすぐにする）", unit: 59 },
  { word: "straw", pos: "名", ja: "ストロー", example: "drink with a straw（ストローで飲む）", unit: 60 },
  { word: "stream", pos: "名", ja: "小川", example: "a clear stream（澄んだ小川）", unit: 60 },
  { word: "street", pos: "名", ja: "通り", example: "cross the street（通りを渡る）", unit: 60 },
  { word: "strengthen", pos: "動", ja: "強くする", example: "strengthen muscles（筋肉を強くする）", unit: 60 },
  { word: "stretch", pos: "動", ja: "伸ばす", example: "stretch your arms（腕を伸ばす）", unit: 60 },
  { word: "strike", pos: "動", ja: "打つ", example: "strike the ball（ボールを打つ）", unit: 60 },
  { word: "string", pos: "名", ja: "ひも", example: "tie with string（ひもで結ぶ）", unit: 60 },
  { word: "stroke", pos: "名", ja: "ひとかき", example: "a stroke of a brush（筆のひとかき）", unit: 60 },
  { word: "strong", pos: "形", ja: "強い", example: "a strong man（強い男）", unit: 60 },
  { word: "struggle", pos: "動", ja: "もがく", example: "struggle to escape（逃げようともがく）", unit: 60 },
  { word: "student", pos: "名", ja: "学生", example: "a college student（大学生）", unit: 60 },
  { word: "study", pos: "動", ja: "勉強する", example: "study English（英語を勉強する）", unit: 60 },
  { word: "stuff", pos: "名", ja: "物", example: "put away your stuff（物を片付ける）", unit: 60 },
  { word: "stupid", pos: "形", ja: "ばかな", example: "a stupid mistake（ばかな間違い）", unit: 60 },
  { word: "subject", pos: "名", ja: "科目", example: "my favorite subject（好きな科目）", unit: 60 },
  { word: "substance", pos: "名", ja: "物質", example: "a dangerous substance（危険な物質）", unit: 60 },
  { word: "succeed", pos: "動", ja: "成功する", example: "succeed in business（事業で成功する）", unit: 60 },
  { word: "success", pos: "名", ja: "成功", example: "a great success（大成功）", unit: 60 },
  { word: "suck", pos: "動", ja: "吸う", example: "suck through a straw（ストローで吸う）", unit: 60 },
  { word: "sudden", pos: "形", ja: "突然の", example: "a sudden change（突然の変化）", unit: 60 },
  { word: "suffer", pos: "動", ja: "苦しむ", example: "suffer from pain（痛みに苦しむ）", unit: 61 },
  { word: "sugar", pos: "名", ja: "砂糖", example: "add sugar（砂糖を加える）", unit: 61 },
  { word: "suit", pos: "名", ja: "スーツ", example: "wear a suit（スーツを着る）", unit: 61 },
  { word: "summer", pos: "名", ja: "夏", example: "a hot summer（暑い夏）", unit: 61 },
  { word: "sun", pos: "名", ja: "太陽", example: "the bright sun（明るい太陽）", unit: 61 },
  { word: "supply", pos: "動", ja: "供給する", example: "supply water（水を供給する）", unit: 61 },
  { word: "support", pos: "動", ja: "支える", example: "support the family（家族を支える）", unit: 61 },
  { word: "suppose", pos: "動", ja: "思う", example: "I suppose so（そう思う）", unit: 61 },
  { word: "surface", pos: "名", ja: "表面", example: "a smooth surface（なめらかな表面）", unit: 61 },
  { word: "surround", pos: "動", ja: "囲む", example: "surround the house（家を囲む）", unit: 61 },
  { word: "suspect", pos: "動", ja: "怪しむ", example: "suspect a lie（うそを怪しむ）", unit: 61 },
  { word: "suspicious", pos: "形", ja: "疑わしい", example: "a suspicious man（疑わしい男）", unit: 61 },
  { word: "swallow", pos: "動", ja: "飲み込む", example: "swallow the pill（薬を飲み込む）", unit: 61 },
  { word: "swear", pos: "動", ja: "誓う", example: "swear to tell the truth（真実を誓う）", unit: 61 },
  { word: "sweat", pos: "名", ja: "汗", example: "wipe the sweat（汗をふく）", unit: 61 },
  { word: "sweep", pos: "動", ja: "掃く", example: "sweep the floor（床を掃く）", unit: 61 },
  { word: "sweet", pos: "形", ja: "甘い", example: "a sweet cake（甘いケーキ）", unit: 61 },
  { word: "swell", pos: "動", ja: "腫れる", example: "my leg swells（足が腫れる）", unit: 61 },
  { word: "swim", pos: "動", ja: "泳ぐ", example: "swim in the sea（海で泳ぐ）", unit: 61 },
  { word: "sympathetic", pos: "形", ja: "同情的な", example: "a sympathetic look（同情的な表情）", unit: 61 },
  { word: "sympathy", pos: "名", ja: "同情", example: "feel sympathy（同情を感じる）", unit: 62 },
  { word: "system", pos: "名", ja: "体系", example: "a new system（新しい体系）", unit: 62 },
  { word: "table", pos: "名", ja: "テーブル", example: "sit at the table（テーブルに座る）", unit: 62 },
  { word: "tail", pos: "名", ja: "尾", example: "a dog's tail（犬の尾）", unit: 62 },
  { word: "take", pos: "動", ja: "取る", example: "take a book（本を取る）", unit: 62 },
  { word: "tall", pos: "形", ja: "背が高い", example: "a tall boy（背が高い少年）", unit: 62 },
  { word: "tap", pos: "動", ja: "軽くたたく", example: "tap the door（ドアを軽くたたく）", unit: 62 },
  { word: "taste", pos: "名", ja: "味", example: "a sweet taste（甘い味）", unit: 62 },
  { word: "tax", pos: "名", ja: "税金", example: "pay tax（税金を払う）", unit: 62 },
  { word: "taxi", pos: "名", ja: "タクシー", example: "take a taxi（タクシーに乗る）", unit: 62 },
  { word: "tea", pos: "名", ja: "お茶", example: "drink tea（お茶を飲む）", unit: 62 },
  { word: "teach", pos: "動", ja: "教える", example: "teach math（数学を教える）", unit: 62 },
  { word: "tear", pos: "動", ja: "破る", example: "tear the paper（紙を破る）", unit: 62 },
  { word: "telephone", pos: "名", ja: "電話", example: "answer the telephone（電話に出る）", unit: 62 },
  { word: "tell", pos: "動", ja: "伝える", example: "tell the truth（真実を伝える）", unit: 62 },
  { word: "temperature", pos: "名", ja: "温度", example: "the room temperature（部屋の温度）", unit: 62 },
  { word: "tempt", pos: "動", ja: "誘惑する", example: "tempt him with money（お金で彼を誘惑する）", unit: 62 },
  { word: "tend", pos: "動", ja: "傾向がある", example: "tend to be shy（内気になりがちだ）", unit: 62 },
  { word: "tender", pos: "形", ja: "やわらかい", example: "tender meat（やわらかい肉）", unit: 62 },
  { word: "tent", pos: "名", ja: "テント", example: "set up a tent（テントを張る）", unit: 62 },
  { word: "term", pos: "名", ja: "用語", example: "a technical term（専門用語）", unit: 63 },
  { word: "terrible", pos: "形", ja: "ひどい", example: "a terrible accident（ひどい事故）", unit: 63 },
  { word: "test", pos: "名", ja: "試験", example: "pass the test（試験に合格する）", unit: 63 },
  { word: "thank", pos: "動", ja: "感謝する", example: "thank you for help（助けに感謝する）", unit: 63 },
  { word: "theatrical", pos: "形", ja: "演劇の", example: "a theatrical performance（演劇の公演）", unit: 63 },
  { word: "thick", pos: "形", ja: "厚い", example: "a thick book（厚い本）", unit: 63 },
  { word: "thief", pos: "名", ja: "泥棒", example: "catch a thief（泥棒を捕まえる）", unit: 63 },
  { word: "thin", pos: "形", ja: "薄い", example: "a thin slice（薄い一切れ）", unit: 63 },
  { word: "think", pos: "動", ja: "考える", example: "think about it（それについて考える）", unit: 63 },
  { word: "thorough", pos: "形", ja: "徹底的な", example: "a thorough check（徹底的な点検）", unit: 63 },
  { word: "thread", pos: "名", ja: "糸", example: "a needle and thread（針と糸）", unit: 63 },
  { word: "threat", pos: "名", ja: "脅威", example: "a serious threat（深刻な脅威）", unit: 63 },
  { word: "threaten", pos: "動", ja: "脅す", example: "threaten a person（人を脅す）", unit: 63 },
  { word: "throat", pos: "名", ja: "のど", example: "a sore throat（痛むのど）", unit: 63 },
  { word: "throw", pos: "動", ja: "投げる", example: "throw a ball（ボールを投げる）", unit: 63 },
  { word: "thumb", pos: "名", ja: "親指", example: "hurt my thumb（親指をけがする）", unit: 63 },
  { word: "thunder", pos: "名", ja: "雷", example: "hear thunder（雷が鳴るのを聞く）", unit: 63 },
  { word: "ticket", pos: "名", ja: "切符", example: "buy a ticket（切符を買う）", unit: 63 },
  { word: "tide", pos: "名", ja: "潮", example: "the rising tide（満ちる潮）", unit: 63 },
  { word: "tight", pos: "形", ja: "きつい", example: "tight shoes（きつい靴）", unit: 63 },
  { word: "tip", pos: "名", ja: "先端", example: "the tip of a pen（ペンの先端）", unit: 64 },
  { word: "tire", pos: "動", ja: "疲れさせる", example: "the work tires me（仕事が私を疲れさせる）", unit: 64 },
  { word: "title", pos: "名", ja: "題名", example: "the title of a book（本の題名）", unit: 64 },
  { word: "toe", pos: "名", ja: "足の指", example: "hurt my toe（足の指をけがする）", unit: 64 },
  { word: "ton", pos: "名", ja: "トン", example: "weigh a ton（1トンの重さがある）", unit: 64 },
  { word: "tongue", pos: "名", ja: "舌", example: "burn my tongue（舌をやけどする）", unit: 64 },
  { word: "tool", pos: "名", ja: "道具", example: "a useful tool（役立つ道具）", unit: 64 },
  { word: "tooth", pos: "名", ja: "歯", example: "brush my teeth（歯を磨く）", unit: 64 },
  { word: "touch", pos: "動", ja: "さわる", example: "touch the screen（画面にさわる）", unit: 64 },
  { word: "tough", pos: "形", ja: "頑丈な", example: "tough boots（頑丈なブーツ）", unit: 64 },
  { word: "tour", pos: "名", ja: "観光旅行", example: "a bus tour（バスの観光旅行）", unit: 64 },
  { word: "towel", pos: "名", ja: "タオル", example: "a clean towel（清潔なタオル）", unit: 64 },
  { word: "tower", pos: "名", ja: "塔", example: "a tall tower（高い塔）", unit: 64 },
  { word: "town", pos: "名", ja: "町", example: "a small town（小さな町）", unit: 64 },
  { word: "toy", pos: "名", ja: "おもちゃ", example: "a new toy（新しいおもちゃ）", unit: 64 },
  { word: "track", pos: "名", ja: "線路", example: "a railway track（鉄道の線路）", unit: 64 },
  { word: "trade", pos: "名", ja: "貿易", example: "foreign trade（外国との貿易）", unit: 64 },
  { word: "train", pos: "名", ja: "列車", example: "take a train（列車に乗る）", unit: 64 },
  { word: "translate", pos: "動", ja: "翻訳する", example: "translate a book（本を翻訳する）", unit: 64 },
  { word: "translation", pos: "名", ja: "翻訳", example: "a good translation（よい翻訳）", unit: 64 },
];
