// 語彙パック: TOEIC500 バンド 追加分F（頻出基礎語）。
// ejdict-hand(CC0) 取込→並列サブエージェントで語義是正・機能語除去したもの。
// 既存の全 eikaiwa 語と word・ja が重複しないよう調整済み（意味は全トラックで一意）。
import type { VocabEntry, VocabUnitMeta } from "./types";

export const TOEIC500_F_UNITS: VocabUnitMeta[] = [
  { unit: 40, title: "頻出基礎語（TOEIC500・その40）", lesson: "よく使う基礎語を英語→日本語の4択でおぼえよう。" },
  { unit: 41, title: "頻出基礎語（TOEIC500・その41）", lesson: "よく使う基礎語を英語→日本語の4択でおぼえよう。" },
  { unit: 42, title: "頻出基礎語（TOEIC500・その42）", lesson: "よく使う基礎語を英語→日本語の4択でおぼえよう。" },
  { unit: 43, title: "頻出基礎語（TOEIC500・その43）", lesson: "よく使う基礎語を英語→日本語の4択でおぼえよう。" },
  { unit: 44, title: "頻出基礎語（TOEIC500・その44）", lesson: "よく使う基礎語を英語→日本語の4択でおぼえよう。" },
  { unit: 45, title: "頻出基礎語（TOEIC500・その45）", lesson: "よく使う基礎語を英語→日本語の4択でおぼえよう。" },
  { unit: 46, title: "頻出基礎語（TOEIC500・その46）", lesson: "よく使う基礎語を英語→日本語の4択でおぼえよう。" },
  { unit: 47, title: "頻出基礎語（TOEIC500・その47）", lesson: "よく使う基礎語を英語→日本語の4択でおぼえよう。" },
  { unit: 48, title: "頻出基礎語（TOEIC500・その48）", lesson: "よく使う基礎語を英語→日本語の4択でおぼえよう。" },
  { unit: 49, title: "頻出基礎語（TOEIC500・その49）", lesson: "よく使う基礎語を英語→日本語の4択でおぼえよう。" },
  { unit: 50, title: "頻出基礎語（TOEIC500・その50）", lesson: "よく使う基礎語を英語→日本語の4択でおぼえよう。" },
  { unit: 51, title: "頻出基礎語（TOEIC500・その51）", lesson: "よく使う基礎語を英語→日本語の4択でおぼえよう。" },
  { unit: 52, title: "頻出基礎語（TOEIC500・その52）", lesson: "よく使う基礎語を英語→日本語の4択でおぼえよう。" },
];

export const TOEIC500_F_VOCAB: VocabEntry[] = [
  { word: "level", pos: "名", ja: "水準", example: "a high level（高い水準）", unit: 40 },
  { word: "lodge", pos: "名", ja: "山小屋", example: "a ski lodge（スキー用の山小屋）", unit: 40 },
  { word: "low", pos: "形", ja: "低い", example: "a low price（低い価格）", unit: 40 },
  { word: "mean", pos: "動", ja: "意味する", example: "What do you mean?（どういう意味ですか）", unit: 40 },
  { word: "operate", pos: "動", ja: "操作する", example: "operate a machine（機械を操作する）", unit: 40 },
  { word: "orange", pos: "名", ja: "オレンジ", example: "eat an orange（オレンジを食べる）", unit: 40 },
  { word: "ordinary", pos: "形", ja: "普通の", example: "an ordinary day（普通の一日）", unit: 40 },
  { word: "organ", pos: "名", ja: "臓器", example: "a vital organ（重要な臓器）", unit: 40 },
  { word: "origin", pos: "名", ja: "起源", example: "the origin of life（生命の起源）", unit: 40 },
  { word: "outline", pos: "名", ja: "概要", example: "an outline of the plan（計画の概要）", unit: 40 },
  { word: "overcome", pos: "動", ja: "克服する", example: "overcome difficulties（困難を克服する）", unit: 40 },
  { word: "owe", pos: "動", ja: "借りている", example: "owe money（お金を借りている）", unit: 40 },
  { word: "ownership", pos: "名", ja: "所有権", example: "transfer ownership（所有権を移す）", unit: 40 },
  { word: "pack", pos: "動", ja: "荷造りする", example: "pack a bag（かばんに荷造りする）", unit: 40 },
  { word: "page", pos: "名", ja: "ページ", example: "turn the page（ページをめくる）", unit: 40 },
  { word: "pain", pos: "名", ja: "痛み", example: "feel pain（痛みを感じる）", unit: 40 },
  { word: "paint", pos: "動", ja: "塗る", example: "paint the wall（壁を塗る）", unit: 40 },
  { word: "pair", pos: "名", ja: "一組", example: "a pair of shoes（一組の靴）", unit: 40 },
  { word: "pale", pos: "形", ja: "青白い", example: "a pale face（青白い顔）", unit: 40 },
  { word: "paper", pos: "名", ja: "紙", example: "a sheet of paper（一枚の紙）", unit: 40 },
  { word: "parent", pos: "名", ja: "親", example: "my parents（私の両親）", unit: 41 },
  { word: "park", pos: "名", ja: "公園", example: "walk in the park（公園を歩く）", unit: 41 },
  { word: "part", pos: "名", ja: "部分", example: "the best part（一番いい部分）", unit: 41 },
  { word: "particle", pos: "名", ja: "粒子", example: "a tiny particle（小さな粒子）", unit: 41 },
  { word: "particular", pos: "形", ja: "特定の", example: "a particular reason（特定の理由）", unit: 41 },
  { word: "partner", pos: "名", ja: "パートナー", example: "a business partner（ビジネスパートナー）", unit: 41 },
  { word: "party", pos: "名", ja: "パーティー", example: "a birthday party（誕生日パーティー）", unit: 41 },
  { word: "pass", pos: "動", ja: "通り過ぎる", example: "pass the shop（店を通り過ぎる）", unit: 41 },
  { word: "passage", pos: "名", ja: "通路", example: "a narrow passage（狭い通路）", unit: 41 },
  { word: "passenger", pos: "名", ja: "乗客", example: "a passenger on the bus（バスの乗客）", unit: 41 },
  { word: "past", pos: "名", ja: "過去", example: "in the past（過去に）", unit: 41 },
  { word: "path", pos: "名", ja: "小道", example: "a mountain path（山の小道）", unit: 41 },
  { word: "patience", pos: "名", ja: "忍耐", example: "have patience（忍耐を持つ）", unit: 41 },
  { word: "patient", pos: "形", ja: "忍耐強い", example: "be patient（忍耐強くある）", unit: 41 },
  { word: "pattern", pos: "名", ja: "模様", example: "a flower pattern（花の模様）", unit: 41 },
  { word: "pause", pos: "名", ja: "一時停止", example: "a short pause（短い間）", unit: 41 },
  { word: "pay", pos: "動", ja: "支払う", example: "pay the bill（勘定を支払う）", unit: 41 },
  { word: "peace", pos: "名", ja: "平和", example: "world peace（世界の平和）", unit: 41 },
  { word: "peculiar", pos: "形", ja: "奇妙な", example: "a peculiar smell（奇妙なにおい）", unit: 41 },
  { word: "pencil", pos: "名", ja: "鉛筆", example: "write with a pencil（鉛筆で書く）", unit: 41 },
  { word: "people", pos: "名", ja: "人々", example: "many people（多くの人々）", unit: 42 },
  { word: "perfect", pos: "形", ja: "完璧な", example: "a perfect score（完璧な点数）", unit: 42 },
  { word: "perform", pos: "動", ja: "行う", example: "perform a task（仕事を行う）", unit: 42 },
  { word: "performance", pos: "名", ja: "出来ばえ", example: "a good performance（良い出来）", unit: 42 },
  { word: "permanent", pos: "形", ja: "永久の", example: "a permanent job（永久の仕事）", unit: 42 },
  { word: "permission", pos: "名", ja: "許可", example: "ask permission（許可を求める）", unit: 42 },
  { word: "person", pos: "名", ja: "人", example: "a kind person（親切な人）", unit: 42 },
  { word: "persuade", pos: "動", ja: "説得する", example: "persuade a friend（友人を説得する）", unit: 42 },
  { word: "pet", pos: "名", ja: "ペット", example: "keep a pet（ペットを飼う）", unit: 42 },
  { word: "photograph", pos: "名", ja: "写真", example: "take a photograph（写真を撮る）", unit: 42 },
  { word: "picture", pos: "名", ja: "絵", example: "draw a picture（絵を描く）", unit: 42 },
  { word: "pile", pos: "名", ja: "積み重ね", example: "a pile of books（本の積み重ね）", unit: 42 },
  { word: "pin", pos: "名", ja: "ピン", example: "use a pin（ピンを使う）", unit: 42 },
  { word: "pink", pos: "名", ja: "桃色", example: "the color pink（桃色）", unit: 42 },
  { word: "pipe", pos: "名", ja: "管", example: "a water pipe（水道管）", unit: 42 },
  { word: "pity", pos: "名", ja: "あわれみ", example: "feel pity（あわれみを感じる）", unit: 42 },
  { word: "place", pos: "名", ja: "場所", example: "a quiet place（静かな場所）", unit: 42 },
  { word: "plain", pos: "形", ja: "質素な", example: "a plain room（質素な部屋）", unit: 42 },
  { word: "plan", pos: "名", ja: "計画", example: "make a plan（計画を立てる）", unit: 42 },
  { word: "plant", pos: "名", ja: "植物", example: "a green plant（緑の植物）", unit: 42 },
  { word: "plate", pos: "名", ja: "皿", example: "a plate of food（一皿の料理）", unit: 43 },
  { word: "play", pos: "動", ja: "遊ぶ", example: "play outside（外で遊ぶ）", unit: 43 },
  { word: "pleasant", pos: "形", ja: "心地よい", example: "a pleasant day（心地よい一日）", unit: 43 },
  { word: "please", pos: "動", ja: "喜ばせる", example: "please the crowd（観客を喜ばせる）", unit: 43 },
  { word: "plenty", pos: "名", ja: "たくさん", example: "plenty of time（たくさんの時間）", unit: 43 },
  { word: "pocket", pos: "名", ja: "ポケット", example: "in my pocket（ポケットの中に）", unit: 43 },
  { word: "poem", pos: "名", ja: "詩", example: "write a poem（詩を書く）", unit: 43 },
  { word: "poet", pos: "名", ja: "詩人", example: "a famous poet（有名な詩人）", unit: 43 },
  { word: "point", pos: "名", ja: "要点", example: "the main point（主な要点）", unit: 43 },
  { word: "poison", pos: "名", ja: "毒", example: "deadly poison（猛毒）", unit: 43 },
  { word: "police", pos: "名", ja: "警察", example: "call the police（警察を呼ぶ）", unit: 43 },
  { word: "polish", pos: "動", ja: "磨く", example: "polish shoes（靴を磨く）", unit: 43 },
  { word: "polite", pos: "形", ja: "礼儀正しい", example: "a polite boy（礼儀正しい少年）", unit: 43 },
  { word: "political", pos: "形", ja: "政治の", example: "a political party（政党）", unit: 43 },
  { word: "politician", pos: "名", ja: "政治家", example: "a young politician（若い政治家）", unit: 43 },
  { word: "politics", pos: "名", ja: "政治", example: "talk about politics（政治を語る）", unit: 43 },
  { word: "pool", pos: "名", ja: "プール", example: "swim in the pool（プールで泳ぐ）", unit: 43 },
  { word: "poor", pos: "形", ja: "貧しい", example: "a poor family（貧しい家族）", unit: 43 },
  { word: "population", pos: "名", ja: "人口", example: "a large population（多くの人口）", unit: 43 },
  { word: "position", pos: "名", ja: "位置", example: "a good position（よい位置）", unit: 43 },
  { word: "possess", pos: "動", ja: "所有する", example: "possess land（土地を所有する）", unit: 44 },
  { word: "possession", pos: "名", ja: "所有", example: "in his possession（彼の所有で）", unit: 44 },
  { word: "possible", pos: "形", ja: "可能な", example: "if possible（可能なら）", unit: 44 },
  { word: "postpone", pos: "動", ja: "延期する", example: "postpone the meeting（会議を延期する）", unit: 44 },
  { word: "pot", pos: "名", ja: "なべ", example: "a cooking pot（料理なべ）", unit: 44 },
  { word: "pound", pos: "名", ja: "ポンド", example: "ten pounds（10ポンド）", unit: 44 },
  { word: "pour", pos: "動", ja: "注ぐ", example: "pour water（水を注ぐ）", unit: 44 },
  { word: "poverty", pos: "名", ja: "貧困", example: "live in poverty（貧困で暮らす）", unit: 44 },
  { word: "powder", pos: "名", ja: "粉", example: "white powder（白い粉）", unit: 44 },
  { word: "practical", pos: "形", ja: "実用的な", example: "a practical idea（実用的な考え）", unit: 44 },
  { word: "practice", pos: "名", ja: "練習", example: "daily practice（毎日の練習）", unit: 44 },
  { word: "praise", pos: "動", ja: "ほめる", example: "praise a student（生徒をほめる）", unit: 44 },
  { word: "pray", pos: "動", ja: "祈る", example: "pray for peace（平和を祈る）", unit: 44 },
  { word: "preach", pos: "動", ja: "説教する", example: "preach in church（教会で説教する）", unit: 44 },
  { word: "precious", pos: "形", ja: "貴重な", example: "a precious gift（貴重な贈り物）", unit: 44 },
  { word: "prefer", pos: "動", ja: "好む", example: "prefer tea（お茶を好む）", unit: 44 },
  { word: "preference", pos: "名", ja: "好み", example: "my preference（私の好み）", unit: 44 },
  { word: "prejudice", pos: "名", ja: "偏見", example: "racial prejudice（人種偏見）", unit: 44 },
  { word: "preserve", pos: "動", ja: "保存する", example: "preserve food（食品を保存する）", unit: 44 },
  { word: "president", pos: "名", ja: "大統領", example: "the president（大統領）", unit: 44 },
  { word: "press", pos: "動", ja: "押す", example: "press the button（ボタンを押す）", unit: 45 },
  { word: "pressure", pos: "名", ja: "圧力", example: "under pressure（圧力を受けて）", unit: 45 },
  { word: "pretend", pos: "動", ja: "ふりをする", example: "pretend to sleep（寝たふりをする）", unit: 45 },
  { word: "pretty", pos: "形", ja: "かわいい", example: "a pretty flower（かわいい花）", unit: 45 },
  { word: "prevent", pos: "動", ja: "防ぐ", example: "prevent a fire（火事を防ぐ）", unit: 45 },
  { word: "prevention", pos: "名", ja: "予防", example: "disease prevention（病気の予防）", unit: 45 },
  { word: "pride", pos: "名", ja: "誇り", example: "take pride（誇りを持つ）", unit: 45 },
  { word: "priest", pos: "名", ja: "聖職者", example: "a village priest（村の聖職者）", unit: 45 },
  { word: "print", pos: "動", ja: "印刷する", example: "print a page（ページを印刷する）", unit: 45 },
  { word: "prison", pos: "名", ja: "刑務所", example: "go to prison（刑務所に入る）", unit: 45 },
  { word: "private", pos: "形", ja: "個人的な", example: "a private room（個室）", unit: 45 },
  { word: "prize", pos: "名", ja: "賞", example: "win a prize（賞を取る）", unit: 45 },
  { word: "produce", pos: "動", ja: "生産する", example: "produce cars（車を生産する）", unit: 45 },
  { word: "production", pos: "名", ja: "生産", example: "mass production（大量生産）", unit: 45 },
  { word: "profession", pos: "名", ja: "職業", example: "the medical profession（医療の職業）", unit: 45 },
  { word: "progress", pos: "名", ja: "進歩", example: "make progress（進歩する）", unit: 45 },
  { word: "promise", pos: "名", ja: "約束", example: "keep a promise（約束を守る）", unit: 45 },
  { word: "pronounce", pos: "動", ja: "発音する", example: "pronounce a word（単語を発音する）", unit: 45 },
  { word: "proof", pos: "名", ja: "証拠", example: "clear proof（明確な証拠）", unit: 45 },
  { word: "proper", pos: "形", ja: "適切な", example: "the proper way（適切な方法）", unit: 45 },
  { word: "proposal", pos: "名", ja: "提案", example: "a new proposal（新しい提案）", unit: 46 },
  { word: "protection", pos: "名", ja: "保護", example: "for protection（保護のために）", unit: 46 },
  { word: "proud", pos: "形", ja: "誇りに思う", example: "proud of you（あなたを誇りに思う）", unit: 46 },
  { word: "prove", pos: "動", ja: "証明する", example: "prove a fact（事実を証明する）", unit: 46 },
  { word: "public", pos: "形", ja: "公共の", example: "public places（公共の場）", unit: 46 },
  { word: "pull", pos: "動", ja: "引く", example: "pull the door（ドアを引く）", unit: 46 },
  { word: "pump", pos: "名", ja: "ポンプ", example: "a water pump（水ポンプ）", unit: 46 },
  { word: "punish", pos: "動", ja: "罰する", example: "punish a child（子どもを罰する）", unit: 46 },
  { word: "pupil", pos: "名", ja: "生徒", example: "a bright pupil（優秀な生徒）", unit: 46 },
  { word: "pure", pos: "形", ja: "純粋な", example: "pure water（純粋な水）", unit: 46 },
  { word: "purpose", pos: "名", ja: "目的", example: "the purpose of life（人生の目的）", unit: 46 },
  { word: "puzzle", pos: "動", ja: "悩ませる", example: "puzzle me（私を悩ませる）", unit: 46 },
  { word: "qualification", pos: "名", ja: "資格", example: "job qualifications（仕事の資格）", unit: 46 },
  { word: "qualify", pos: "動", ja: "資格を得る", example: "qualify as a nurse（看護師の資格を得る）", unit: 46 },
  { word: "quantity", pos: "名", ja: "量", example: "a large quantity（大量）", unit: 46 },
  { word: "quarrel", pos: "名", ja: "口げんか", example: "have a quarrel（口げんかをする）", unit: 46 },
  { word: "quarter", pos: "名", ja: "4分の1", example: "a quarter of the pizza（ピザの4分の1）", unit: 46 },
  { word: "queen", pos: "名", ja: "女王", example: "the queen of England（イギリスの女王）", unit: 46 },
  { word: "question", pos: "名", ja: "質問", example: "ask a question（質問をする）", unit: 46 },
  { word: "quiet", pos: "形", ja: "静かな", example: "a quiet room（静かな部屋）", unit: 46 },
  { word: "rabbit", pos: "名", ja: "ウサギ", example: "a white rabbit（白いウサギ）", unit: 47 },
  { word: "race", pos: "名", ja: "競走", example: "win the race（競走に勝つ）", unit: 47 },
  { word: "railroad", pos: "名", ja: "鉄道", example: "a railroad station（鉄道の駅）", unit: 47 },
  { word: "rain", pos: "名", ja: "雨", example: "heavy rain（激しい雨）", unit: 47 },
  { word: "raise", pos: "動", ja: "上げる", example: "raise your hand（手を上げる）", unit: 47 },
  { word: "rank", pos: "名", ja: "階級", example: "a high rank（高い階級）", unit: 47 },
  { word: "rare", pos: "形", ja: "まれな", example: "a rare chance（まれな機会）", unit: 47 },
  { word: "rate", pos: "名", ja: "割合", example: "a high rate（高い割合）", unit: 47 },
  { word: "raw", pos: "形", ja: "生の", example: "raw fish（生の魚）", unit: 47 },
  { word: "reach", pos: "動", ja: "着く", example: "reach the station（駅に着く）", unit: 47 },
  { word: "read", pos: "動", ja: "読む", example: "read a book（本を読む）", unit: 47 },
  { word: "ready", pos: "形", ja: "準備ができた", example: "be ready to go（行く準備ができた）", unit: 47 },
  { word: "real", pos: "形", ja: "本当の", example: "a real diamond（本物のダイヤ）", unit: 47 },
  { word: "reason", pos: "名", ja: "理由", example: "the reason for it（その理由）", unit: 47 },
  { word: "reasonable", pos: "形", ja: "妥当な", example: "a reasonable price（妥当な値段）", unit: 47 },
  { word: "recognition", pos: "名", ja: "認識", example: "face recognition（顔認識）", unit: 47 },
  { word: "recommend", pos: "動", ja: "推薦する", example: "recommend a book（本を推薦する）", unit: 47 },
  { word: "record", pos: "動", ja: "記録する", example: "record the data（データを記録する）", unit: 47 },
  { word: "reduction", pos: "名", ja: "削減", example: "a price reduction（値下げ）", unit: 47 },
  { word: "reference", pos: "名", ja: "参照", example: "a reference book（参考書）", unit: 47 },
  { word: "reflect", pos: "動", ja: "反射する", example: "reflect the light（光を反射する）", unit: 48 },
  { word: "reflection", pos: "名", ja: "反射", example: "the reflection in the mirror（鏡の反射）", unit: 48 },
  { word: "refresh", pos: "動", ja: "さっぱりさせる", example: "refresh myself（気分をさっぱりさせる）", unit: 48 },
  { word: "refuse", pos: "動", ja: "断る", example: "refuse the offer（申し出を断る）", unit: 48 },
  { word: "regard", pos: "動", ja: "見なす", example: "regard it as true（本当だと見なす）", unit: 48 },
  { word: "regret", pos: "動", ja: "後悔する", example: "regret the mistake（過ちを後悔する）", unit: 48 },
  { word: "relate", pos: "動", ja: "関連する", example: "relate to the topic（話題に関連する）", unit: 48 },
  { word: "relation", pos: "名", ja: "関係", example: "a close relation（密接な関係）", unit: 48 },
  { word: "relative", pos: "名", ja: "親戚", example: "a close relative（近い親戚）", unit: 48 },
  { word: "relief", pos: "名", ja: "安心", example: "a sigh of relief（安堵のため息）", unit: 48 },
  { word: "relieve", pos: "動", ja: "和らげる", example: "relieve the pain（痛みを和らげる）", unit: 48 },
  { word: "religion", pos: "名", ja: "宗教", example: "a world religion（世界の宗教）", unit: 48 },
  { word: "remain", pos: "動", ja: "残る", example: "remain at home（家に残る）", unit: 48 },
  { word: "remark", pos: "名", ja: "発言", example: "a rude remark（失礼な発言）", unit: 48 },
  { word: "remedy", pos: "名", ja: "治療薬", example: "a home remedy（家庭の治療薬）", unit: 48 },
  { word: "remember", pos: "動", ja: "思い出す", example: "remember her name（彼女の名前を思い出す）", unit: 48 },
  { word: "remind", pos: "動", ja: "思い出させる", example: "remind me later（後で思い出させて）", unit: 48 },
  { word: "rent", pos: "動", ja: "賃借りする", example: "rent an apartment（アパートを借りる）", unit: 48 },
  { word: "repeat", pos: "動", ja: "繰り返す", example: "repeat the word（その語を繰り返す）", unit: 48 },
  { word: "repetition", pos: "名", ja: "繰り返し", example: "avoid repetition（繰り返しを避ける）", unit: 48 },
  { word: "replace", pos: "動", ja: "取り替える", example: "replace the battery（電池を取り替える）", unit: 49 },
  { word: "reply", pos: "動", ja: "返事する", example: "reply to the email（メールに返事する）", unit: 49 },
  { word: "report", pos: "名", ja: "報告", example: "a weather report（天気予報）", unit: 49 },
  { word: "represent", pos: "動", ja: "代表する", example: "represent the team（チームを代表する）", unit: 49 },
  { word: "representative", pos: "名", ja: "代表者", example: "a sales representative（営業担当者）", unit: 49 },
  { word: "reproduce", pos: "動", ja: "再現する", example: "reproduce the sound（音を再現する）", unit: 49 },
  { word: "republic", pos: "名", ja: "共和国", example: "the French Republic（フランス共和国）", unit: 49 },
  { word: "reputation", pos: "名", ja: "評判", example: "a good reputation（良い評判）", unit: 49 },
  { word: "request", pos: "動", ja: "頼む", example: "request help（助けを頼む）", unit: 49 },
  { word: "rescue", pos: "動", ja: "救う", example: "rescue the child（子どもを救う）", unit: 49 },
  { word: "reserve", pos: "動", ja: "予約する", example: "reserve a table（席を予約する）", unit: 49 },
  { word: "resign", pos: "動", ja: "辞任する", example: "resign from the job（仕事を辞める）", unit: 49 },
  { word: "resist", pos: "動", ja: "抵抗する", example: "resist the enemy（敵に抵抗する）", unit: 49 },
  { word: "resistance", pos: "名", ja: "抵抗", example: "strong resistance（強い抵抗）", unit: 49 },
  { word: "respect", pos: "動", ja: "尊敬する", example: "respect my teacher（先生を尊敬する）", unit: 49 },
  { word: "responsible", pos: "形", ja: "責任がある", example: "responsible for it（それに責任がある）", unit: 49 },
  { word: "rest", pos: "名", ja: "休息", example: "take a rest（休息をとる）", unit: 49 },
  { word: "restaurant", pos: "名", ja: "レストラン", example: "a nice restaurant（すてきなレストラン）", unit: 49 },
  { word: "result", pos: "名", ja: "結果", example: "the test result（テストの結果）", unit: 49 },
  { word: "retire", pos: "動", ja: "引退する", example: "retire from work（仕事を引退する）", unit: 49 },
  { word: "review", pos: "動", ja: "復習する", example: "review the lesson（授業を復習する）", unit: 50 },
  { word: "reward", pos: "名", ja: "報酬", example: "a big reward（大きな報酬）", unit: 50 },
  { word: "ribbon", pos: "名", ja: "リボン", example: "a red ribbon（赤いリボン）", unit: 50 },
  { word: "rice", pos: "名", ja: "米", example: "cook rice（米を炊く）", unit: 50 },
  { word: "rich", pos: "形", ja: "金持ちの", example: "a rich man（金持ちの男）", unit: 50 },
  { word: "ride", pos: "動", ja: "乗る", example: "ride a bike（自転車に乗る）", unit: 50 },
  { word: "ring", pos: "名", ja: "指輪", example: "a gold ring（金の指輪）", unit: 50 },
  { word: "rise", pos: "動", ja: "上がる", example: "the sun rises（太陽が上がる）", unit: 50 },
  { word: "rival", pos: "名", ja: "競争相手", example: "a strong rival（強い競争相手）", unit: 50 },
  { word: "river", pos: "名", ja: "川", example: "a long river（長い川）", unit: 50 },
  { word: "road", pos: "名", ja: "道路", example: "a wide road（広い道路）", unit: 50 },
  { word: "roar", pos: "動", ja: "ほえる", example: "lions roar（ライオンがほえる）", unit: 50 },
  { word: "rob", pos: "動", ja: "奪う", example: "rob a bank（銀行を襲う）", unit: 50 },
  { word: "rock", pos: "名", ja: "岩", example: "a big rock（大きな岩）", unit: 50 },
  { word: "roll", pos: "動", ja: "転がる", example: "the ball rolls（ボールが転がる）", unit: 50 },
  { word: "roof", pos: "名", ja: "屋根", example: "a red roof（赤い屋根）", unit: 50 },
  { word: "room", pos: "名", ja: "部屋", example: "a clean room（きれいな部屋）", unit: 50 },
  { word: "root", pos: "名", ja: "根", example: "tree roots（木の根）", unit: 50 },
  { word: "rope", pos: "名", ja: "なわ", example: "a strong rope（丈夫ななわ）", unit: 50 },
  { word: "rough", pos: "形", ja: "粗い", example: "a rough surface（粗い表面）", unit: 50 },
  { word: "row", pos: "名", ja: "列", example: "the front row（前の列）", unit: 51 },
  { word: "royal", pos: "形", ja: "王の", example: "the royal family（王の一家）", unit: 51 },
  { word: "rub", pos: "動", ja: "こする", example: "rub your eyes（目をこする）", unit: 51 },
  { word: "rubber", pos: "名", ja: "ゴム", example: "a rubber ball（ゴムのボール）", unit: 51 },
  { word: "rug", pos: "名", ja: "敷き物", example: "a soft rug（柔らかい敷き物）", unit: 51 },
  { word: "ruin", pos: "動", ja: "台無しにする", example: "ruin the plan（計画を台無しにする）", unit: 51 },
  { word: "rule", pos: "名", ja: "規則", example: "follow the rule（規則を守る）", unit: 51 },
  { word: "run", pos: "動", ja: "走る", example: "run fast（速く走る）", unit: 51 },
  { word: "rust", pos: "名", ja: "さび", example: "cover with rust（さびで覆われる）", unit: 51 },
  { word: "sacrifice", pos: "動", ja: "犠牲にする", example: "sacrifice time（時間を犠牲にする）", unit: 51 },
  { word: "sad", pos: "形", ja: "悲しい", example: "a sad story（悲しい話）", unit: 51 },
  { word: "saddle", pos: "名", ja: "くら", example: "a horse saddle（馬のくら）", unit: 51 },
  { word: "safe", pos: "形", ja: "安全な", example: "a safe place（安全な場所）", unit: 51 },
  { word: "safety", pos: "名", ja: "安全", example: "for your safety（あなたの安全のため）", unit: 51 },
  { word: "sail", pos: "名", ja: "帆", example: "a white sail（白い帆）", unit: 51 },
  { word: "sale", pos: "名", ja: "販売", example: "on sale（販売中）", unit: 51 },
  { word: "same", pos: "形", ja: "同じ", example: "the same day（同じ日）", unit: 51 },
  { word: "sample", pos: "名", ja: "見本", example: "a free sample（無料の見本）", unit: 51 },
  { word: "sand", pos: "名", ja: "砂", example: "white sand（白い砂）", unit: 51 },
  { word: "satisfaction", pos: "名", ja: "満足", example: "full satisfaction（十分な満足）", unit: 51 },
  { word: "satisfactory", pos: "形", ja: "満足な", example: "a satisfactory result（満足な結果）", unit: 52 },
  { word: "satisfy", pos: "動", ja: "満足させる", example: "satisfy customers（客を満足させる）", unit: 52 },
  { word: "sauce", pos: "名", ja: "ソース", example: "tomato sauce（トマトソース）", unit: 52 },
  { word: "say", pos: "動", ja: "言う", example: "say hello（こんにちはと言う）", unit: 52 },
  { word: "scale", pos: "名", ja: "規模", example: "a large scale（大きな規模）", unit: 52 },
  { word: "scarce", pos: "形", ja: "乏しい", example: "scarce water（乏しい水）", unit: 52 },
  { word: "scatter", pos: "動", ja: "ばらまく", example: "scatter seeds（種をばらまく）", unit: 52 },
  { word: "scene", pos: "名", ja: "場面", example: "a sad scene（悲しい場面）", unit: 52 },
  { word: "scenery", pos: "名", ja: "風景", example: "beautiful scenery（美しい風景）", unit: 52 },
  { word: "school", pos: "名", ja: "学校", example: "go to school（学校へ行く）", unit: 52 },
  { word: "science", pos: "名", ja: "科学", example: "study science（科学を学ぶ）", unit: 52 },
  { word: "scientific", pos: "形", ja: "科学の", example: "scientific research（科学の研究）", unit: 52 },
  { word: "scientist", pos: "名", ja: "科学者", example: "a famous scientist（有名な科学者）", unit: 52 },
  { word: "scrape", pos: "動", ja: "こすり落とす", example: "scrape the paint（塗料をこすり落とす）", unit: 52 },
  { word: "scratch", pos: "動", ja: "ひっかく", example: "scratch your arm（腕をひっかく）", unit: 52 },
  { word: "screen", pos: "名", ja: "画面", example: "a big screen（大きな画面）", unit: 52 },
  { word: "screw", pos: "名", ja: "ねじ", example: "tighten a screw（ねじを締める）", unit: 52 },
  { word: "search", pos: "動", ja: "探す", example: "search for keys（鍵を探す）", unit: 52 },
  { word: "season", pos: "名", ja: "季節", example: "my favorite season（好きな季節）", unit: 52 },
];
