// 語彙パック: TOEIC500 バンド 追加分E（頻出基礎語・第3バッチ）。
// ejdict-hand(CC0) 取込→並列サブエージェントで語義是正・機能語除去したもの。
// 既存の全 eikaiwa 語と word・ja が重複しないよう調整済み（意味は全トラックで一意）。
import type { VocabEntry, VocabUnitMeta } from "./types";

export const TOEIC500_E_UNITS: VocabUnitMeta[] = [
  { unit: 28, title: "頻出基礎語（TOEIC500・その28）", lesson: "よく使う基礎語を英語→日本語の4択でおぼえよう。" },
  { unit: 29, title: "頻出基礎語（TOEIC500・その29）", lesson: "よく使う基礎語を英語→日本語の4択でおぼえよう。" },
  { unit: 30, title: "頻出基礎語（TOEIC500・その30）", lesson: "よく使う基礎語を英語→日本語の4択でおぼえよう。" },
  { unit: 31, title: "頻出基礎語（TOEIC500・その31）", lesson: "よく使う基礎語を英語→日本語の4択でおぼえよう。" },
  { unit: 32, title: "頻出基礎語（TOEIC500・その32）", lesson: "よく使う基礎語を英語→日本語の4択でおぼえよう。" },
  { unit: 33, title: "頻出基礎語（TOEIC500・その33）", lesson: "よく使う基礎語を英語→日本語の4択でおぼえよう。" },
  { unit: 34, title: "頻出基礎語（TOEIC500・その34）", lesson: "よく使う基礎語を英語→日本語の4択でおぼえよう。" },
  { unit: 35, title: "頻出基礎語（TOEIC500・その35）", lesson: "よく使う基礎語を英語→日本語の4択でおぼえよう。" },
  { unit: 36, title: "頻出基礎語（TOEIC500・その36）", lesson: "よく使う基礎語を英語→日本語の4択でおぼえよう。" },
  { unit: 37, title: "頻出基礎語（TOEIC500・その37）", lesson: "よく使う基礎語を英語→日本語の4択でおぼえよう。" },
  { unit: 38, title: "頻出基礎語（TOEIC500・その38）", lesson: "よく使う基礎語を英語→日本語の4択でおぼえよう。" },
  { unit: 39, title: "頻出基礎語（TOEIC500・その39）", lesson: "よく使う基礎語を英語→日本語の4択でおぼえよう。" },
];

export const TOEIC500_E_VOCAB: VocabEntry[] = [
  { word: "english", pos: "名", ja: "英語", example: "speak English（英語を話す）", unit: 28 },
  { word: "flat", pos: "形", ja: "平らな", example: "a flat road（平らな道）", unit: 28 },
  { word: "forgive", pos: "動", ja: "許す", example: "forgive a friend（友達を許す）", unit: 28 },
  { word: "holy", pos: "形", ja: "神聖な", example: "a holy place（神聖な場所）", unit: 28 },
  { word: "home", pos: "名", ja: "家", example: "go home（家に帰る）", unit: 28 },
  { word: "honest", pos: "形", ja: "正直な", example: "an honest person（正直な人）", unit: 28 },
  { word: "hope", pos: "動", ja: "望む", example: "hope for peace（平和を望む）", unit: 28 },
  { word: "horizon", pos: "名", ja: "地平線", example: "see the horizon（地平線を見る）", unit: 28 },
  { word: "horse", pos: "名", ja: "馬", example: "ride a horse（馬に乗る）", unit: 28 },
  { word: "hospital", pos: "名", ja: "病院", example: "go to the hospital（病院に行く）", unit: 28 },
  { word: "hot", pos: "形", ja: "熱い", example: "hot soup（熱いスープ）", unit: 28 },
  { word: "hotel", pos: "名", ja: "ホテル", example: "stay at a hotel（ホテルに泊まる）", unit: 28 },
  { word: "hour", pos: "名", ja: "時間", example: "one hour（1時間）", unit: 28 },
  { word: "human", pos: "名", ja: "人間", example: "a human being（人間）", unit: 28 },
  { word: "humble", pos: "形", ja: "謙虚な", example: "a humble person（謙虚な人）", unit: 28 },
  { word: "hunger", pos: "名", ja: "飢え", example: "die of hunger（飢えで死ぬ）", unit: 28 },
  { word: "hunt", pos: "動", ja: "狩る", example: "hunt animals（動物を狩る）", unit: 28 },
  { word: "hurry", pos: "動", ja: "急ぐ", example: "hurry home（急いで帰る）", unit: 28 },
  { word: "hurt", pos: "動", ja: "傷つける", example: "hurt my leg（足を傷つける）", unit: 28 },
  { word: "husband", pos: "名", ja: "夫", example: "her husband（彼女の夫）", unit: 28 },
  { word: "hut", pos: "名", ja: "小屋", example: "a small hut（小さな小屋）", unit: 29 },
  { word: "ice", pos: "名", ja: "氷", example: "melt the ice（氷を溶かす）", unit: 29 },
  { word: "idea", pos: "名", ja: "考え", example: "a good idea（良い考え）", unit: 29 },
  { word: "ideal", pos: "形", ja: "理想的な", example: "an ideal place（理想的な場所）", unit: 29 },
  { word: "idle", pos: "形", ja: "怠けた", example: "an idle student（怠けた学生）", unit: 29 },
  { word: "ill", pos: "形", ja: "病気の", example: "feel ill（病気に感じる）", unit: 29 },
  { word: "imaginary", pos: "形", ja: "架空の", example: "an imaginary friend（架空の友達）", unit: 29 },
  { word: "imagine", pos: "動", ja: "想像する", example: "imagine the future（未来を想像する）", unit: 29 },
  { word: "imitation", pos: "名", ja: "模倣", example: "a cheap imitation（安っぽい模倣）", unit: 29 },
  { word: "immediate", pos: "形", ja: "即座の", example: "an immediate answer（即座の返事）", unit: 29 },
  { word: "immense", pos: "形", ja: "巨大な", example: "an immense building（巨大な建物）", unit: 29 },
  { word: "importance", pos: "名", ja: "重要性", example: "the importance of study（勉強の重要性）", unit: 29 },
  { word: "impossible", pos: "形", ja: "不可能な", example: "an impossible task（不可能な仕事）", unit: 29 },
  { word: "inch", pos: "名", ja: "インチ", example: "two inches long（2インチの長さ）", unit: 29 },
  { word: "indeed", pos: "副", ja: "実に", example: "very good indeed（実にすばらしい）", unit: 29 },
  { word: "industry", pos: "名", ja: "産業", example: "the car industry（自動車産業）", unit: 29 },
  { word: "influence", pos: "名", ja: "影響", example: "a bad influence（悪い影響）", unit: 29 },
  { word: "inform", pos: "動", ja: "知らせる", example: "inform the class（クラスに知らせる）", unit: 29 },
  { word: "inquiry", pos: "名", ja: "問い合わせ", example: "make an inquiry（問い合わせをする）", unit: 29 },
  { word: "insect", pos: "名", ja: "昆虫", example: "catch an insect（昆虫を捕まえる）", unit: 29 },
  { word: "inside", pos: "名", ja: "内部", example: "the inside of the box（箱の内部）", unit: 30 },
  { word: "instead", pos: "副", ja: "その代わりに", example: "go instead（代わりに行く）", unit: 30 },
  { word: "instrument", pos: "名", ja: "器具", example: "a medical instrument（医療器具）", unit: 30 },
  { word: "insult", pos: "動", ja: "侮辱する", example: "insult a person（人を侮辱する）", unit: 30 },
  { word: "insurance", pos: "名", ja: "保険", example: "car insurance（自動車保険）", unit: 30 },
  { word: "insure", pos: "動", ja: "保険をかける", example: "insure a house（家に保険をかける）", unit: 30 },
  { word: "intend", pos: "動", ja: "意図する", example: "intend to go（行くつもりだ）", unit: 30 },
  { word: "intention", pos: "名", ja: "意図", example: "a good intention（良い意図）", unit: 30 },
  { word: "interest", pos: "名", ja: "興味", example: "show interest（興味を示す）", unit: 30 },
  { word: "interfere", pos: "動", ja: "干渉する", example: "interfere in plans（計画に干渉する）", unit: 30 },
  { word: "interrupt", pos: "動", ja: "さえぎる", example: "interrupt a talk（話をさえぎる）", unit: 30 },
  { word: "international", pos: "形", ja: "国際的な", example: "an international event（国際的な行事）", unit: 30 },
  { word: "introduce", pos: "動", ja: "紹介する", example: "introduce a friend（友達を紹介する）", unit: 30 },
  { word: "introduction", pos: "名", ja: "紹介", example: "a short introduction（短い紹介）", unit: 30 },
  { word: "invent", pos: "動", ja: "発明する", example: "invent a machine（機械を発明する）", unit: 30 },
  { word: "invention", pos: "名", ja: "発明", example: "a great invention（偉大な発明）", unit: 30 },
  { word: "invite", pos: "動", ja: "招待する", example: "invite friends（友達を招待する）", unit: 30 },
  { word: "iron", pos: "名", ja: "鉄", example: "made of iron（鉄でできた）", unit: 30 },
  { word: "island", pos: "名", ja: "島", example: "a small island（小さな島）", unit: 30 },
  { word: "jaw", pos: "名", ja: "あご", example: "a strong jaw（丈夫なあご）", unit: 30 },
  { word: "join", pos: "動", ja: "参加する", example: "join a club（クラブに参加する）", unit: 31 },
  { word: "joint", pos: "名", ja: "関節", example: "a knee joint（膝の関節）", unit: 31 },
  { word: "joke", pos: "名", ja: "冗談", example: "tell a joke（冗談を言う）", unit: 31 },
  { word: "journey", pos: "名", ja: "旅行", example: "a long journey（長い旅行）", unit: 31 },
  { word: "joy", pos: "名", ja: "喜び", example: "full of joy（喜びに満ちた）", unit: 31 },
  { word: "judge", pos: "名", ja: "裁判官", example: "a fair judge（公平な裁判官）", unit: 31 },
  { word: "juice", pos: "名", ja: "ジュース", example: "orange juice（オレンジジュース）", unit: 31 },
  { word: "jump", pos: "動", ja: "跳ぶ", example: "jump high（高く跳ぶ）", unit: 31 },
  { word: "justice", pos: "名", ja: "正義", example: "social justice（社会正義）", unit: 31 },
  { word: "keep", pos: "動", ja: "保つ", example: "keep a secret（秘密を守る）", unit: 31 },
  { word: "key", pos: "名", ja: "かぎ", example: "a house key（家のかぎ）", unit: 31 },
  { word: "kick", pos: "動", ja: "ける", example: "kick a ball（ボールをける）", unit: 31 },
  { word: "kill", pos: "動", ja: "殺す", example: "kill an insect（虫を殺す）", unit: 31 },
  { word: "kind", pos: "形", ja: "親切な", example: "a kind teacher（親切な先生）", unit: 31 },
  { word: "king", pos: "名", ja: "王", example: "a great king（偉大な王）", unit: 31 },
  { word: "kingdom", pos: "名", ja: "王国", example: "a small kingdom（小さな王国）", unit: 31 },
  { word: "kiss", pos: "動", ja: "キスする", example: "kiss the baby（赤ちゃんにキスする）", unit: 31 },
  { word: "kitchen", pos: "名", ja: "台所", example: "clean the kitchen（台所を掃除する）", unit: 31 },
  { word: "knee", pos: "名", ja: "ひざ", example: "hurt my knee（ひざをけがする）", unit: 31 },
  { word: "kneel", pos: "動", ja: "ひざまずく", example: "kneel down（ひざまずく）", unit: 31 },
  { word: "knife", pos: "名", ja: "ナイフ", example: "a sharp knife（鋭いナイフ）", unit: 32 },
  { word: "knock", pos: "動", ja: "ノックする", example: "knock on the door（ドアをノックする）", unit: 32 },
  { word: "know", pos: "動", ja: "知る", example: "know the answer（答えを知る）", unit: 32 },
  { word: "knowledge", pos: "名", ja: "知識", example: "deep knowledge（深い知識）", unit: 32 },
  { word: "lack", pos: "動", ja: "欠く", example: "lack money（お金が足りない）", unit: 32 },
  { word: "ladder", pos: "名", ja: "はしご", example: "climb a ladder（はしごを登る）", unit: 32 },
  { word: "lady", pos: "名", ja: "女性", example: "a kind lady（親切な女性）", unit: 32 },
  { word: "lake", pos: "名", ja: "湖", example: "swim in the lake（湖で泳ぐ）", unit: 32 },
  { word: "lamp", pos: "名", ja: "ランプ", example: "turn on the lamp（ランプをつける）", unit: 32 },
  { word: "land", pos: "名", ja: "土地", example: "buy land（土地を買う）", unit: 32 },
  { word: "language", pos: "名", ja: "言語", example: "a foreign language（外国語）", unit: 32 },
  { word: "late", pos: "形", ja: "遅れた", example: "be late for school（学校に遅れる）", unit: 32 },
  { word: "laugh", pos: "動", ja: "笑う", example: "laugh loudly（大声で笑う）", unit: 32 },
  { word: "laughter", pos: "名", ja: "笑い", example: "loud laughter（大きな笑い声）", unit: 32 },
  { word: "law", pos: "名", ja: "法律", example: "obey the law（法律を守る）", unit: 32 },
  { word: "lawyer", pos: "名", ja: "弁護士", example: "a good lawyer（優秀な弁護士）", unit: 32 },
  { word: "lead", pos: "動", ja: "導く", example: "lead a team（チームを率いる）", unit: 32 },
  { word: "leadership", pos: "名", ja: "指導力", example: "strong leadership（強い指導力）", unit: 32 },
  { word: "leaf", pos: "名", ja: "葉", example: "a green leaf（緑の葉）", unit: 32 },
  { word: "learn", pos: "動", ja: "学ぶ", example: "learn English（英語を学ぶ）", unit: 32 },
  { word: "leather", pos: "名", ja: "革", example: "a leather bag（革のかばん）", unit: 33 },
  { word: "leave", pos: "動", ja: "去る", example: "leave home（家を出る）", unit: 33 },
  { word: "leg", pos: "名", ja: "脚", example: "a long leg（長い脚）", unit: 33 },
  { word: "lend", pos: "動", ja: "貸す", example: "lend a pen（ペンを貸す）", unit: 33 },
  { word: "length", pos: "名", ja: "長さ", example: "the length of the road（道の長さ）", unit: 33 },
  { word: "letter", pos: "名", ja: "手紙", example: "write a letter（手紙を書く）", unit: 33 },
  { word: "library", pos: "名", ja: "図書館", example: "go to the library（図書館へ行く）", unit: 33 },
  { word: "lid", pos: "名", ja: "ふた", example: "open the lid（ふたを開ける）", unit: 33 },
  { word: "lie", pos: "動", ja: "うそをつく", example: "tell a lie（うそをつく）", unit: 33 },
  { word: "life", pos: "名", ja: "生命", example: "save a life（命を救う）", unit: 33 },
  { word: "lift", pos: "動", ja: "持ち上げる", example: "lift a box（箱を持ち上げる）", unit: 33 },
  { word: "light", pos: "名", ja: "光", example: "bright light（明るい光）", unit: 33 },
  { word: "likely", pos: "形", ja: "ありそうな", example: "a likely result（ありそうな結果）", unit: 33 },
  { word: "limit", pos: "名", ja: "限界", example: "a time limit（制限時間）", unit: 33 },
  { word: "line", pos: "名", ja: "線", example: "draw a line（線を引く）", unit: 33 },
  { word: "lip", pos: "名", ja: "くちびる", example: "red lips（赤いくちびる）", unit: 33 },
  { word: "liquid", pos: "名", ja: "液体", example: "a clear liquid（透明な液体）", unit: 33 },
  { word: "list", pos: "名", ja: "一覧表", example: "a shopping list（買い物リスト）", unit: 33 },
  { word: "listen", pos: "動", ja: "聞く", example: "listen to music（音楽を聞く）", unit: 33 },
  { word: "literary", pos: "形", ja: "文学の", example: "a literary work（文学作品）", unit: 33 },
  { word: "literature", pos: "名", ja: "文学", example: "English literature（英文学）", unit: 34 },
  { word: "live", pos: "動", ja: "住む", example: "live in Tokyo（東京に住む）", unit: 34 },
  { word: "load", pos: "名", ja: "荷物", example: "a heavy load（重い荷物）", unit: 34 },
  { word: "loan", pos: "名", ja: "貸付金", example: "pay back a loan（ローンを返す）", unit: 34 },
  { word: "local", pos: "形", ja: "地元の", example: "a local shop（地元の店）", unit: 34 },
  { word: "lock", pos: "動", ja: "鍵をかける", example: "lock the door（ドアに鍵をかける）", unit: 34 },
  { word: "log", pos: "名", ja: "丸太", example: "a big log（大きな丸太）", unit: 34 },
  { word: "lonely", pos: "形", ja: "さびしい", example: "feel lonely（さびしく感じる）", unit: 34 },
  { word: "long", pos: "形", ja: "長い", example: "a long river（長い川）", unit: 34 },
  { word: "look", pos: "動", ja: "見る", example: "look at the sky（空を見る）", unit: 34 },
  { word: "loose", pos: "形", ja: "ゆるい", example: "a loose belt（ゆるいベルト）", unit: 34 },
  { word: "lord", pos: "名", ja: "主人", example: "serve the lord（主人に仕える）", unit: 34 },
  { word: "lose", pos: "動", ja: "失う", example: "lose a key（鍵をなくす）", unit: 34 },
  { word: "loss", pos: "名", ja: "損失", example: "a big loss（大きな損失）", unit: 34 },
  { word: "love", pos: "名", ja: "愛", example: "love for family（家族への愛）", unit: 34 },
  { word: "lovely", pos: "形", ja: "すてきな", example: "a lovely day（すてきな日）", unit: 34 },
  { word: "loyal", pos: "形", ja: "忠実な", example: "a loyal friend（忠実な友）", unit: 34 },
  { word: "loyalty", pos: "名", ja: "忠誠", example: "show loyalty（忠誠を示す）", unit: 34 },
  { word: "luck", pos: "名", ja: "運", example: "good luck（幸運）", unit: 34 },
  { word: "lump", pos: "名", ja: "塊", example: "a lump of sugar（角砂糖）", unit: 34 },
  { word: "lunch", pos: "名", ja: "昼食", example: "eat lunch（昼食を食べる）", unit: 35 },
  { word: "lung", pos: "名", ja: "肺", example: "healthy lungs（健康な肺）", unit: 35 },
  { word: "machine", pos: "名", ja: "機械", example: "a washing machine（洗濯機）", unit: 35 },
  { word: "main", pos: "形", ja: "主な", example: "the main road（主要道路）", unit: 35 },
  { word: "make", pos: "動", ja: "作る", example: "make a cake（ケーキを作る）", unit: 35 },
  { word: "male", pos: "形", ja: "男性の", example: "a male voice（男性の声）", unit: 35 },
  { word: "manage", pos: "動", ja: "管理する", example: "manage a team（チームを管理する）", unit: 35 },
  { word: "mankind", pos: "名", ja: "人類", example: "all mankind（全人類）", unit: 35 },
  { word: "manner", pos: "名", ja: "やり方", example: "in this manner（このやり方で）", unit: 35 },
  { word: "manufacture", pos: "動", ja: "製造する", example: "manufacture cars（車を製造する）", unit: 35 },
  { word: "map", pos: "名", ja: "地図", example: "read a map（地図を読む）", unit: 35 },
  { word: "market", pos: "名", ja: "市場", example: "a fish market（魚市場）", unit: 35 },
  { word: "marriage", pos: "名", ja: "結婚", example: "a happy marriage（幸せな結婚）", unit: 35 },
  { word: "marry", pos: "動", ja: "結婚する", example: "marry her（彼女と結婚する）", unit: 35 },
  { word: "material", pos: "名", ja: "材料", example: "raw material（原材料）", unit: 35 },
  { word: "matter", pos: "名", ja: "問題", example: "an important matter（重要な問題）", unit: 35 },
  { word: "maybe", pos: "副", ja: "たぶん", example: "maybe tomorrow（たぶん明日）", unit: 35 },
  { word: "meal", pos: "名", ja: "食事", example: "a big meal（豪華な食事）", unit: 35 },
  { word: "measure", pos: "動", ja: "測る", example: "measure the length（長さを測る）", unit: 35 },
  { word: "meat", pos: "名", ja: "肉", example: "cook meat（肉を料理する）", unit: 35 },
  { word: "mechanic", pos: "名", ja: "整備士", example: "a car mechanic（車の整備士）", unit: 36 },
  { word: "medical", pos: "形", ja: "医療の", example: "medical care（医療）", unit: 36 },
  { word: "medicine", pos: "名", ja: "薬", example: "take medicine（薬を飲む）", unit: 36 },
  { word: "meet", pos: "動", ja: "会う", example: "meet a friend（友達に会う）", unit: 36 },
  { word: "melt", pos: "動", ja: "溶ける", example: "snow melts（雪が溶ける）", unit: 36 },
  { word: "member", pos: "名", ja: "一員", example: "a team member（チームの一員）", unit: 36 },
  { word: "membership", pos: "名", ja: "会員資格", example: "a membership card（会員証）", unit: 36 },
  { word: "memory", pos: "名", ja: "記憶", example: "a good memory（良い記憶力）", unit: 36 },
  { word: "mention", pos: "動", ja: "言及する", example: "mention the plan（計画に触れる）", unit: 36 },
  { word: "merchant", pos: "名", ja: "商人", example: "a rich merchant（裕福な商人）", unit: 36 },
  { word: "mercy", pos: "名", ja: "慈悲", example: "show mercy（慈悲を示す）", unit: 36 },
  { word: "mere", pos: "形", ja: "ほんの", example: "a mere child（ほんの子供）", unit: 36 },
  { word: "message", pos: "名", ja: "伝言", example: "leave a message（伝言を残す）", unit: 36 },
  { word: "metal", pos: "名", ja: "金属", example: "made of metal（金属製の）", unit: 36 },
  { word: "middle", pos: "名", ja: "真ん中", example: "in the middle（真ん中に）", unit: 36 },
  { word: "mile", pos: "名", ja: "マイル", example: "ten miles away（10マイル先）", unit: 36 },
  { word: "milk", pos: "名", ja: "牛乳", example: "drink milk（牛乳を飲む）", unit: 36 },
  { word: "mill", pos: "名", ja: "製粉所", example: "a flour mill（製粉所）", unit: 36 },
  { word: "mind", pos: "名", ja: "心", example: "change one's mind（心変わりする）", unit: 36 },
  { word: "mineral", pos: "名", ja: "鉱物", example: "mineral water（ミネラルウォーター）", unit: 36 },
  { word: "minister", pos: "名", ja: "大臣", example: "a prime minister（総理大臣）", unit: 37 },
  { word: "minute", pos: "名", ja: "分", example: "wait a minute（少し待つ）", unit: 37 },
  { word: "miserable", pos: "形", ja: "みじめな", example: "feel miserable（みじめに感じる）", unit: 37 },
  { word: "misery", pos: "名", ja: "みじめさ", example: "live in misery（惨めに暮らす）", unit: 37 },
  { word: "mistake", pos: "名", ja: "誤り", example: "make a mistake（間違える）", unit: 37 },
  { word: "mix", pos: "動", ja: "混ぜる", example: "mix the colors（色を混ぜる）", unit: 37 },
  { word: "mixture", pos: "名", ja: "混合物", example: "a mixture of gases（気体の混合物）", unit: 37 },
  { word: "model", pos: "名", ja: "模型", example: "a plastic model（プラモデル）", unit: 37 },
  { word: "moderate", pos: "形", ja: "適度な", example: "moderate exercise（適度な運動）", unit: 37 },
  { word: "modern", pos: "形", ja: "現代の", example: "modern art（現代美術）", unit: 37 },
  { word: "moment", pos: "名", ja: "瞬間", example: "at that moment（その瞬間に）", unit: 37 },
  { word: "money", pos: "名", ja: "お金", example: "save money（お金を貯める）", unit: 37 },
  { word: "month", pos: "名", ja: "月", example: "next month（来月）", unit: 37 },
  { word: "moral", pos: "形", ja: "道徳的な", example: "a moral duty（道徳的義務）", unit: 37 },
  { word: "moreover", pos: "副", ja: "さらに", example: "moreover, it rained（さらに雨も降った）", unit: 37 },
  { word: "morning", pos: "名", ja: "朝", example: "early morning（早朝）", unit: 37 },
  { word: "mother", pos: "名", ja: "母", example: "my mother（私の母）", unit: 37 },
  { word: "motion", pos: "名", ja: "動き", example: "a slow motion（ゆっくりした動き）", unit: 37 },
  { word: "motor", pos: "名", ja: "モーター", example: "an electric motor（電気モーター）", unit: 37 },
  { word: "mountain", pos: "名", ja: "山", example: "a high mountain（高い山）", unit: 37 },
  { word: "mouse", pos: "名", ja: "ネズミ", example: "a small mouse（小さなネズミ）", unit: 38 },
  { word: "mouth", pos: "名", ja: "口", example: "open your mouth（口を開ける）", unit: 38 },
  { word: "move", pos: "動", ja: "動く", example: "move slowly（ゆっくり動く）", unit: 38 },
  { word: "mud", pos: "名", ja: "泥", example: "covered in mud（泥まみれ）", unit: 38 },
  { word: "murder", pos: "名", ja: "殺人", example: "solve a murder（殺人を解決する）", unit: 38 },
  { word: "music", pos: "名", ja: "音楽", example: "listen to music（音楽を聞く）", unit: 38 },
  { word: "musician", pos: "名", ja: "音楽家", example: "a famous musician（有名な音楽家）", unit: 38 },
  { word: "nail", pos: "名", ja: "つめ", example: "cut my nails（つめを切る）", unit: 38 },
  { word: "name", pos: "名", ja: "名前", example: "your name（あなたの名前）", unit: 38 },
  { word: "narrow", pos: "形", ja: "狭い", example: "a narrow road（狭い道）", unit: 38 },
  { word: "native", pos: "形", ja: "母国の", example: "my native language（母国語）", unit: 38 },
  { word: "nature", pos: "名", ja: "自然", example: "enjoy nature（自然を楽しむ）", unit: 38 },
  { word: "neat", pos: "形", ja: "きちんとした", example: "a neat room（きちんとした部屋）", unit: 38 },
  { word: "necessity", pos: "名", ja: "必要", example: "a daily necessity（日用必需品）", unit: 38 },
  { word: "neck", pos: "名", ja: "首", example: "a long neck（長い首）", unit: 38 },
  { word: "needle", pos: "名", ja: "針", example: "a sewing needle（縫い針）", unit: 38 },
  { word: "neglect", pos: "動", ja: "怠る", example: "neglect the work（仕事を怠る）", unit: 38 },
  { word: "nest", pos: "名", ja: "巣", example: "a bird's nest（鳥の巣）", unit: 38 },
  { word: "network", pos: "名", ja: "ネットワーク", example: "a computer network（コンピューターネットワーク）", unit: 38 },
  { word: "new", pos: "形", ja: "新しい", example: "a new car（新しい車）", unit: 38 },
  { word: "news", pos: "名", ja: "ニュース", example: "good news（良いニュース）", unit: 39 },
  { word: "newspaper", pos: "名", ja: "新聞", example: "read a newspaper（新聞を読む）", unit: 39 },
  { word: "night", pos: "名", ja: "夜", example: "a dark night（暗い夜）", unit: 39 },
  { word: "noble", pos: "形", ja: "高貴な", example: "a noble family（高貴な家柄）", unit: 39 },
  { word: "noise", pos: "名", ja: "騒音", example: "a loud noise（大きな騒音）", unit: 39 },
  { word: "north", pos: "名", ja: "北", example: "go north（北へ行く）", unit: 39 },
  { word: "northern", pos: "形", ja: "北の", example: "the northern city（北の都市）", unit: 39 },
  { word: "nose", pos: "名", ja: "鼻", example: "a big nose（大きな鼻）", unit: 39 },
  { word: "note", pos: "名", ja: "メモ", example: "take a note（メモを取る）", unit: 39 },
  { word: "notice", pos: "動", ja: "気づく", example: "notice a change（変化に気づく）", unit: 39 },
  { word: "now", pos: "副", ja: "今", example: "right now（たった今）", unit: 39 },
  { word: "number", pos: "名", ja: "数", example: "a large number（大きな数）", unit: 39 },
  { word: "numerous", pos: "形", ja: "多数の", example: "numerous people（多数の人々）", unit: 39 },
  { word: "nurse", pos: "名", ja: "看護師", example: "a kind nurse（親切な看護師）", unit: 39 },
  { word: "nut", pos: "名", ja: "ナッツ", example: "eat a nut（ナッツを食べる）", unit: 39 },
  { word: "object", pos: "名", ja: "物体", example: "a small object（小さな物体）", unit: 39 },
  { word: "objection", pos: "名", ja: "反対", example: "raise an objection（反対を唱える）", unit: 39 },
  { word: "observe", pos: "動", ja: "観察する", example: "observe the stars（星を観察する）", unit: 39 },
  { word: "ocean", pos: "名", ja: "海", example: "cross the ocean（海を渡る）", unit: 39 },
  { word: "offer", pos: "動", ja: "申し出る", example: "offer help（助けを申し出る）", unit: 39 },
];
