// 語彙パック: TOEIC730 バンド（上級・100語 / 5単元）。
//
// 選定: ejdict-hand(CC0) の頻度リストで「2000語にあって850基礎語にない＝一段上の
// リング」から、既存220語を除いて抽出（scripts/vocab/ingest-ejdict.mjs）。下書きに
// 人手キュレーションを通した確定データ。辞書の第一義ズレを是正し（accident=事故／
// admit=認める／advantage=利点／check=確認する／claim=主張する／decrease=減少する／
// director=監督 等）、例文・品詞を補った。band内で ja・word は一意。

import type { VocabEntry, VocabUnitMeta } from "./types";

export const TOEIC730_UNITS: VocabUnitMeta[] = [
  { unit: 1, title: "上級動詞（TOEIC730・その1）", lesson: "一段上の動詞を20語。英語→日本語の4択でおぼえよう。" },
  { unit: 2, title: "上級動詞（TOEIC730・その2）", lesson: "上級動詞をさらに20語。似た意味の語とのちがいに注意。" },
  { unit: 3, title: "上級名詞（TOEIC730・その1）", lesson: "ビジネス・社会で出る上級名詞を20語。" },
  { unit: 4, title: "上級名詞（TOEIC730・その2）", lesson: "上級名詞をさらに20語。" },
  { unit: 5, title: "上級形容詞（TOEIC730）", lesson: "様子や程度を表す上級形容詞を20語。" },
];

export const TOEIC730_VOCAB: VocabEntry[] = [
  // ===== ユニット1: 上級動詞 =====
  { word: "accuse", pos: "動", ja: "告発する", example: "accuse him of a crime（彼を罪で告発する）", unit: 1 },
  { word: "admit", pos: "動", ja: "認める", example: "admit a mistake（間違いを認める）", unit: 1 },
  { word: "adopt", pos: "動", ja: "取り入れる", example: "adopt a new plan（新しい案を取り入れる）", unit: 1 },
  { word: "advance", pos: "動", ja: "前進する", example: "advance step by step（一歩ずつ前進する）", unit: 1 },
  { word: "advertise", pos: "動", ja: "宣伝する", example: "advertise a product（製品を宣伝する）", unit: 1 },
  { word: "admire", pos: "動", ja: "称賛する", example: "admire her courage（彼女の勇気を称賛する）", unit: 1 },
  { word: "afford", pos: "動", ja: "余裕がある", example: "can't afford a car（車を買う余裕がない）", unit: 1 },
  { word: "aim", pos: "動", ja: "目指す", example: "aim for the top（頂点を目指す）", unit: 1 },
  { word: "appoint", pos: "動", ja: "任命する", example: "appoint a leader（リーダーを任命する）", unit: 1 },
  { word: "approve", pos: "動", ja: "承認する", example: "approve the budget（予算を承認する）", unit: 1 },
  { word: "descend", pos: "動", ja: "下る", example: "descend the stairs（階段を下りる）", unit: 1 },
  { word: "check", pos: "動", ja: "確認する", example: "check the schedule（予定を確認する）", unit: 1 },
  { word: "choose", pos: "動", ja: "選ぶ", example: "choose a plan（案を選ぶ）", unit: 1 },
  { word: "claim", pos: "動", ja: "主張する", example: "claim one's innocence（無実を主張する）", unit: 1 },
  { word: "combine", pos: "動", ja: "結合する", example: "combine forces（力を結合する）", unit: 1 },
  { word: "command", pos: "動", ja: "命令する", example: "command an army（軍に命令する）", unit: 1 },
  { word: "compete", pos: "動", ja: "競争する", example: "compete with rivals（ライバルと競争する）", unit: 1 },
  { word: "complain", pos: "動", ja: "不平を言う", example: "complain about service（サービスに不平を言う）", unit: 1 },
  { word: "compose", pos: "動", ja: "構成する", example: "compose a committee（委員会を構成する）", unit: 1 },
  { word: "confess", pos: "動", ja: "告白する", example: "confess a secret（秘密を告白する）", unit: 1 },

  // ===== ユニット2: 上級動詞 =====
  { word: "confuse", pos: "動", ja: "混乱させる", example: "confuse the audience（聴衆を混乱させる）", unit: 2 },
  { word: "connect", pos: "動", ja: "接続する", example: "connect two cities（二つの都市を接続する）", unit: 2 },
  { word: "consider", pos: "動", ja: "考慮する", example: "consider the risks（危険を考慮する）", unit: 2 },
  { word: "contain", pos: "動", ja: "含む", example: "contain vitamins（ビタミンを含む）", unit: 2 },
  { word: "count", pos: "動", ja: "数える", example: "count the guests（客を数える）", unit: 2 },
  { word: "cultivate", pos: "動", ja: "栽培する", example: "cultivate rice（米を栽培する）", unit: 2 },
  { word: "cure", pos: "動", ja: "治療する", example: "cure an illness（病気を治療する）", unit: 2 },
  { word: "dare", pos: "動", ja: "あえてする", example: "dare to try（あえて挑戦する）", unit: 2 },
  { word: "declare", pos: "動", ja: "宣言する", example: "declare victory（勝利を宣言する）", unit: 2 },
  { word: "decrease", pos: "動", ja: "減少する", example: "Sales decrease.（売上が減少する）", unit: 2 },
  { word: "defeat", pos: "動", ja: "負かす", example: "defeat an opponent（相手を負かす）", unit: 2 },
  { word: "defend", pos: "動", ja: "守る", example: "defend the castle（城を守る）", unit: 2 },
  { word: "delay", pos: "動", ja: "遅らせる", example: "delay the launch（開始を遅らせる）", unit: 2 },
  { word: "demand", pos: "動", ja: "要求する", example: "demand a refund（返金を要求する）", unit: 2 },
  { word: "depend", pos: "動", ja: "頼る", example: "depend on support（支援に頼る）", unit: 2 },
  { word: "describe", pos: "動", ja: "描写する", example: "describe an event（出来事を描写する）", unit: 2 },
  { word: "deserve", pos: "動", ja: "値する", example: "deserve a reward（報酬に値する）", unit: 2 },
  { word: "destroy", pos: "動", ja: "破壊する", example: "destroy a bridge（橋を破壊する）", unit: 2 },
  { word: "determine", pos: "動", ja: "決定する", example: "determine a date（日程を決定する）", unit: 2 },
  { word: "develop", pos: "動", ja: "発展させる", example: "develop a region（地域を発展させる）", unit: 2 },

  // ===== ユニット3: 上級名詞 =====
  { word: "ability", pos: "名", ja: "能力", example: "leadership ability（統率能力）", unit: 3 },
  { word: "absence", pos: "名", ja: "欠席", example: "a long absence（長期の欠席）", unit: 3 },
  { word: "accident", pos: "名", ja: "事故", example: "a traffic accident（交通事故）", unit: 3 },
  { word: "advantage", pos: "名", ja: "利点", example: "a clear advantage（明らかな利点）", unit: 3 },
  { word: "adventure", pos: "名", ja: "冒険", example: "an exciting adventure（わくわくする冒険）", unit: 3 },
  { word: "agency", pos: "名", ja: "代理店", example: "an advertising agency（広告代理店）", unit: 3 },
  { word: "agent", pos: "名", ja: "代理人", example: "a sales agent（販売代理人）", unit: 3 },
  { word: "agriculture", pos: "名", ja: "農業", example: "local agriculture（地域の農業）", unit: 3 },
  { word: "allowance", pos: "名", ja: "手当", example: "a housing allowance（住宅手当）", unit: 3 },
  { word: "ambition", pos: "名", ja: "野心", example: "political ambition（政治的野心）", unit: 3 },
  { word: "application", pos: "名", ja: "申し込み", example: "submit an application（申し込みを提出する）", unit: 3 },
  { word: "ceremony", pos: "名", ja: "儀式", example: "an opening ceremony（開会式）", unit: 3 },
  { word: "character", pos: "名", ja: "性格", example: "a strong character（強い性格）", unit: 3 },
  { word: "charge", pos: "名", ja: "料金", example: "a service charge（サービス料）", unit: 3 },
  { word: "charm", pos: "名", ja: "魅力", example: "natural charm（生まれつきの魅力）", unit: 3 },
  { word: "choice", pos: "名", ja: "選択", example: "a wise choice（賢い選択）", unit: 3 },
  { word: "citizen", pos: "名", ja: "市民", example: "a senior citizen（高齢の市民）", unit: 3 },
  { word: "colony", pos: "名", ja: "植民地", example: "a British colony（英国の植民地）", unit: 3 },
  { word: "commerce", pos: "名", ja: "商業", example: "e-commerce（電子商取引）", unit: 3 },
  { word: "companion", pos: "名", ja: "仲間", example: "a loyal companion（忠実な仲間）", unit: 3 },

  // ===== ユニット4: 上級名詞 =====
  { word: "complaint", pos: "名", ja: "苦情", example: "a customer complaint（顧客の苦情）", unit: 4 },
  { word: "concern", pos: "名", ja: "懸念", example: "a growing concern（高まる懸念）", unit: 4 },
  { word: "confidence", pos: "名", ja: "自信", example: "gain confidence（自信を得る）", unit: 4 },
  { word: "confession", pos: "名", ja: "自白", example: "a written confession（書面の自白）", unit: 4 },
  { word: "conscience", pos: "名", ja: "良心", example: "follow one's conscience（良心に従う）", unit: 4 },
  { word: "conversation", pos: "名", ja: "会話", example: "a phone conversation（電話での会話）", unit: 4 },
  { word: "council", pos: "名", ja: "評議会", example: "a town council（町議会）", unit: 4 },
  { word: "courage", pos: "名", ja: "勇気", example: "show courage（勇気を示す）", unit: 4 },
  { word: "course", pos: "名", ja: "進路", example: "change course（進路を変える）", unit: 4 },
  { word: "criminal", pos: "名", ja: "犯罪者", example: "a dangerous criminal（危険な犯罪者）", unit: 4 },
  { word: "custom", pos: "名", ja: "習慣", example: "an old custom（古い習慣）", unit: 4 },
  { word: "cost", pos: "名", ja: "費用", example: "a low cost（低い費用）", unit: 4 },
  { word: "depth", pos: "名", ja: "深さ", example: "the depth of a river（川の深さ）", unit: 4 },
  { word: "description", pos: "名", ja: "記述", example: "a detailed description（詳しい記述）", unit: 4 },
  { word: "desert", pos: "名", ja: "砂漠", example: "cross the desert（砂漠を横断する）", unit: 4 },
  { word: "difficulty", pos: "名", ja: "困難", example: "overcome difficulty（困難を乗り越える）", unit: 4 },
  { word: "director", pos: "名", ja: "監督", example: "a film director（映画監督）", unit: 4 },
  { word: "defendant", pos: "名", ja: "被告", example: "defend the defendant（被告を弁護する）", unit: 4 },
  { word: "crowd", pos: "名", ja: "群衆", example: "a huge crowd（巨大な群衆）", unit: 4 },
  { word: "despair", pos: "名", ja: "絶望", example: "fall into despair（絶望に陥る）", unit: 4 },

  // ===== ユニット5: 上級形容詞 =====
  { word: "absent", pos: "形", ja: "不在の", example: "absent from class（授業を欠席して）", unit: 5 },
  { word: "absolute", pos: "形", ja: "完全な", example: "absolute trust（完全な信頼）", unit: 5 },
  { word: "active", pos: "形", ja: "活動的な", example: "an active member（活動的な会員）", unit: 5 },
  { word: "actual", pos: "形", ja: "実際の", example: "the actual result（実際の結果）", unit: 5 },
  { word: "alive", pos: "形", ja: "生きている", example: "stay alive（生き続ける）", unit: 5 },
  { word: "cautious", pos: "形", ja: "用心深い", example: "a cautious approach（用心深いやり方）", unit: 5 },
  { word: "clever", pos: "形", ja: "賢い", example: "a clever plan（賢い計画）", unit: 5 },
  { word: "circular", pos: "形", ja: "円形の", example: "a circular shape（円形）", unit: 5 },
  { word: "commercial", pos: "形", ja: "商業の", example: "a commercial area（商業地域）", unit: 5 },
  { word: "confident", pos: "形", ja: "自信のある", example: "a confident answer（自信のある答え）", unit: 5 },
  { word: "correct", pos: "形", ja: "正しい", example: "a correct guess（正しい推測）", unit: 5 },
  { word: "curious", pos: "形", ja: "好奇心の強い", example: "a curious student（好奇心の強い生徒）", unit: 5 },
  { word: "daily", pos: "形", ja: "毎日の", example: "a daily report（毎日の報告）", unit: 5 },
  { word: "decisive", pos: "形", ja: "決定的な", example: "a decisive victory（決定的な勝利）", unit: 5 },
  { word: "direct", pos: "形", ja: "直接の", example: "a direct route（直接のルート）", unit: 5 },
  { word: "destructive", pos: "形", ja: "破壊的な", example: "a destructive storm（破壊的な嵐）", unit: 5 },
  { word: "customary", pos: "形", ja: "習慣的な", example: "a customary practice（習慣的な慣行）", unit: 5 },
  { word: "earnest", pos: "形", ja: "真剣な", example: "an earnest effort（真剣な努力）", unit: 5 },
  { word: "dull", pos: "形", ja: "鈍い", example: "a dull blade（鈍い刃）", unit: 5 },
  { word: "double", pos: "形", ja: "2倍の", example: "a double portion（2倍の分量）", unit: 5 },
];
