// 語彙パック: TOEIC500 バンド 追加分C（頻出基礎語）。
// ejdict-hand(CC0) 取込→並列サブエージェントで語義是正・機能語除去したもの。
// 既存の全 eikaiwa 語と word・ja が重複しないよう調整済み（意味は全トラックで一意）。
import type { VocabEntry, VocabUnitMeta } from "./types";

export const TOEIC500_C_UNITS: VocabUnitMeta[] = [
  { unit: 7, title: "頻出基礎語（TOEIC500・その7）", lesson: "よく使う基礎語を英語→日本語の4択でおぼえよう。" },
  { unit: 8, title: "頻出基礎語（TOEIC500・その8）", lesson: "よく使う基礎語を英語→日本語の4択でおぼえよう。" },
  { unit: 9, title: "頻出基礎語（TOEIC500・その9）", lesson: "よく使う基礎語を英語→日本語の4択でおぼえよう。" },
  { unit: 10, title: "頻出基礎語（TOEIC500・その10）", lesson: "よく使う基礎語を英語→日本語の4択でおぼえよう。" },
  { unit: 11, title: "頻出基礎語（TOEIC500・その11）", lesson: "よく使う基礎語を英語→日本語の4択でおぼえよう。" },
  { unit: 12, title: "頻出基礎語（TOEIC500・その12）", lesson: "よく使う基礎語を英語→日本語の4択でおぼえよう。" },
  { unit: 13, title: "頻出基礎語（TOEIC500・その13）", lesson: "よく使う基礎語を英語→日本語の4択でおぼえよう。" },
  { unit: 14, title: "頻出基礎語（TOEIC500・その14）", lesson: "よく使う基礎語を英語→日本語の4択でおぼえよう。" },
  { unit: 15, title: "頻出基礎語（TOEIC500・その15）", lesson: "よく使う基礎語を英語→日本語の4択でおぼえよう。" },
  { unit: 16, title: "頻出基礎語（TOEIC500・その16）", lesson: "よく使う基礎語を英語→日本語の4択でおぼえよう。" },
];

export const TOEIC500_C_VOCAB: VocabEntry[] = [
  { word: "able", pos: "形", ja: "できる", example: "be able to swim（泳ぐことができる）", unit: 7 },
  { word: "abroad", pos: "副", ja: "海外へ", example: "go abroad（海外へ行く）", unit: 7 },
  { word: "account", pos: "名", ja: "口座", example: "a bank account（銀行口座）", unit: 7 },
  { word: "action", pos: "名", ja: "行動", example: "take action（行動を起こす）", unit: 7 },
  { word: "actor", pos: "名", ja: "俳優", example: "a famous actor（有名な俳優）", unit: 7 },
  { word: "add", pos: "動", ja: "加える", example: "add sugar（砂糖を加える）", unit: 7 },
  { word: "address", pos: "名", ja: "住所", example: "my email address（メールアドレス）", unit: 7 },
  { word: "admission", pos: "名", ja: "入場", example: "free admission（入場無料）", unit: 7 },
  { word: "advise", pos: "動", ja: "助言する", example: "advise a friend（友人に助言する）", unit: 7 },
  { word: "afraid", pos: "形", ja: "恐れて", example: "be afraid of dogs（犬を怖がる）", unit: 7 },
  { word: "afternoon", pos: "名", ja: "午後", example: "in the afternoon（午後に）", unit: 7 },
  { word: "age", pos: "名", ja: "年齢", example: "at the age of ten（10歳のとき）", unit: 7 },
  { word: "agree", pos: "動", ja: "同意する", example: "agree with you（あなたに同意する）", unit: 7 },
  { word: "air", pos: "名", ja: "空気", example: "fresh air（新鮮な空気）", unit: 7 },
  { word: "airplane", pos: "名", ja: "飛行機", example: "by airplane（飛行機で）", unit: 7 },
  { word: "almost", pos: "副", ja: "ほとんど", example: "almost done（ほとんど終わった）", unit: 7 },
  { word: "alone", pos: "副", ja: "ひとりで", example: "live alone（ひとりで暮らす）", unit: 7 },
  { word: "already", pos: "副", ja: "すでに", example: "already finished（すでに終わった）", unit: 7 },
  { word: "amuse", pos: "動", ja: "楽しませる", example: "amuse children（子供を楽しませる）", unit: 8 },
  { word: "angle", pos: "名", ja: "角度", example: "a right angle（直角）", unit: 8 },
  { word: "animal", pos: "名", ja: "動物", example: "a wild animal（野生動物）", unit: 8 },
  { word: "anxiety", pos: "名", ja: "不安", example: "feel anxiety（不安を感じる）", unit: 8 },
  { word: "anxious", pos: "形", ja: "心配して", example: "anxious about the test（試験を心配する）", unit: 8 },
  { word: "appearance", pos: "名", ja: "外見", example: "neat appearance（きちんとした外見）", unit: 8 },
  { word: "arise", pos: "動", ja: "生じる", example: "problems arise（問題が生じる）", unit: 8 },
  { word: "arrest", pos: "動", ja: "逮捕する", example: "arrest a thief（泥棒を逮捕する）", unit: 8 },
  { word: "arrive", pos: "動", ja: "到着する", example: "arrive at the station（駅に着く）", unit: 8 },
  { word: "arrow", pos: "名", ja: "矢印", example: "follow the arrow（矢印に従う）", unit: 8 },
  { word: "ash", pos: "名", ja: "灰", example: "cigarette ash（タバコの灰）", unit: 8 },
  { word: "ashamed", pos: "形", ja: "恥じて", example: "ashamed of oneself（自分を恥じる）", unit: 8 },
  { word: "ask", pos: "動", ja: "尋ねる", example: "ask a question（質問する）", unit: 8 },
  { word: "asleep", pos: "形", ja: "眠って", example: "fall asleep（眠りに落ちる）", unit: 8 },
  { word: "association", pos: "名", ja: "団体", example: "a sports association（スポーツ団体）", unit: 8 },
  { word: "astonish", pos: "動", ja: "驚かせる", example: "astonish everyone（皆を驚かせる）", unit: 8 },
  { word: "attraction", pos: "名", ja: "呼び物", example: "a tourist attraction（観光の呼び物）", unit: 8 },
  { word: "aunt", pos: "名", ja: "おば", example: "my aunt（私のおば）", unit: 8 },
  { word: "autumn", pos: "名", ja: "秋", example: "in autumn（秋に）", unit: 8 },
  { word: "avenue", pos: "名", ja: "大通り", example: "a wide avenue（広い大通り）", unit: 8 },
  { word: "awake", pos: "形", ja: "目が覚めて", example: "stay awake（起きている）", unit: 9 },
  { word: "awkward", pos: "形", ja: "気まずい", example: "an awkward silence（気まずい沈黙）", unit: 9 },
  { word: "baby", pos: "名", ja: "赤ん坊", example: "a newborn baby（新生児）", unit: 9 },
  { word: "back", pos: "名", ja: "背中", example: "lie on your back（あおむけに寝る）", unit: 9 },
  { word: "backward", pos: "副", ja: "後ろへ", example: "step backward（後ろへ下がる）", unit: 9 },
  { word: "bag", pos: "名", ja: "袋", example: "a paper bag（紙袋）", unit: 9 },
  { word: "bake", pos: "動", ja: "焼く", example: "bake a cake（ケーキを焼く）", unit: 9 },
  { word: "balance", pos: "名", ja: "バランス", example: "keep your balance（バランスを保つ）", unit: 9 },
  { word: "ball", pos: "名", ja: "ボール", example: "throw a ball（ボールを投げる）", unit: 9 },
  { word: "band", pos: "名", ja: "バンド", example: "a rock band（ロックバンド）", unit: 9 },
  { word: "bank", pos: "名", ja: "銀行", example: "go to the bank（銀行に行く）", unit: 9 },
  { word: "bar", pos: "名", ja: "棒", example: "an iron bar（鉄の棒）", unit: 9 },
  { word: "bare", pos: "形", ja: "むき出しの", example: "bare feet（はだし）", unit: 9 },
  { word: "bargain", pos: "名", ja: "お買い得品", example: "a great bargain（掘り出し物）", unit: 9 },
  { word: "barrel", pos: "名", ja: "たる", example: "a barrel of oil（石油1バレル）", unit: 9 },
  { word: "basis", pos: "名", ja: "基礎", example: "on a daily basis（毎日）", unit: 9 },
  { word: "basket", pos: "名", ja: "かご", example: "a shopping basket（買い物かご）", unit: 9 },
  { word: "bath", pos: "名", ja: "入浴", example: "take a bath（お風呂に入る）", unit: 9 },
  { word: "bathe", pos: "動", ja: "入浴する", example: "bathe the baby（赤ん坊を入浴させる）", unit: 9 },
  { word: "bay", pos: "名", ja: "湾", example: "a calm bay（穏やかな湾）", unit: 9 },
  { word: "bear", pos: "動", ja: "耐える", example: "bear the pain（痛みに耐える）", unit: 10 },
  { word: "beard", pos: "名", ja: "あごひげ", example: "grow a beard（ひげを生やす）", unit: 10 },
  { word: "beat", pos: "動", ja: "打ち負かす", example: "beat the team（チームを負かす）", unit: 10 },
  { word: "beauty", pos: "名", ja: "美しさ", example: "natural beauty（自然の美）", unit: 10 },
  { word: "bed", pos: "名", ja: "ベッド", example: "go to bed（寝る）", unit: 10 },
  { word: "bedroom", pos: "名", ja: "寝室", example: "a small bedroom（小さな寝室）", unit: 10 },
  { word: "beg", pos: "動", ja: "懇願する", example: "beg for help（助けを乞う）", unit: 10 },
  { word: "behave", pos: "動", ja: "ふるまう", example: "behave well（行儀よくする）", unit: 10 },
  { word: "being", pos: "名", ja: "存在", example: "a human being（人間）", unit: 10 },
  { word: "belong", pos: "動", ja: "所属する", example: "belong to a club（クラブに所属する）", unit: 10 },
  { word: "belt", pos: "名", ja: "ベルト", example: "a seat belt（シートベルト）", unit: 10 },
  { word: "bend", pos: "動", ja: "曲げる", example: "bend your knees（ひざを曲げる）", unit: 10 },
  { word: "bill", pos: "名", ja: "勘定書", example: "pay the bill（勘定を払う）", unit: 10 },
  { word: "bind", pos: "動", ja: "縛る", example: "bind the rope（ロープを縛る）", unit: 10 },
  { word: "bird", pos: "名", ja: "鳥", example: "a wild bird（野鳥）", unit: 10 },
  { word: "bite", pos: "動", ja: "かむ", example: "bite an apple（りんごをかじる）", unit: 10 },
  { word: "blade", pos: "名", ja: "刃", example: "a sharp blade（鋭い刃）", unit: 10 },
  { word: "blame", pos: "動", ja: "責める", example: "blame others（人のせいにする）", unit: 10 },
  { word: "bleed", pos: "動", ja: "出血する", example: "bleed heavily（大量に出血する）", unit: 10 },
  { word: "bless", pos: "動", ja: "祝福する", example: "bless the couple（夫婦を祝福する）", unit: 10 },
  { word: "block", pos: "名", ja: "かたまり", example: "a block of ice（氷のかたまり）", unit: 11 },
  { word: "blood", pos: "名", ja: "血", example: "give blood（献血する）", unit: 11 },
  { word: "blow", pos: "動", ja: "吹く", example: "blow the whistle（笛を吹く）", unit: 11 },
  { word: "boast", pos: "動", ja: "自慢する", example: "boast about success（成功を自慢する）", unit: 11 },
  { word: "boat", pos: "名", ja: "ボート", example: "row a boat（ボートをこぐ）", unit: 11 },
  { word: "boil", pos: "動", ja: "沸かす", example: "boil water（お湯を沸かす）", unit: 11 },
  { word: "bone", pos: "名", ja: "骨", example: "break a bone（骨を折る）", unit: 11 },
  { word: "border", pos: "名", ja: "国境", example: "cross the border（国境を越える）", unit: 11 },
  { word: "both", pos: "形", ja: "両方の", example: "both hands（両手）", unit: 11 },
  { word: "bottle", pos: "名", ja: "びん", example: "a bottle of water（水のボトル）", unit: 11 },
  { word: "bottom", pos: "名", ja: "底", example: "the bottom of the sea（海の底）", unit: 11 },
  { word: "boundary", pos: "名", ja: "境界線", example: "cross the boundary（境界を越える）", unit: 11 },
  { word: "bowl", pos: "名", ja: "ボウル", example: "a bowl of rice（茶碗一杯のご飯）", unit: 11 },
  { word: "box", pos: "名", ja: "箱", example: "a cardboard box（段ボール箱）", unit: 11 },
  { word: "boy", pos: "名", ja: "少年", example: "a little boy（小さな男の子）", unit: 11 },
  { word: "brain", pos: "名", ja: "脳", example: "the human brain（人間の脳）", unit: 11 },
  { word: "bread", pos: "名", ja: "パン", example: "a loaf of bread（一斤のパン）", unit: 11 },
  { word: "breakfast", pos: "名", ja: "朝食", example: "eat breakfast（朝食を食べる）", unit: 11 },
  { word: "breath", pos: "名", ja: "息", example: "take a deep breath（深呼吸する）", unit: 11 },
  { word: "breathe", pos: "動", ja: "呼吸する", example: "breathe deeply（深く呼吸する）", unit: 11 },
  { word: "brick", pos: "名", ja: "れんが", example: "a brick wall（れんがの壁）", unit: 12 },
  { word: "bridge", pos: "名", ja: "橋", example: "cross a bridge（橋を渡る）", unit: 12 },
  { word: "broadcast", pos: "動", ja: "放送する", example: "broadcast the news（ニュースを放送する）", unit: 12 },
  { word: "brother", pos: "名", ja: "兄弟", example: "my older brother（私の兄）", unit: 12 },
  { word: "brush", pos: "名", ja: "ブラシ", example: "a hair brush（ヘアブラシ）", unit: 12 },
  { word: "bunch", pos: "名", ja: "束", example: "a bunch of flowers（花束）", unit: 12 },
  { word: "burst", pos: "動", ja: "破裂する", example: "the balloon burst（風船が破裂した）", unit: 12 },
  { word: "bury", pos: "動", ja: "埋める", example: "bury treasure（宝を埋める）", unit: 12 },
  { word: "bush", pos: "名", ja: "低木", example: "hide in the bushes（茂みに隠れる）", unit: 12 },
  { word: "businessman", pos: "名", ja: "実業家", example: "a successful businessman（成功した実業家）", unit: 12 },
  { word: "butter", pos: "名", ja: "バター", example: "bread and butter（バター付きパン）", unit: 12 },
  { word: "button", pos: "名", ja: "ボタン", example: "press the button（ボタンを押す）", unit: 12 },
  { word: "cake", pos: "名", ja: "ケーキ", example: "a piece of cake（ケーキ一切れ）", unit: 12 },
  { word: "calculation", pos: "名", ja: "計算", example: "do a calculation（計算をする）", unit: 12 },
  { word: "camera", pos: "名", ja: "カメラ", example: "take a photo with a camera（カメラで撮影する）", unit: 12 },
  { word: "camp", pos: "名", ja: "キャンプ", example: "set up camp（キャンプを張る）", unit: 12 },
  { word: "captain", pos: "名", ja: "船長", example: "the ship's captain（船の船長）", unit: 12 },
  { word: "carriage", pos: "名", ja: "馬車", example: "a horse carriage（馬車）", unit: 12 },
  { word: "cattle", pos: "名", ja: "家畜の牛", example: "raise cattle（牛を飼育する）", unit: 12 },
  { word: "cause", pos: "名", ja: "原因", example: "the cause of the fire（火事の原因）", unit: 12 },
  { word: "caution", pos: "名", ja: "用心", example: "proceed with caution（注意して進む）", unit: 13 },
  { word: "cave", pos: "名", ja: "ほら穴", example: "explore a cave（洞窟を探検する）", unit: 13 },
  { word: "century", pos: "名", ja: "世紀", example: "the 21st century（21世紀）", unit: 13 },
  { word: "certain", pos: "形", ja: "確信して", example: "I am certain（私は確信している）", unit: 13 },
  { word: "certainty", pos: "名", ja: "確実性", example: "with certainty（確実に）", unit: 13 },
  { word: "chain", pos: "名", ja: "鎖", example: "a gold chain（金の鎖）", unit: 13 },
  { word: "chair", pos: "名", ja: "いす", example: "sit on a chair（いすに座る）", unit: 13 },
  { word: "chairman", pos: "名", ja: "議長", example: "the chairman（議長）", unit: 13 },
  { word: "chance", pos: "名", ja: "機会", example: "a good chance（良い機会）", unit: 13 },
  { word: "change", pos: "動", ja: "変える", example: "change your mind（考えを変える）", unit: 13 },
  { word: "cheap", pos: "形", ja: "安い", example: "a cheap ticket（安い切符）", unit: 13 },
  { word: "cheer", pos: "動", ja: "応援する", example: "cheer for the team（チームを応援する）", unit: 13 },
  { word: "chest", pos: "名", ja: "胸", example: "chest pain（胸の痛み）", unit: 13 },
  { word: "chicken", pos: "名", ja: "鶏", example: "fried chicken（フライドチキン）", unit: 13 },
  { word: "child", pos: "名", ja: "子供", example: "a young child（幼い子供）", unit: 13 },
  { word: "childhood", pos: "名", ja: "子供時代", example: "a happy childhood（幸せな子供時代）", unit: 13 },
  { word: "church", pos: "名", ja: "教会", example: "go to church（教会へ行く）", unit: 13 },
  { word: "circle", pos: "名", ja: "円", example: "draw a circle（円を描く）", unit: 13 },
  { word: "city", pos: "名", ja: "都市", example: "a big city（大都市）", unit: 13 },
  { word: "class", pos: "名", ja: "授業", example: "attend a class（授業に出る）", unit: 13 },
  { word: "classification", pos: "名", ja: "分類", example: "the classification of books（本の分類）", unit: 14 },
  { word: "classify", pos: "動", ja: "分類する", example: "classify data（データを分類する）", unit: 14 },
  { word: "clay", pos: "名", ja: "粘土", example: "a clay pot（粘土の壺）", unit: 14 },
  { word: "clean", pos: "形", ja: "清潔な", example: "a clean room（清潔な部屋）", unit: 14 },
  { word: "clear", pos: "形", ja: "はっきりした", example: "a clear explanation（はっきりした説明）", unit: 14 },
  { word: "clerk", pos: "名", ja: "店員", example: "a store clerk（店員）", unit: 14 },
  { word: "climb", pos: "動", ja: "登る", example: "climb a mountain（山に登る）", unit: 14 },
  { word: "clock", pos: "名", ja: "時計", example: "look at the clock（時計を見る）", unit: 14 },
  { word: "close", pos: "動", ja: "閉じる", example: "close the door（ドアを閉める）", unit: 14 },
  { word: "cloth", pos: "名", ja: "布", example: "a piece of cloth（一枚の布）", unit: 14 },
  { word: "clothe", pos: "動", ja: "服を着せる", example: "clothe a child（子供に服を着せる）", unit: 14 },
  { word: "cloud", pos: "名", ja: "雲", example: "a dark cloud（黒い雲）", unit: 14 },
  { word: "coal", pos: "名", ja: "石炭", example: "burn coal（石炭を燃やす）", unit: 14 },
  { word: "coast", pos: "名", ja: "海岸", example: "the west coast（西海岸）", unit: 14 },
  { word: "coat", pos: "名", ja: "コート", example: "wear a coat（コートを着る）", unit: 14 },
  { word: "coffee", pos: "名", ja: "コーヒー", example: "a cup of coffee（一杯のコーヒー）", unit: 14 },
  { word: "coin", pos: "名", ja: "硬貨", example: "a gold coin（金貨）", unit: 14 },
  { word: "cold", pos: "形", ja: "寒い", example: "a cold morning（寒い朝）", unit: 14 },
  { word: "collar", pos: "名", ja: "えり", example: "a shirt collar（シャツのえり）", unit: 14 },
  { word: "collection", pos: "名", ja: "収集", example: "a stamp collection（切手の収集）", unit: 14 },
  { word: "college", pos: "名", ja: "大学", example: "go to college（大学に通う）", unit: 15 },
  { word: "comfort", pos: "動", ja: "慰める", example: "comfort a friend（友を慰める）", unit: 15 },
  { word: "committee", pos: "名", ja: "委員会", example: "a school committee（学校の委員会）", unit: 15 },
  { word: "common", pos: "形", ja: "共通の", example: "a common goal（共通の目標）", unit: 15 },
  { word: "comparison", pos: "名", ja: "比較", example: "make a comparison（比較する）", unit: 15 },
  { word: "competition", pos: "名", ja: "競争", example: "win the competition（競争に勝つ）", unit: 15 },
  { word: "completion", pos: "名", ja: "完成", example: "the completion of work（仕事の完成）", unit: 15 },
  { word: "complicate", pos: "動", ja: "複雑にする", example: "complicate matters（事を複雑にする）", unit: 15 },
  { word: "composition", pos: "名", ja: "作文", example: "write a composition（作文を書く）", unit: 15 },
  { word: "condition", pos: "名", ja: "状態", example: "in good condition（良い状態で）", unit: 15 },
  { word: "conscious", pos: "形", ja: "気づいて", example: "be conscious of danger（危険に気づく）", unit: 15 },
  { word: "content", pos: "名", ja: "中身", example: "the content of a box（箱の中身）", unit: 15 },
  { word: "control", pos: "動", ja: "支配する", example: "control a machine（機械を制御する）", unit: 15 },
  { word: "convenience", pos: "名", ja: "便利さ", example: "for your convenience（あなたの便利のため）", unit: 15 },
  { word: "cook", pos: "動", ja: "料理する", example: "cook dinner（夕食を作る）", unit: 15 },
  { word: "cool", pos: "形", ja: "涼しい", example: "a cool breeze（涼しい風）", unit: 15 },
  { word: "copy", pos: "動", ja: "写す", example: "copy a document（書類を写す）", unit: 15 },
  { word: "corn", pos: "名", ja: "とうもろこし", example: "grow corn（とうもろこしを育てる）", unit: 15 },
  { word: "cottage", pos: "名", ja: "小さな家", example: "a country cottage（田舎の家）", unit: 15 },
  { word: "cotton", pos: "名", ja: "綿", example: "a cotton shirt（綿のシャツ）", unit: 15 },
  { word: "country", pos: "名", ja: "国", example: "a foreign country（外国）", unit: 16 },
  { word: "court", pos: "名", ja: "裁判所", example: "go to court（裁判所へ行く）", unit: 16 },
  { word: "cousin", pos: "名", ja: "いとこ", example: "my cousin（私のいとこ）", unit: 16 },
  { word: "cover", pos: "動", ja: "おおう", example: "cover the table（テーブルをおおう）", unit: 16 },
  { word: "cow", pos: "名", ja: "雌牛", example: "milk a cow（牛の乳をしぼる）", unit: 16 },
  { word: "crack", pos: "名", ja: "割れ目", example: "a crack in the wall（壁の割れ目）", unit: 16 },
  { word: "crash", pos: "動", ja: "衝突する", example: "the car crashed（車が衝突した）", unit: 16 },
  { word: "cream", pos: "名", ja: "クリーム", example: "whipped cream（ホイップクリーム）", unit: 16 },
  { word: "creature", pos: "名", ja: "生き物", example: "a strange creature（奇妙な生き物）", unit: 16 },
  { word: "creep", pos: "動", ja: "這う", example: "creep on the floor（床を這う）", unit: 16 },
  { word: "crime", pos: "名", ja: "犯罪", example: "commit a crime（犯罪を犯す）", unit: 16 },
  { word: "crop", pos: "名", ja: "作物", example: "grow crops（作物を育てる）", unit: 16 },
  { word: "cross", pos: "動", ja: "渡る", example: "cross the street（通りを渡る）", unit: 16 },
  { word: "crown", pos: "名", ja: "王冠", example: "a golden crown（金の王冠）", unit: 16 },
  { word: "cruel", pos: "形", ja: "残酷な", example: "a cruel act（残酷な行為）", unit: 16 },
  { word: "crush", pos: "動", ja: "押しつぶす", example: "crush a can（缶をつぶす）", unit: 16 },
  { word: "cry", pos: "動", ja: "泣く", example: "cry loudly（大声で泣く）", unit: 16 },
  { word: "cup", pos: "名", ja: "カップ", example: "a cup of tea（一杯のお茶）", unit: 16 },
  { word: "current", pos: "形", ja: "現在の", example: "the current situation（現在の状況）", unit: 16 },
  { word: "curtain", pos: "名", ja: "カーテン", example: "open the curtain（カーテンを開ける）", unit: 16 },
];
