// 中学2年 英語（中2）の追加問題バンク（english_j2f）。
// サブエージェントが作問し、別エージェントで文法監査した authored 確定データ。
// 生成AIは出題・採点・解説に使わない（採点は engine が answerIndex 比較）。
import type { QuizUnit } from "@/lib/quiz/types";

export const ENGLISH_UNITS_J2F: QuizUnit[] = [
  {
    id: "j2fe-future",
    subject: "english",
    grade: "中2",
    title: "未来形（will / be going to）",
    lesson: "これからのことを表すときは will か be going to を使います。どちらもあとに動詞の原形がきます（will go / be going to go）。will の否定は will not（短縮形 won't）、疑問文は Will you 〜? の形です。be going to は be動詞を主語に合わせて変え、疑問文は be動詞を前に出します。tomorrow や next week などの語といっしょによく使います。",
    items: [
      {
        id: "j2fe-future-1",
        question: "It ___ tomorrow afternoon.（明日の午後は雨が降るでしょう）",
        choices: ["will rains","will rain","wills rain","will raining"],
        answerIndex: 1,
        explanation: "will のあとの動詞はいつも原形です。主語が It でも rain のままで、s はつけません。",
        choiceHints: ["will のあとの動詞に s はつきません。will rain が正しい形です。",null,"will は主語によって形が変わりません。wills とは言いません。","will のあとは -ing 形ではなく原形です。will rain にします。"],
      },
      {
        id: "j2fe-future-2",
        question: "We ___ going to clean the park next Saturday.（私たちは次の土曜日に公園をそうじするつもりです）",
        choices: ["is","am","be","are"],
        answerIndex: 3,
        explanation: "be going to の be は主語に合わせて形を変えます。主語が We なので are going to です。",
        choiceHints: ["is は he / she / it など3人称単数の主語のときの形です。We には are を使います。","am を使うのは主語が I のときだけです。","be はそのままでは使えません。主語 We に合わせて are にします。",null],
      },
      {
        id: "j2fe-future-3",
        question: "He ___ come to the party tomorrow.（彼は明日、パーティーに来ないでしょう）",
        choices: ["doesn't","didn't","won't","isn't"],
        answerIndex: 2,
        explanation: "未来のことを打ち消すときは will not（短縮形 won't）を使い、そのあとは動詞の原形です。",
        choiceHints: ["doesn't は今のことを打ち消す形です。tomorrow があるので won't を使います。","didn't は過去のことを打ち消す形です。明日のことなので won't にします。",null,"isn't のあとに原形 come は続けられません。未来の否定は won't come です。"],
      },
      {
        id: "j2fe-future-4",
        question: "___ you be free next Monday?（次の月曜日、あなたはひまですか）",
        choices: ["Do","Will","Did","Are"],
        answerIndex: 1,
        explanation: "未来のことをたずねるときは Will を文の最初に置きます。そのあとは主語＋動詞の原形（be）です。",
        choiceHints: ["Do のあとに be は続きません。未来のことなので Will you be 〜? にします。",null,"Did は過去のことをたずねる形です。next Monday なので Will にします。","Are を使うなら be はいりません。ここは be があるので Will が入ります。"],
      },
      {
        id: "j2fe-future-5",
        question: "___ she going to visit Kyoto next month?（彼女は来月、京都をおとずれるつもりですか）",
        choices: ["Does","Will","Is","Has"],
        answerIndex: 2,
        explanation: "be going to の疑問文は be動詞を文の最初に出します。主語が she なので Is she going to 〜? です。",
        choiceHints: ["Does のあとに going to は続きません。be動詞の Is を前に出します。","Will を使うなら going to はいりません（Will she visit 〜?）。ここは Is です。",null,"Has は現在完了で使う形です。be going to の疑問文は Is で始めます。"],
      },
      {
        id: "j2fe-future-6",
        question: "I'm going to ___ my homework after dinner.（私は夕食のあとに宿題をするつもりです）",
        choices: ["do","did","doing","does"],
        answerIndex: 0,
        explanation: "be going to のあとは必ず動詞の原形です。「する」は do をそのまま使います。",
        choiceHints: [null,"did は過去形です。going to のあとは原形 do にします。","going to のあとは -ing 形ではなく原形です。","does は三人称単数のときの現在形です。going to のあとは原形 do です。"],
      },
      {
        id: "j2fe-future-7",
        question: "My sister will be thirteen years old ___.（私の妹は来年13歳になります）",
        choices: ["last year","two years ago","the other day","next year"],
        answerIndex: 3,
        explanation: "will はこれからのことを表すので、未来を表す語句 next year（来年）がぴったりです。",
        choiceHints: ["last year は「去年」で過去を表します。will とはいっしょに使えません。","two years ago は「2年前」で過去のことです。","the other day は「先日」で過去のことです。",null],
      },
      {
        id: "j2fe-future-8",
        question: "「私は今度の日曜日、友だちと買い物に行く予定です」を表す英文はどれ？",
        choices: ["I am going to go shopping with my friend next Sunday.","I am going to shopping with my friend next Sunday.","I will going to go shopping with my friend next Sunday.","I am go to go shopping with my friend next Sunday."],
        answerIndex: 0,
        explanation: "前から決めている予定は be going to で表します。going to のあとは動詞の原形なので go shopping になります。",
        choiceHints: [null,"going to のあとは動詞の原形です。shopping ではなく go shopping にします。","will と be going to をいっしょに使うことはできません。","be動詞 am のあとにいきなり原形 go は置けません。am going to の形にします。"],
      },
    ],
  },
  {
    id: "j2fe-infinitive-basic",
    subject: "english",
    grade: "中2",
    title: "不定詞の基本（to + 動詞の原形）",
    lesson: "〈to + 動詞の原形〉を不定詞といいます。使い方は大きく3つです。「〜すること」（名詞的用法：I want to be 〜 / My dream is to 〜）、「〜するために」（副詞的用法：I went there to see 〜）、「〜するための・〜すべき」（形容詞的用法：something to eat / homework to do）。to のあとの動詞は、主語が何でも、時がいつでも、いつも原形のままです。",
    items: [
      {
        id: "j2fe-infinitive-basic-1",
        question: "I want ___ a doctor in the future.（私は将来、医者になりたい）",
        choices: ["be","being","to be","was"],
        answerIndex: 2,
        explanation: "want to + 動詞の原形で「〜したい」という意味になります。want to be で「〜になりたい」です。",
        choiceHints: ["want のあとに動詞の原形だけは置けません。to be の形にします。","want のあとに -ing 形は使いません。want to be が正しい形です。",null,"was は過去形です。want to be の形にします。"],
      },
      {
        id: "j2fe-infinitive-basic-2",
        question: "She likes ___ books in the library.（彼女は図書館で本を読むのが好きです）",
        choices: ["to read","to reads","to reading","read"],
        answerIndex: 0,
        explanation: "like to + 動詞の原形で「〜するのが好きだ」となります。to のあとは主語に関係なく原形です。",
        choiceHints: [null,"to のあとの動詞に s はつきません。to read にします。","to のあとは原形です。to reading とは言いません。","likes のすぐあとに原形は置けません。to read の形にします。"],
      },
      {
        id: "j2fe-infinitive-basic-3",
        question: "He went to the stadium ___ the soccer game.（彼はサッカーの試合を見るためにスタジアムへ行った）",
        choices: ["see","seeing","saw","to see"],
        answerIndex: 3,
        explanation: "「〜するために」と目的を表すときは〈to + 動詞の原形〉を使います。",
        choiceHints: ["1つの文に動詞をそのまま2つ並べることはできません。to see にします。","-ing 形だけでは「〜するために」の意味になりません。","過去形は使いません。目的を表すのは to see です。",null],
      },
      {
        id: "j2fe-infinitive-basic-4",
        question: "I'm glad ___ you again.（またあなたに会えてうれしいです）",
        choices: ["meet","to meet","meeting","met"],
        answerIndex: 1,
        explanation: "be glad to + 動詞の原形で「〜してうれしい」と、気持ちの理由を表します。",
        choiceHints: ["glad のあとに動詞の原形だけは置けません。to meet にします。",null,"気持ちの理由を表すときは glad to meet の形を使います。","met は過去形です。to meet にします。"],
      },
      {
        id: "j2fe-infinitive-basic-5",
        question: "I want something ___.（私は何か飲むものがほしい）",
        choices: ["drink","drinking","to drink","for drink"],
        answerIndex: 2,
        explanation: "something のうしろに〈to + 動詞の原形〉を置くと「〜するためのもの」という意味になります。",
        choiceHints: ["something のあとに動詞の原形をそのまま置くことはできません。to drink にします。","-ing 形ではなく to + 原形で「〜するための」を表します。",null,"for のあとに動詞の原形は置けません。something to drink が正しい形です。"],
      },
      {
        id: "j2fe-infinitive-basic-6",
        question: "We have a lot of homework ___ today.（今日はやるべき宿題がたくさんある）",
        choices: ["to do","doing","do","to doing"],
        answerIndex: 0,
        explanation: "名詞のうしろに〈to + 動詞の原形〉を置くと「〜すべき・〜するための」と名詞を説明できます。",
        choiceHints: [null,"-ing 形ではなく to + 原形で「〜すべき」を表します。","名詞のあとに動詞の原形だけは置けません。to do にします。","to のあとは原形です。to do にします。"],
      },
      {
        id: "j2fe-infinitive-basic-7",
        question: "「彼女は写真をとるために公園へ行きました」を表す英文はどれ？",
        choices: ["She went to the park took pictures.","She went to the park for take pictures.","She went to the park to took pictures.","She went to the park to take pictures."],
        answerIndex: 3,
        explanation: "「〜するために」という目的は〈to + 動詞の原形〉で表します。went のあとに to take pictures を続けます。",
        choiceHints: ["動詞を2つそのまま続けることはできません。「〜するために」は to + 原形です。","for のあとに動詞の原形は置けません。to take にします。","to のあとは動詞の原形です。took ではなく take にします。",null],
      },
      {
        id: "j2fe-infinitive-basic-8",
        question: "My dream is ___ around the world.（私の夢は世界中を旅することです）",
        choices: ["travel","to travel","travels","traveled"],
        answerIndex: 1,
        explanation: "be動詞のあとに〈to + 動詞の原形〉を置くと「〜することです」という意味になります。",
        choiceHints: ["be動詞のあとに動詞の原形をそのまま置くことはできません。to travel にします。",null,"travels は三人称単数のときの現在形です。ここは to travel です。","traveled は過去形です。「〜すること」は to travel で表します。"],
      },
    ],
  },
  {
    id: "j2fe-comparative",
    subject: "english",
    grade: "中2",
    title: "比較（比較級・最上級）",
    lesson: "2つをくらべるときは比較級（語尾に -er、または前に more）を使い、than 〜（〜よりも）を続けます。3つ以上の中でいちばんというときは最上級（語尾に -est、または前に most）を使い、the をつけて in 〜（場所や範囲）や of 〜（なかまの数）を続けます。同じくらいのときは as 〜 as でもとの形（原級）をはさみます。good / well は better - best と特別に変化します。",
    items: [
      {
        id: "j2fe-comparative-1",
        question: "This tower is ___ than that one.（このタワーはあのタワーより高い）",
        choices: ["taller","tall","tallest","more tall"],
        answerIndex: 0,
        explanation: "than があるので比較級にします。tall は短い語なので語尾に -er をつけて taller です。",
        choiceHints: [null,"than があるので、もとの形ではなく比較級 taller にします。","最上級 tallest は the をつけて使い、than とはいっしょに使いません。","tall は短い語なので more はつけず、-er をつけて taller にします。"],
      },
      {
        id: "j2fe-comparative-2",
        question: "This book is ___ interesting than that one.（この本はあの本よりおもしろい）",
        choices: ["much","most","more","very"],
        answerIndex: 2,
        explanation: "interesting のように長い語は、-er をつけずに前に more を置いて比較級にします。",
        choiceHints: ["much だけでは比較級になりません。more interesting than 〜 とします。","most は最上級で使います。than があるので more にします。",null,"very は比較には使えません。more interesting than 〜 とします。"],
      },
      {
        id: "j2fe-comparative-3",
        question: "Mt. Fuji is the ___ mountain in Japan.（富士山は日本でいちばん高い山です）",
        choices: ["higher","highest","high","most high"],
        answerIndex: 1,
        explanation: "the と in Japan があるので「いちばん〜」を表す最上級にします。high は短い語なので -est をつけます。",
        choiceHints: ["higher は2つをくらべる比較級です。「いちばん」は highest にします。",null,"もとの形のままでは「いちばん高い」を表せません。","high は短い語なので most ではなく -est をつけて highest にします。"],
      },
      {
        id: "j2fe-comparative-4",
        question: "Ken can run ___ of the five boys.（ケンは5人の男の子の中でいちばん速く走れる）",
        choices: ["faster","fast","more fast","the fastest"],
        answerIndex: 3,
        explanation: "of the five boys（5人の中で）があるので最上級です。fast は -est をつけて fastest になります。",
        choiceHints: ["faster は2つをくらべる形です。5人の中でいちばん、なので最上級にします。","fast のままでは「いちばん速く」を表せません。","fast は -er / -est をつける語なので more は使いません。",null],
      },
      {
        id: "j2fe-comparative-5",
        question: "This is the longest river ___ Japan.（これは日本でいちばん長い川です）",
        choices: ["in","of","on","for"],
        answerIndex: 0,
        explanation: "最上級のあとに場所や範囲を続けるときは in を使います（in Japan / in my class）。",
        choiceHints: [null,"of は of the three のように、なかまの数や集まりに使います。国や場所には in です。","on は「〜の上に」という意味で、範囲を表すときには使いません。","for は「〜のために」などの意味です。範囲は in Japan とします。"],
      },
      {
        id: "j2fe-comparative-6",
        question: "Tom is as ___ as his father.（トムはお父さんと同じくらい背が高い）",
        choices: ["taller","tallest","tall","more tall"],
        answerIndex: 2,
        explanation: "as 〜 as は「同じくらい〜」という意味で、間にはもとの形（原級）を入れます。",
        choiceHints: ["as 〜 as の間は比較級ではなく、もとの形を入れます。","as 〜 as の間に最上級は入れません。as tall as とします。",null,"more はつけません。as tall as が正しい形です。"],
      },
      {
        id: "j2fe-comparative-7",
        question: "This question is ___ than that one.（この問題はあの問題よりやさしい）",
        choices: ["easyer","easier","more easy","easiest"],
        answerIndex: 1,
        explanation: "〈子音字 + y〉で終わる語は y を i に変えて -er をつけます。easy → easier です。",
        choiceHints: ["y をそのまま残しません。y を i に変えて easier とします。",null,"easy は -er をつける語なので more は使いません。","easiest は最上級で、than とはいっしょに使いません。"],
      },
      {
        id: "j2fe-comparative-8",
        question: "I like summer, but I like winter ___.（夏も好きですが、冬のほうがもっと好きです）",
        choices: ["gooder","well","best","better"],
        answerIndex: 3,
        explanation: "good / well の比較級は better です。2つをくらべて「〜のほうが好き」というときは like 〜 better を使います。",
        choiceHints: ["good に -er はつけません。比較級は better です。","well は「じょうずに」という意味です。ここは「より好き」なので better にします。","best は3つ以上の中でいちばんのときに使います。夏と冬の2つなので better です。",null],
      },
    ],
  },
  {
    id: "j2fe-svoo",
    subject: "english",
    grade: "中2",
    title: "SVOO（give/show/tell + 人 + 物）",
    lesson: "give, show, tell, send, teach などは〈動詞 + 人 + 物〉の順で「（人）に（物）を〜する」という文を作れます。He gave me a book. のように、人が先、物があとです。この文は〈動詞 + 物 + to + 人〉に書きかえられます（He gave a book to me.）。ただし make, buy, cook などは to ではなく for を使います。",
    items: [
      {
        id: "j2fe-svoo-1",
        question: "Please show ___.（私にあなたの写真を見せてください）",
        choices: ["your pictures me","me your pictures","to me your pictures","me to your pictures"],
        answerIndex: 1,
        explanation: "〈show + 人 + 物〉の順です。人（me）を先に、物（your pictures）をあとに置きます。",
        choiceHints: ["「人 → 物」の順にします。show me your pictures が正しい形です。",null,"〈show + 人 + 物〉のときは to をつけません。","to を使うのは〈物 + to + 人〉の形のときです。ここは show me your pictures です。"],
      },
      {
        id: "j2fe-svoo-2",
        question: "She ___ us an interesting story yesterday.（彼女は昨日、私たちにおもしろい話をしてくれた）",
        choices: ["said","spoke","talked","told"],
        answerIndex: 3,
        explanation: "「（人）に（話）を話す」は〈tell + 人 + 物〉で表します。過去形は told です。",
        choiceHints: ["say はすぐあとに人を置けません。said to us のような形になります。","speak は spoke to us のように to をつけて使います。","talk も talked to us のように to をつけて使います。",null],
      },
      {
        id: "j2fe-svoo-3",
        question: "Mr. Brown ___ us English.（ブラウン先生は私たちに英語を教えています）",
        choices: ["teaches","learns","studies","says"],
        answerIndex: 0,
        explanation: "〈teach + 人 + 物〉で「（人）に（教科など）を教える」という意味になります。",
        choiceHints: [null,"learn は「習う・身につける」で、教わる側が使う語です。教えるのは teach です。","study は「勉強する」で、人に教える意味にはなりません。","say はこの〈人 + 物〉の形では使えません。"],
      },
      {
        id: "j2fe-svoo-4",
        question: "I gave a present to my sister. ＝ I gave ___.（私は妹にプレゼントをあげた）",
        choices: ["a present my sister","my sister to a present","my sister a present","to my sister a present"],
        answerIndex: 2,
        explanation: "〈give + 物 + to + 人〉は〈give + 人 + 物〉に書きかえられます。to をとって人を先に置きます。",
        choiceHints: ["この形にするときは「人 → 物」の順です。my sister a present とします。","to の位置がちがいます。give + 人 + 物の形では to は使いません。",null,"人を先に置くときは to はいりません。"],
      },
      {
        id: "j2fe-svoo-5",
        question: "My mother made me a cake. ＝ My mother made a cake ___ me.（母は私にケーキを作ってくれた）",
        choices: ["to","for","of","with"],
        answerIndex: 1,
        explanation: "make, buy, cook などを書きかえるときは to ではなく for を使います。give や show は to です。",
        choiceHints: ["to を使うのは give や show, tell などです。make のときは for にします。",null,"of はこの書きかえには使いません。","with は「〜といっしょに」という意味です。ここは for me とします。"],
      },
      {
        id: "j2fe-svoo-6",
        question: "Could you ___ me the way to the station?（駅への道を教えてくれませんか）",
        choices: ["teach","say","speak","tell"],
        answerIndex: 3,
        explanation: "道や名前、時間などの情報を「教える」ときは tell を使います。〈tell + 人 + 物〉の形です。",
        choiceHints: ["teach は勉強や技術をじっくり教えるときに使います。道案内は tell です。","say は〈人 + 物〉の形をとれません。","speak はこの形では使えません。speak to me のように使います。",null],
      },
      {
        id: "j2fe-svoo-7",
        question: "I sent ___ last week.（私は先週、彼女にEメールを送った）",
        choices: ["her an e-mail","an e-mail her","to her an e-mail","her to an e-mail"],
        answerIndex: 0,
        explanation: "〈send + 人 + 物〉の順です。人（her）が先、物（an e-mail）があとになります。",
        choiceHints: [null,"「人 → 物」の順です。her an e-mail とします。","人を先に置くときは to はいりません。","to の位置がちがいます。send her an e-mail が正しい形です。"],
      },
      {
        id: "j2fe-svoo-8",
        question: "「彼は私たちに彼の新しい自転車を見せてくれた」を表す英文はどれ？",
        choices: ["He showed his new bike us.","He showed to us his new bike.","He showed us his new bike.","He showed us to his new bike."],
        answerIndex: 2,
        explanation: "〈show + 人 + 物〉の順で、He showed us his new bike. となります。",
        choiceHints: ["物のあとに人をそのまま置くことはできません。人（us）を先にします。","to を使うなら showed his new bike to us の順にします。",null,"人を先に置くときは to はいりません。"],
      },
    ],
  },
  {
    id: "j2fe-conjunction",
    subject: "english",
    grade: "中2",
    title: "接続詞（when / if / because / that）",
    lesson: "2つの文をつなぐことばを接続詞といいます。when は「〜するとき」、if は「もし〜なら」、because は「〜なので（理由）」を表します。that は「〜ということ」で、I think that 〜. のように使います（that は省略できます）。when や if を文の最初に置くときは、前半のあとにコンマ（,）を入れます。また if や when のまとまりの中では、未来のことでも現在形を使います。",
    items: [
      {
        id: "j2fe-conjunction-1",
        question: "___ I got home, my mother was cooking dinner.（私が家に着いたとき、母は夕食を作っていた）",
        choices: ["If","Because","That","When"],
        answerIndex: 3,
        explanation: "「〜するとき」と時を表すのは when です。文の最初に置いたので、そのあとにコンマがついています。",
        choiceHints: ["If は「もし〜なら」という意味です。時を表すのは When です。","Because は「〜なので」と理由を表します。ここは時を表す When です。","That はこの位置で「〜するとき」を表すことはできません。",null],
      },
      {
        id: "j2fe-conjunction-2",
        question: "___ it rains tomorrow, we will stay home.（もし明日雨が降ったら、私たちは家にいます）",
        choices: ["When","If","Because","That"],
        answerIndex: 1,
        explanation: "「もし〜なら」と条件を表すのは if です。日本語の「もし」に注目しましょう。",
        choiceHints: ["When は「〜するとき」で、起こることが決まっている場合に使います。「もし」は If です。",null,"Because は理由を表します。「もし〜なら」は If です。","That は「〜ということ」で、条件を表すことはできません。"],
      },
      {
        id: "j2fe-conjunction-3",
        question: "I was very happy ___ I got a letter from him.（彼から手紙をもらったので、私はとてもうれしかった）",
        choices: ["if","so","because","but"],
        answerIndex: 2,
        explanation: "「〜なので」と理由を表すのは because です。うれしかった理由をあとに続けています。",
        choiceHints: ["if は「もし〜なら」という条件を表します。理由は because です。","so は「だから」で、結果を後ろに続けます。ここは理由が後ろに来るので because です。",null,"but は「しかし」と反対のことをつなぎます。理由は because です。"],
      },
      {
        id: "j2fe-conjunction-4",
        question: "I think ___ this book is very useful.（私はこの本はとても役に立つと思います）",
        choices: ["that","if","because","when"],
        answerIndex: 0,
        explanation: "think のあとに「〜ということ」を続けるときは that を使います。この that は省略もできます。",
        choiceHints: [null,"if は「もし〜なら」です。「〜だと思う」は think that 〜 です。","because は理由を表します。ここは「〜ということ」なので that です。","when は「〜するとき」です。think のあとには that を使います。"],
      },
      {
        id: "j2fe-conjunction-5",
        question: "If it ___ sunny tomorrow, we will go hiking.（もし明日晴れたら、私たちはハイキングに行きます）",
        choices: ["will be","is going to be","will","is"],
        answerIndex: 3,
        explanation: "if や when のまとまりの中では、未来のことでも現在形を使います。主語が it なので is です。",
        choiceHints: ["if のまとまりの中では will を使いません。現在形 is にします。","be going to もここでは使いません。現在形 is にします。","will だけでは文になりません。if のあとは現在形 is を使います。",null],
      },
      {
        id: "j2fe-conjunction-6",
        question: "Please call me ___ you arrive at the station.（駅に着いたら、私に電話してください）",
        choices: ["because","when","that","but"],
        answerIndex: 1,
        explanation: "「〜したら（〜するとき）」と時を表すので when を使います。",
        choiceHints: ["because は理由を表します。「〜したら」は when です。",null,"that は「〜ということ」で、時を表すことはできません。","but は「しかし」です。時を表すのは when です。"],
      },
      {
        id: "j2fe-conjunction-7",
        question: "「私が部屋に入ったとき、ケンは音楽を聞いていました」を表す英文はどれ？",
        choices: ["When, I entered the room Ken was listening to music.","I entered the room, when Ken was listening to music.","When I entered the room, Ken was listening to music.","When I entered the room Ken, was listening to music."],
        answerIndex: 2,
        explanation: "When を文の最初に置くときは〈When + 主語 + 動詞, 主語 + 動詞 〜.〉の形にし、前半の終わりにコンマを入れます。",
        choiceHints: ["コンマは When のすぐあとではなく、前半の文の終わりに置きます。","この形では when が「ケンが音楽を聞いていた」のほうにつき、意味がずれてしまいます。",null,"コンマの位置がちがいます。主語 Ken の前で区切ります。"],
      },
      {
        id: "j2fe-conjunction-8",
        question: "「私は彼女が正しいと思います」を表す英文はどれ？",
        choices: ["I think that she is right.","I think that she right.","I think she that is right.","I think because she is right."],
        answerIndex: 0,
        explanation: "think that のあとには〈主語 + 動詞〉が続きます。I think that she is right. となります。",
        choiceHints: [null,"that のあとにも〈主語 + 動詞〉が必要です。she is right とします。","that は she の前に置きます。I think that she is right. が正しい形です。","because は理由を表します。「〜だと思う」は think that を使います。"],
      },
    ],
  },
];
