// 中学1年 英語（中1）の問題バンク（english_j1）。
// サブエージェントが作問し、別エージェントで文法監査した authored 確定データ。
// 生成AIは出題・採点・解説に使わない（採点は engine が answerIndex 比較）。
import type { QuizUnit } from "@/lib/quiz/types";

export const ENGLISH_UNITS_J1: QuizUnit[] = [
  {
    id: "j1e-be-verb",
    subject: "english",
    grade: "中1",
    title: "be動詞",
    lesson: "「〜です」「〜にいます」を表すのが be動詞です。主語によって形が変わり、I には am、he・she・it など1人（1つ）には is、you や複数には are を使います。否定文は be動詞のあとに not を置き、am not / isn't / aren't とします。疑問文は be動詞を主語の前に出して Am / Is / Are 〜? の形にします。",
    items: [
      {
        id: "j1e-be-verb-1",
        question: "I ___ from Japan.（私は日本の出身です）",
        choices: ["am","is","are","be"],
        answerIndex: 0,
        explanation: "主語が I のときの be動詞は am です。I am from Japan. となります。",
        choiceHints: [null,"is は he や she など1人（1つ）の主語に使います。主語 I には am を使います。","are は you や複数の主語に使います。主語 I には am を使います。","be はもとの形（原形）です。主語 I のときは am に形を変えます。"],
      },
      {
        id: "j1e-be-verb-2",
        question: "Ms. Brown ___ our English teacher.（ブラウン先生は私たちの英語の先生です）",
        choices: ["am","are","is","do"],
        answerIndex: 2,
        explanation: "主語が Ms. Brown（1人）なので be動詞は is を使います。",
        choiceHints: ["am は主語が I のときだけに使います。Ms. Brown には is を使います。","are は you や複数の主語に使います。1人の Ms. Brown には is を使います。",null,"do は一般動詞の疑問文や否定文に使う語です。「〜です」を表すのは be動詞の is です。"],
      },
      {
        id: "j1e-be-verb-3",
        question: "These ___ my new shoes.（これらは私の新しいくつです）",
        choices: ["is","are","am","be"],
        answerIndex: 1,
        explanation: "These（これらは）は複数の主語なので、be動詞は are を使います。1つのときは This is 〜、2つ以上のときは These are 〜 です。",
        choiceHints: ["is は1人（1つ）の主語に使います。These は複数なので are です。",null,"am は主語が I のときだけに使います。These には are を使います。","be はもとの形（原形）です。These が主語のときは are にします。"],
      },
      {
        id: "j1e-be-verb-4",
        question: "He ___ a soccer fan.（彼はサッカーファンではありません）",
        choices: ["am not","aren't","don't","isn't"],
        answerIndex: 3,
        explanation: "主語 He の be動詞は is なので、否定は is not を縮めた isn't になります。",
        choiceHints: ["am not は主語が I のときの形です。He には isn't を使います。","aren't は you や複数の主語のときの形です。He には isn't を使います。","don't は一般動詞の否定に使います。「〜ではありません」は be動詞の isn't です。",null],
      },
      {
        id: "j1e-be-verb-5",
        question: "「あなたは日本の出身ですか」を表す英文はどれ？",
        choices: ["Are you from Japan?","Is you from Japan?","Do you are from Japan?","You are from Japan."],
        answerIndex: 0,
        explanation: "be動詞の疑問文は be動詞を主語の前に出します。主語 you の be動詞は are なので Are you from Japan? となります。",
        choiceHints: [null,"主語 you には is ではなく are を使います。Are you 〜? が正しい形です。","be動詞の疑問文に Do は使いません。are を前に出して Are you 〜? とします。","ふつうの語順のままでは疑問文になりません。are を you の前に出します。"],
      },
      {
        id: "j1e-be-verb-6",
        question: "___ that your bag?（あれはあなたのかばんですか）",
        choices: ["Are","Am","Is","Do"],
        answerIndex: 2,
        explanation: "主語 that（あれ）は1つのものなので be動詞は is です。疑問文なので Is を文の最初に置きます。",
        choiceHints: ["Are は you や複数の主語に使います。1つを指す that には Is を使います。","Am は主語が I のときだけに使います。that には Is を使います。",null,"Do は一般動詞の疑問文に使います。「〜ですか」は be動詞の Is で始めます。"],
      },
      {
        id: "j1e-be-verb-7",
        question: "I ___ hungry now.（私は今、おなかがすいていません）",
        choices: ["isn't","am not","aren't","don't"],
        answerIndex: 1,
        explanation: "主語 I の be動詞は am です。否定は am not とします。am not に短縮形はありません。",
        choiceHints: ["isn't は he や she など1人（1つ）の主語に使います。I には am not です。",null,"aren't は you や複数の主語に使います。I には am not です。","don't は一般動詞の否定に使います。hungry は動詞ではないので am not を使います。"],
      },
      {
        id: "j1e-be-verb-8",
        question: "「これらは私の犬ではありません」を表す英文はどれ？",
        choices: ["These is not my dogs.","This are not my dogs.","These not are my dogs.","These are not my dogs."],
        answerIndex: 3,
        explanation: "These は複数なので be動詞は are です。否定は are のあとに not を置いて These are not my dogs. となります。",
        choiceHints: ["These は複数なので is ではなく are を使います。","This は1つを指す語です。複数の dogs に合わせて These are 〜 とします。","not は be動詞のあとに置きます。are not の順にします。",null],
      },
    ],
  },
  {
    id: "j1e-general-verb",
    subject: "english",
    grade: "中1",
    title: "一般動詞",
    lesson: "play, go, study のように動作や状態を表す語を一般動詞といいます。主語が he・she・it など1人（1つ）のときは、動詞の終わりに s や es をつけます（go→goes、study→studies）。疑問文は Do / Does を文の最初に置き、否定文は don't / doesn't を動詞の前に置きます。Do や Does を使うとき、そのあとの動詞は s のつかないもとの形にもどします。",
    items: [
      {
        id: "j1e-general-verb-1",
        question: "I ___ tennis every Sunday.（私は毎週日曜日にテニスをします）",
        choices: ["plays","play","playing","am play"],
        answerIndex: 1,
        explanation: "主語が I のときは、動詞に s をつけずそのままの形 play を使います。",
        choiceHints: ["plays は he や she など1人（1つ）の主語のときの形です。I には play を使います。",null,"playing は -ing 形です。この形だけでは文の動詞になれません。play を使います。","be動詞と一般動詞をならべては使えません。ここは play だけで正しい文になります。"],
      },
      {
        id: "j1e-general-verb-2",
        question: "My brother ___ to school by bus.（兄はバスで学校へ行きます）",
        choices: ["go","going","gos","goes"],
        answerIndex: 3,
        explanation: "主語 My brother は1人なので動詞に es をつけます。go は s ではなく es をつけて goes になります。",
        choiceHints: ["主語が1人なので s や es が必要です。go ではなく goes にします。","going は -ing 形です。この形だけでは文の動詞になれません。goes を使います。","go は o で終わるので s ではなく es をつけます。gos ではなく goes です。",null],
      },
      {
        id: "j1e-general-verb-3",
        question: "She ___ English every day.（彼女は毎日英語を勉強します）",
        choices: ["studies","studys","study","studing"],
        answerIndex: 0,
        explanation: "主語 She は1人なので動詞に s をつけます。study は〈子音字＋y〉で終わるので、y を i に変えて es をつけ studies になります。",
        choiceHints: [null,"study の y はそのままにせず、i に変えて es をつけます。studies が正しい形です。","主語が1人なので s が必要です。study ではなく studies にします。","studing という語はありません。ここは studies を使います。"],
      },
      {
        id: "j1e-general-verb-4",
        question: "___ you like music?（あなたは音楽が好きですか）",
        choices: ["Are","Does","Do","Is"],
        answerIndex: 2,
        explanation: "一般動詞 like の疑問文なので Do を文の最初に置きます。主語 you には Do を使います。",
        choiceHints: ["Are は be動詞です。あとに一般動詞 like があるので Do を使います。","Does は he や she など1人（1つ）の主語に使います。you には Do です。",null,"Is は be動詞で、主語も you には合いません。ここは Do you 〜? です。"],
      },
      {
        id: "j1e-general-verb-5",
        question: "___ your father play golf?（あなたのお父さんはゴルフをしますか）",
        choices: ["Do","Does","Is","Are"],
        answerIndex: 1,
        explanation: "主語 your father は1人なので、一般動詞の疑問文では Does を使います。Does のあとの動詞は play のままです。",
        choiceHints: ["主語が1人（your father）なので Do ではなく Does を使います。",null,"Is は be動詞です。あとに一般動詞 play があるので Does を使います。","Are は be動詞で、主語も1人には合いません。ここは Does です。"],
      },
      {
        id: "j1e-general-verb-6",
        question: "Tom ___ have a cat.（トムはねこを飼っていません）",
        choices: ["don't","isn't","not","doesn't"],
        answerIndex: 3,
        explanation: "主語 Tom は1人なので、一般動詞の否定文は doesn't を使います。doesn't のあとの動詞は have のままです。",
        choiceHints: ["主語が1人（Tom）なので don't ではなく doesn't を使います。","isn't は be動詞の否定です。一般動詞 have の否定には doesn't を使います。","not だけでは否定文になりません。doesn't have とします。",null],
      },
      {
        id: "j1e-general-verb-7",
        question: "We ___ watch TV in the morning.（私たちは朝にテレビを見ません）",
        choices: ["don't","doesn't","aren't","isn't"],
        answerIndex: 0,
        explanation: "主語 We は複数なので、一般動詞の否定文は don't を使います。don't watch で「見ません」を表します。",
        choiceHints: [null,"doesn't は1人（1つ）の主語に使います。複数の We には don't です。","aren't は be動詞の否定です。一般動詞 watch の否定には don't を使います。","isn't は be動詞の否定で、主語も We には合いません。ここは don't です。"],
      },
      {
        id: "j1e-general-verb-8",
        question: "Does Yuki ___ the piano?（ユキはピアノをひきますか）",
        choices: ["plays","playing","play","played"],
        answerIndex: 2,
        explanation: "Does を使った疑問文では、そのあとの動詞は s のつかないもとの形にします。Does Yuki play 〜? となります。",
        choiceHints: ["Does があるので動詞に s はつけません。plays ではなく play です。","playing は -ing 形です。Does のあとはもとの形 play にします。",null,"played は過去の形です。Does のあとはもとの形 play にします。"],
      },
    ],
  },
  {
    id: "j1e-plural",
    subject: "english",
    grade: "中1",
    title: "名詞の複数形",
    lesson: "「2つ以上」を表すとき、名詞は複数形になります。ふつうは s をつけ（cat→cats）、s・x・ch・sh で終わる語は es をつけます（box→boxes、watch→watches）。〈子音字＋y〉で終わる語は y を i に変えて es をつけます（country→countries）。child→children、man→men のように形が変わる語もあります。1つのときは前に a をつけ、母音の音で始まる語には an をつけます。milk や water のように数えられない名詞は s をつけません。",
    items: [
      {
        id: "j1e-plural-1",
        question: "I have two ___.（私はねこを2匹飼っています）",
        choices: ["cat","cates","cats","cat's"],
        answerIndex: 2,
        explanation: "two（2匹）なので複数形にします。cat はふつうに s をつけて cats になります。",
        choiceHints: ["two があるので複数形にします。cat ではなく cats です。","cat に es はつけません。s だけをつけて cats にします。",null,"cat's は「ねこの」という意味の形です。「2匹のねこ」は cats です。"],
      },
      {
        id: "j1e-plural-2",
        question: "We have three ___ in our house.（私たちの家には箱が3つあります）",
        choices: ["boxes","boxs","box","boxies"],
        answerIndex: 0,
        explanation: "box は x で終わるので、複数形は es をつけて boxes になります。",
        choiceHints: [null,"x で終わる語は s ではなく es をつけます。boxs ではなく boxes です。","three があるので複数形にします。box ではなく boxes です。","y で終わる語ではないので ies にはしません。boxes が正しい形です。"],
      },
      {
        id: "j1e-plural-3",
        question: "Japan and China are ___ in Asia.（日本と中国はアジアの国です）",
        choices: ["countrys","countryes","country","countries"],
        answerIndex: 3,
        explanation: "country は〈子音字＋y〉で終わるので、y を i に変えて es をつけ countries になります。",
        choiceHints: ["y をそのままにして s はつけません。y を i に変えて countries にします。","y をそのままにして es はつけません。countries が正しい形です。","2つの国のことなので複数形にします。country ではなく countries です。",null],
      },
      {
        id: "j1e-plural-4",
        question: "Three ___ are playing in the park.（3人の子どもが公園で遊んでいます）",
        choices: ["childs","children","childrens","childes"],
        answerIndex: 1,
        explanation: "child は形が変わる名詞で、複数形は children です。s はつけません。",
        choiceHints: ["child に s はつけません。複数形は children です。",null,"children がもう複数形なので、さらに s はつけません。","child に es はつけません。複数形は children です。"],
      },
      {
        id: "j1e-plural-5",
        question: "Two ___ are waiting at the door.（2人の男の人がドアのところで待っています）",
        choices: ["mans","mens","men","manes"],
        answerIndex: 2,
        explanation: "man は形が変わる名詞で、複数形は men です。s はつけません。",
        choiceHints: ["man に s はつけません。複数形は men です。","men がもう複数形なので、さらに s はつけません。",null,"man に es はつけません。複数形は men です。"],
      },
      {
        id: "j1e-plural-6",
        question: "a と an の使い方が正しい英文はどれ？",
        choices: ["He has an umbrella.","I have an dog.","She is a old woman.","It is a apple."],
        answerIndex: 0,
        explanation: "a・e・i・o・u の音で始まる語の前では a ではなく an を使います。umbrella は u の音で始まるので an umbrella が正しい形です。",
        choiceHints: [null,"dog は d の音で始まるので an ではなく a を使います。a dog が正しい形です。","old は o の音で始まるので a ではなく an を使います。an old woman です。","apple は a の音で始まるので a ではなく an を使います。an apple です。"],
      },
      {
        id: "j1e-plural-7",
        question: "I drink ___ every morning.（私は毎朝牛乳を飲みます）",
        choices: ["a milk","milks","two milk","milk"],
        answerIndex: 3,
        explanation: "milk は数えられない名詞です。a をつけたり s をつけたりせず、そのまま milk と言います。",
        choiceHints: ["数えられない名詞には a をつけません。そのまま milk とします。","数えられない名詞には s をつけません。milk のままにします。","数えられない名詞は two のような数をつけて数えません。milk とします。",null],
      },
      {
        id: "j1e-plural-8",
        question: "He has two ___.（彼は腕時計を2つ持っています）",
        choices: ["watchs","watches","watch","watchies"],
        answerIndex: 1,
        explanation: "watch は ch で終わるので、複数形は es をつけて watches になります。",
        choiceHints: ["ch で終わる語は s ではなく es をつけます。watchs ではなく watches です。",null,"two があるので複数形にします。watch ではなく watches です。","y で終わる語ではないので ies にはしません。watches が正しい形です。"],
      },
    ],
  },
  {
    id: "j1e-pronoun",
    subject: "english",
    grade: "中1",
    title: "代名詞",
    lesson: "名前のかわりに使う語を代名詞といいます。使う場所によって形が変わり、「〜は」は I・he・they、「〜の」は my・his・their、「〜を・〜に」は me・him・them となります。「私のもの」「あなたのもの」のように1語で持ち主を表す語もあり、mine・yours・his・theirs といいます。所有代名詞のあとには名詞をつけません。",
    items: [
      {
        id: "j1e-pronoun-1",
        question: "This is my brother. ___ is a high school student.（こちらは私の兄です。彼は高校生です）",
        choices: ["Him","His","Them","He"],
        answerIndex: 3,
        explanation: "「彼は」と主語になるときは He を使います。my brother を言いかえた主語なので He is 〜 となります。",
        choiceHints: ["Him は「彼を・彼に」の形で、主語には使えません。主語は He です。","His は「彼の」の形です。主語になるのは He です。","Them は「彼らを・彼らに」の形です。1人の兄を指す主語は He です。",null],
      },
      {
        id: "j1e-pronoun-2",
        question: "I have a cat. I love ___ very much.（私はねこを飼っています。私はそのねこが大好きです）",
        choices: ["its","it","it's","they"],
        answerIndex: 1,
        explanation: "love のあとに来る「〜を」の形が必要です。a cat を言いかえた目的語なので it を使います。",
        choiceHints: ["its は「その〜の」という形で、あとに名詞が必要です。ここは it です。",null,"it's は it is を短くした形です。「それを」の意味にはなりません。it を使います。","they は「彼らは」で、しかも複数を指します。1匹のねこを指す目的語は it です。"],
      },
      {
        id: "j1e-pronoun-3",
        question: "That is ___ bike.（あれは彼の自転車です）",
        choices: ["his","he","him","he's"],
        answerIndex: 0,
        explanation: "あとに名詞 bike があるので「彼の」を表す his を使います。",
        choiceHints: [null,"he は「彼は」の形です。名詞の前に置いて「彼の」を表すのは his です。","him は「彼を・彼に」の形です。名詞の前では his を使います。","he's は he is を短くした形です。「彼の」は his です。"],
      },
      {
        id: "j1e-pronoun-4",
        question: "Emi likes Ken. She often calls ___ on the phone.（エミはケンが好きです。彼女はよく彼に電話します）",
        choices: ["he","his","him","he's"],
        answerIndex: 2,
        explanation: "calls のあとに来る「〜に」の形が必要です。Ken を言いかえた目的語なので him を使います。",
        choiceHints: ["he は「彼は」の形で、主語に使います。動詞のあとでは him です。","his は「彼の」の形で、あとに名詞が必要です。ここは him です。",null,"he's は he is を短くした形です。動詞のあとに置く形は him です。"],
      },
      {
        id: "j1e-pronoun-5",
        question: "___ name is Yuki.（私の名前はユキです）",
        choices: ["I","Me","Mine","My"],
        answerIndex: 3,
        explanation: "あとに名詞 name があるので「私の」を表す My を使います。",
        choiceHints: ["I は「私は」の形です。名詞の前で「私の」を表すのは My です。","Me は「私を・私に」の形です。名詞の前では My を使います。","Mine は「私のもの」で、あとに名詞をつけません。ここは My name です。",null],
      },
      {
        id: "j1e-pronoun-6",
        question: "This pen is ___.（このペンは私のものです）",
        choices: ["my","mine","me","I"],
        answerIndex: 1,
        explanation: "「私のもの」と1語で持ち主を表すときは mine を使います。my とちがい、あとに名詞をつけません。",
        choiceHints: ["my のあとには名詞が必要です。1語で「私のもの」を表すのは mine です。",null,"me は「私を・私に」の形です。「私のもの」は mine です。","I は「私は」の形です。「私のもの」は mine です。"],
      },
      {
        id: "j1e-pronoun-7",
        question: "Is this bag ___?（このかばんはあなたのものですか）",
        choices: ["yours","your","you","you're"],
        answerIndex: 0,
        explanation: "「あなたのもの」と1語で持ち主を表すときは yours を使います。",
        choiceHints: [null,"your のあとには名詞が必要です。1語で「あなたのもの」を表すのは yours です。","you は「あなたは・あなたを」の形です。「あなたのもの」は yours です。","you're は you are を短くした形です。「あなたのもの」は yours です。"],
      },
      {
        id: "j1e-pronoun-8",
        question: "Tom and Emi are my friends. I often play with ___.（トムとエミは私の友だちです。私はよく彼らといっしょに遊びます）",
        choices: ["they","their","them","theirs"],
        answerIndex: 2,
        explanation: "with のような語のあとは「〜を・〜に」の形にします。Tom and Emi を言いかえて them を使います。",
        choiceHints: ["they は「彼らは」の形で、主語に使います。with のあとでは them です。","their は「彼らの」の形で、あとに名詞が必要です。ここは them です。",null,"theirs は「彼らのもの」という意味です。「彼らと」は with them です。"],
      },
    ],
  },
  {
    id: "j1e-question-word",
    subject: "english",
    grade: "中1",
    title: "疑問詞",
    lesson: "「何」「だれ」「どこ」などをたずねるときに使う語を疑問詞といいます。what（何）、who（だれ）、where（どこ）、when（いつ）、how（どのように）、why（なぜ）などがあります。数をたずねるときは How many、ねだんや量をたずねるときは How much を使います。疑問詞はいつも文の最初に置き、そのあとは be動詞や Do / Does の疑問文の語順を続けます。",
    items: [
      {
        id: "j1e-question-word-1",
        question: "___ is that? — It's a camera.（あれは何ですか。— カメラです）",
        choices: ["What","Who","Where","When"],
        answerIndex: 0,
        explanation: "「何ですか」とものをたずねるときは What を使います。そのあとは be動詞の疑問文の語順で is that? と続けます。",
        choiceHints: [null,"Who は「だれ」と人をたずねる語です。ものをたずねるときは What です。","Where は「どこ」と場所をたずねる語です。ものをたずねるときは What です。","When は「いつ」と時をたずねる語です。ものをたずねるときは What です。"],
      },
      {
        id: "j1e-question-word-2",
        question: "___ is that tall boy? — He is Ken's brother.（あの背の高い男の子はだれですか。— ケンのお兄さんです）",
        choices: ["What","Where","Who","How"],
        answerIndex: 2,
        explanation: "「だれですか」と人をたずねるときは Who を使います。",
        choiceHints: ["What は「何」とものをたずねる語です。人をたずねるときは Who です。","Where は「どこ」と場所をたずねる語です。人をたずねるときは Who です。",null,"How は「どのように」と方法や様子をたずねる語です。人をたずねるなら Who です。"],
      },
      {
        id: "j1e-question-word-3",
        question: "___ do you live? — I live in Osaka.（あなたはどこに住んでいますか。— 大阪に住んでいます）",
        choices: ["When","Where","Who","What"],
        answerIndex: 1,
        explanation: "「どこに」と場所をたずねるときは Where を使います。そのあとは一般動詞の疑問文の語順で do you live? と続けます。",
        choiceHints: ["When は「いつ」と時をたずねる語です。場所をたずねるときは Where です。",null,"Who は「だれ」と人をたずねる語です。場所をたずねるときは Where です。","What は「何」とものをたずねる語です。場所をたずねるときは Where です。"],
      },
      {
        id: "j1e-question-word-4",
        question: "___ is your birthday? — It's May 5.（あなたの誕生日はいつですか。— 5月5日です）",
        choices: ["Where","How","Who","When"],
        answerIndex: 3,
        explanation: "「いつ」と日付や時をたずねるときは When を使います。",
        choiceHints: ["Where は「どこ」と場所をたずねる語です。日付をたずねるときは When です。","How は「どのように」と方法や様子をたずねる語です。日付をたずねるなら When です。","Who は「だれ」と人をたずねる語です。日付をたずねるときは When です。",null],
      },
      {
        id: "j1e-question-word-5",
        question: "___ is this T-shirt? — It's 1,000 yen.（このTシャツはいくらですか。— 1,000円です）",
        choices: ["How much","How many","How old","How long"],
        answerIndex: 0,
        explanation: "ねだんをたずねるときは How much を使います。「いくらですか」は How much is 〜? です。",
        choiceHints: [null,"How many は「いくつ」と数をたずねる言い方で、あとに複数形の名詞が必要です。ねだんは How much です。","How old は「何才」と年れいをたずねる言い方です。ねだんは How much です。","How long は「どのくらい長い」と長さや時間をたずねる言い方です。ねだんは How much です。"],
      },
      {
        id: "j1e-question-word-6",
        question: "___ are you sad? — Because my dog is sick.（なぜ悲しいのですか。— 犬が病気だからです）",
        choices: ["How","When","Why","Where"],
        answerIndex: 2,
        explanation: "「なぜ」と理由をたずねるときは Why を使います。答えは Because 〜（〜だから）で表します。",
        choiceHints: ["How は「どのように」と方法や様子をたずねる語です。理由をたずねるときは Why です。","When は「いつ」と時をたずねる語です。理由をたずねるときは Why です。",null,"Where は「どこ」と場所をたずねる語です。理由をたずねるときは Why です。"],
      },
      {
        id: "j1e-question-word-7",
        question: "___ books do you have? — I have ten.（あなたは本を何冊持っていますか。— 10冊です）",
        choices: ["How much","How many","How long","How old"],
        answerIndex: 1,
        explanation: "数をたずねるときは How many を使い、そのあとに複数形の名詞を置きます。How many books 〜? となります。",
        choiceHints: ["How much はねだんや、水などの数えられないものの量をたずねる言い方です。数は How many です。",null,"How long は「どのくらい長い」と長さや時間をたずねる言い方です。数は How many です。","How old は「何才」と年れいをたずねる言い方です。数は How many です。"],
      },
      {
        id: "j1e-question-word-8",
        question: "「あなたはどうやって学校に来ますか」を表す英文はどれ？",
        choices: ["How you come to school?","How does you come to school?","How are you come to school?","How do you come to school?"],
        answerIndex: 3,
        explanation: "疑問詞 How を文の最初に置き、そのあとは一般動詞の疑問文の語順にします。主語 you には do を使い How do you come to school? となります。",
        choiceHints: ["疑問詞のあとは疑問文の語順にします。How do you come 〜? とします。","主語 you には does ではなく do を使います。How do you come 〜? です。","be動詞と一般動詞をならべては使えません。How do you come 〜? とします。",null],
      },
    ],
  },
  {
    id: "j1e-present-progressive",
    subject: "english",
    grade: "中1",
    title: "現在進行形",
    lesson: "「今〜しています」と、いましている動作を表すのが現在進行形です。〈be動詞（am / is / are）＋動詞の -ing 形〉で作ります。-ing のつづりに注意しましょう。run は n を重ねて running、write は e をとって writing となります。否定は be動詞のあとに not を置き、疑問文は be動詞を主語の前に出します。",
    items: [
      {
        id: "j1e-present-progressive-1",
        question: "I ___ studying English now.（私は今、英語を勉強しています）",
        choices: ["am","is","are","do"],
        answerIndex: 0,
        explanation: "現在進行形は〈be動詞＋-ing 形〉です。主語が I のときの be動詞は am なので、am studying となります。",
        choiceHints: [null,"is は he / she / it などの三人称単数に使います。主語 I には am を使います。","are は you や複数の主語に使います。主語 I には am を使います。","do は一般動詞の疑問文や否定文に使います。現在進行形は am ＋ -ing です。"],
      },
      {
        id: "j1e-present-progressive-2",
        question: "He is ___ in the park now.（彼は今、公園で走っています）",
        choices: ["runing","running","runs","ran"],
        answerIndex: 1,
        explanation: "run は最後の n を重ねて -ing をつけ、running とつづります。is running で「走っています」を表します。",
        choiceHints: ["run は n を重ねて running とつづります。runing ではありません。",null,"runs は現在形です。「今〜している」は is running です。","ran は過去形です。「今〜している」は is running です。"],
      },
      {
        id: "j1e-present-progressive-3",
        question: "She is ___ a letter now.（彼女は今、手紙を書いています）",
        choices: ["writeing","writting","writing","writes"],
        answerIndex: 2,
        explanation: "write のように e で終わる動詞は、e をとって -ing をつけ writing とつづります。",
        choiceHints: ["e で終わる動詞は e をとって -ing をつけます。writeing ではなく writing です。","write は t を重ねません。e をとって writing とつづります。",null,"writes は現在形です。「今〜している」は is writing です。"],
      },
      {
        id: "j1e-present-progressive-4",
        question: "They ___ playing soccer now.（彼らは今、サッカーをしています）",
        choices: ["is","am","does","are"],
        answerIndex: 3,
        explanation: "主語が They（複数）なので be動詞は are です。are playing で「しています」を表します。",
        choiceHints: ["is は三人称単数に使います。複数の They には are を使います。","am は主語 I だけに使います。They には are を使います。","does は一般動詞の疑問文や否定文に使います。現在進行形は are ＋ -ing です。",null],
      },
      {
        id: "j1e-present-progressive-5",
        question: "I'm ___ watching TV now.（私は今、テレビを見ていません）",
        choices: ["not","don't","doesn't","no"],
        answerIndex: 0,
        explanation: "現在進行形の否定は be動詞のあとに not を置きます。I'm not watching となります。",
        choiceHints: [null,"don't は一般動詞の否定に使います。I'm のあとは not を置きます。","doesn't は三人称単数の一般動詞の否定です。ここは I'm not watching です。","no は名詞の前につける語です。be動詞のあとの否定は not です。"],
      },
      {
        id: "j1e-present-progressive-6",
        question: "「あなたは今、何をしていますか」を表す英文はどれ？",
        choices: ["What you are doing now?","What are you doing now?","What do you doing now?","What are you do now?"],
        answerIndex: 1,
        explanation: "現在進行形の疑問文は be動詞を主語の前に出します。What are you doing now? となり、動詞は -ing 形の doing です。",
        choiceHints: ["疑問文は are を主語 you の前に出します。What are you doing now? が正しい語順です。",null,"現在進行形の疑問文に do は使いません。are を使って What are you doing 〜? とします。","are のあとは -ing 形にします。do ではなく doing です。"],
      },
      {
        id: "j1e-present-progressive-7",
        question: "My mother is ___ lunch in the kitchen.（母は台所で昼食を作っています）",
        choices: ["make","makeing","making","makes"],
        answerIndex: 2,
        explanation: "make は e をとって -ing をつけ making とつづります。is making で「作っています」を表します。",
        choiceHints: ["is のあとは -ing 形にします。make ではなく making です。","make は e をとって -ing をつけます。makeing ではなく making です。",null,"makes は現在形です。is のあとは -ing 形の making にします。"],
      },
      {
        id: "j1e-present-progressive-8",
        question: "Is Tom ___ a bike now? — Yes, he is.（トムは今、自転車に乗っていますか）",
        choices: ["ride","rides","rode","riding"],
        answerIndex: 3,
        explanation: "Is で始まる現在進行形の疑問文なので、動詞は -ing 形にします。ride は e をとって riding です。",
        choiceHints: ["Is のあとは -ing 形にします。ride ではなく riding です。","rides は現在形です。現在進行形の疑問文では riding にします。","rode は過去形です。Is Tom 〜? のあとは riding です。",null],
      },
    ],
  },
  {
    id: "j1e-can",
    subject: "english",
    grade: "中1",
    title: "can（助動詞）",
    lesson: "can は「〜できる」という意味をそえる助動詞です。can のあとの動詞はいつも原形で、主語が三人称単数でも s はつけません（She can swim.）。否定は can't（cannot）を使います。疑問文は Can を主語の前に出します。Can you 〜? は「〜してくれませんか」という依頼にも使えます。",
    items: [
      {
        id: "j1e-can-1",
        question: "I can ___ the piano.（私はピアノをひけます）",
        choices: ["play","plays","playing","played"],
        answerIndex: 0,
        explanation: "助動詞 can のあとの動詞はいつも原形です。can play となります。",
        choiceHints: [null,"can のあとに s はつきません。原形 play にします。","can のあとは -ing 形にしません。原形 play です。","played は過去形です。can のあとは原形 play にします。"],
      },
      {
        id: "j1e-can-2",
        question: "He can ___ very fast.（彼はとても速く泳げます）",
        choices: ["swims","swim","swimming","swam"],
        answerIndex: 1,
        explanation: "主語が He でも、can のあとの動詞は原形のままです。can swim となります。",
        choiceHints: ["can のあとに s はつきません。主語が He でも原形 swim です。",null,"can のあとは -ing 形にしません。原形 swim です。","swam は過去形です。can のあとは原形 swim にします。"],
      },
      {
        id: "j1e-can-3",
        question: "She ___ cook curry.（彼女はカレーを作れません）",
        choices: ["don't can","doesn't can","can't","not can"],
        answerIndex: 2,
        explanation: "can の否定は can't（cannot）です。can't cook で「作れません」を表します。",
        choiceHints: ["can は助動詞なので don't とはいっしょに使いません。can't にします。","can は助動詞なので doesn't とはいっしょに使いません。can't にします。",null,"not は can のあとに置きます。can not（can't）cook が正しい形です。"],
      },
      {
        id: "j1e-can-4",
        question: "「窓を開けてくれませんか」を表す英文はどれ？",
        choices: ["Do you open the window?","Can you opening the window?","Are you can open the window?","Can you open the window?"],
        answerIndex: 3,
        explanation: "「〜してくれませんか」という依頼は Can you ＋動詞の原形 〜? で表します。",
        choiceHints: ["Do you open 〜? は「あなたは窓を開けますか」と習慣をたずねる文になります。依頼は Can you 〜? です。","can のあとは原形にします。opening ではなく open です。","can は助動詞なので be動詞といっしょには使いません。Can you 〜? とします。",null],
      },
      {
        id: "j1e-can-5",
        question: "Can you ___ this kanji? — Yes, I can.（あなたはこの漢字を読めますか）",
        choices: ["read","reads","reading","to read"],
        answerIndex: 0,
        explanation: "Can のあとの動詞も原形です。Can you read 〜? となります。",
        choiceHints: [null,"can のあとに s はつきません。原形 read にします。","can のあとは -ing 形にしません。原形 read です。","can のあとに to はつきません。原形 read だけにします。"],
      },
      {
        id: "j1e-can-6",
        question: "「私は上手に英語を話すことができます」を表す英文はどれ？",
        choices: ["I can speaking English well.","I can speak English well.","I can speaks English well.","I am can speak English well."],
        answerIndex: 1,
        explanation: "「〜できます」は〈can ＋動詞の原形〉です。I can speak English well. となります。",
        choiceHints: ["can のあとは原形にします。speaking ではなく speak です。",null,"can のあとに s はつきません。speaks ではなく speak です。","can は助動詞なので be動詞といっしょには使いません。I can speak 〜 とします。"],
      },
      {
        id: "j1e-can-7",
        question: "___ your sister sing well? — Yes, she can.（あなたのお姉さんは上手に歌えますか）",
        choices: ["Does","Is","Do","Can"],
        answerIndex: 3,
        explanation: "答えが Yes, she can. なので、たずねる文も Can で始めます。Can your sister sing 〜? となります。",
        choiceHints: ["Does でたずねると答えは Yes, she does. になります。ここは Can です。","Is のあとに動詞の原形 sing は続きません。ここは Can を使います。","Do は you や複数の主語に使います。答えの can に合わせて Can にします。",null],
      },
      {
        id: "j1e-can-8",
        question: "Birds can ___ in the sky.（鳥は空を飛ぶことができます）",
        choices: ["flies","flying","fly","to fly"],
        answerIndex: 2,
        explanation: "can のあとの動詞は原形です。can fly で「飛ぶことができる」を表します。",
        choiceHints: ["can のあとに s はつきません。原形 fly にします。","can のあとは -ing 形にしません。原形 fly です。",null,"can のあとに to はつきません。原形 fly だけにします。"],
      },
    ],
  },
  {
    id: "j1e-preposition",
    subject: "english",
    grade: "中1",
    title: "前置詞",
    lesson: "前置詞は場所や時を表す短い言葉です。場所では in（〜の中に）、on（〜の上に・面にふれて）、at（〜の一点に）、under（〜の下に）、by（〜のそばに）、near（〜の近くに）、between A and B（AとBの間に）を使い分けます。時では、曜日は on、時刻は at、月や年は in と覚えましょう。",
    items: [
      {
        id: "j1e-preposition-1",
        question: "I get up ___ six every morning.（私は毎朝6時に起きます）",
        choices: ["in","on","at","to"],
        answerIndex: 2,
        explanation: "時刻の前には at を使います。at six で「6時に」を表します。",
        choiceHints: ["in は月や年など長い時間に使います。時刻には at を使います。","on は曜日や日付に使います。時刻には at を使います。",null,"to は「〜へ」という方向を表します。時刻には at を使います。"],
      },
      {
        id: "j1e-preposition-2",
        question: "We have a party ___ Sunday.（私たちは日曜日にパーティーをします）",
        choices: ["on","in","at","of"],
        answerIndex: 0,
        explanation: "曜日の前には on を使います。on Sunday で「日曜日に」を表します。",
        choiceHints: [null,"in は月や年に使います。曜日には on を使います。","at は時刻に使います。曜日には on を使います。","of は「〜の」という意味です。曜日には on を使います。"],
      },
      {
        id: "j1e-preposition-3",
        question: "My birthday is ___ May.（私の誕生日は5月です）",
        choices: ["on","in","at","for"],
        answerIndex: 1,
        explanation: "月の前には in を使います。in May で「5月に」を表します。",
        choiceHints: ["on は曜日や日付に使います。月には in を使います。",null,"at は時刻に使います。月には in を使います。","for は「〜のために」などの意味です。月には in を使います。"],
      },
      {
        id: "j1e-preposition-4",
        question: "My dog is sleeping ___ the desk.（私の犬は机の下で寝ています）",
        choices: ["on","at","in","under"],
        answerIndex: 3,
        explanation: "「〜の下に」は under です。under the desk で「机の下で」を表します。",
        choiceHints: ["on は「〜の上に」です。「〜の下に」は under です。","at は場所を一点として表すときに使います。「〜の下に」は under です。","in は「〜の中に」です。「〜の下に」は under です。",null],
      },
      {
        id: "j1e-preposition-5",
        question: "The bank is ___ the school and the park.（銀行は学校と公園の間にあります）",
        choices: ["among","between","under","on"],
        answerIndex: 1,
        explanation: "「AとBの間に」は between A and B で表します。between the school and the park となります。",
        choiceHints: ["among は3つ以上のものにかこまれているときに使います。2つの間は between です。",null,"under は「〜の下に」です。2つのものの間は between です。","on は「〜の上に」です。2つのものの間は between です。"],
      },
      {
        id: "j1e-preposition-6",
        question: "Our school is ___ the station.（私たちの学校は駅の近くにあります）",
        choices: ["under","between","near","on"],
        answerIndex: 2,
        explanation: "「〜の近くに」は near です。near the station で「駅の近くに」を表します。",
        choiceHints: ["under は「〜の下に」です。「〜の近くに」は near です。","between は「2つのものの間に」です。「〜の近くに」は near です。",null,"on は「〜の上に」です。「〜の近くに」は near です。"],
      },
      {
        id: "j1e-preposition-7",
        question: "There is a picture ___ the wall.（壁に絵がかかっています）",
        choices: ["in","at","under","on"],
        answerIndex: 3,
        explanation: "面にくっついているときは on を使います。かべにふれているので on the wall です。",
        choiceHints: ["in は「〜の中に」です。かべの面にふれているので on を使います。","at は場所を一点として表すときに使います。かべにかかっている絵には on です。","under は「〜の下に」です。かべの面にふれているので on です。",null],
      },
      {
        id: "j1e-preposition-8",
        question: "I usually study English ___ my room.（私はふだん自分の部屋で英語を勉強します）",
        choices: ["at","in","on","under"],
        answerIndex: 1,
        explanation: "部屋のような「中」を表す場所には in を使います。in my room となります。",
        choiceHints: ["at は駅や学校のように一点として見る場所に使います。部屋の中は in です。",null,"on は「〜の上に」です。部屋の中は in を使います。","under は「〜の下に」です。部屋の中は in を使います。"],
      },
    ],
  },
  {
    id: "j1e-imperative",
    subject: "english",
    grade: "中1",
    title: "命令文",
    lesson: "相手に「〜しなさい」と言うときは、主語をつけずに動詞の原形で文を始めます（Open the door.）。be動詞のときは原形の Be を使います（Be quiet.）。「〜してはいけません」は Don't で文を始めます。「〜しよう」とさそうときは〈Let's ＋動詞の原形〉、ていねいに言うときは Please をそえます。",
    items: [
      {
        id: "j1e-imperative-1",
        question: "___ this book. It is very interesting.（この本を読みなさい。とてもおもしろいですよ）",
        choices: ["Reads","Read","Reading","To read"],
        answerIndex: 1,
        explanation: "命令文は主語をつけず、動詞の原形で始めます。Read this book. となります。",
        choiceHints: ["命令文は動詞の原形で始めます。Reads ではなく Read です。",null,"命令文は -ing 形では始めません。原形 Read にします。","命令文に to はつけません。原形 Read で始めます。"],
      },
      {
        id: "j1e-imperative-2",
        question: "「立ってください」をていねいに表す英文はどれ？",
        choices: ["Please stand up.","Please stands up.","You please stand up.","Please to stand up."],
        answerIndex: 0,
        explanation: "命令文に Please をそえるとていねいになります。動詞は原形のまま Please stand up. です。",
        choiceHints: [null,"命令文の動詞は原形です。stands ではなく stand です。","命令文では主語 You を言いません。Please stand up. とします。","命令文に to はつけません。Please stand up. が正しい形です。"],
      },
      {
        id: "j1e-imperative-3",
        question: "___ open the door.（ドアを開けてはいけません）",
        choices: ["Not","No","Don't","Doesn't"],
        answerIndex: 2,
        explanation: "「〜してはいけません」という否定の命令文は Don't で始めます。Don't open the door. となります。",
        choiceHints: ["否定の命令文は Not ではなく Don't で始めます。","No は「いいえ」や名詞の前につける語です。否定の命令文は Don't です。",null,"否定の命令文は相手がだれでも Don't を使います。Doesn't は使いません。"],
      },
      {
        id: "j1e-imperative-4",
        question: "___ play soccer after school.（放課後サッカーをしよう）",
        choices: ["Let","Let's","Lets","We're"],
        answerIndex: 1,
        explanation: "「〜しよう」とさそうときは〈Let's ＋動詞の原形〉です。Let's play soccer. となります。",
        choiceHints: ["「〜しよう」は Let ではなく Let's です。",null,"アポストロフィをつけて Let's と書きます。Lets ではありません。","We're は We are の短縮形です。「〜しよう」は Let's です。"],
      },
      {
        id: "j1e-imperative-5",
        question: "Let's ___ to the library.（図書館へ行こう）",
        choices: ["going","goes","to go","go"],
        answerIndex: 3,
        explanation: "Let's のあとの動詞は原形です。Let's go to the library. となります。",
        choiceHints: ["Let's のあとは原形にします。going ではなく go です。","Let's のあとに s はつきません。原形 go です。","Let's のあとに to はつきません。原形 go だけにします。",null],
      },
      {
        id: "j1e-imperative-6",
        question: "「教室で走ってはいけません」を表す英文はどれ？",
        choices: ["Don't running in the classroom.","Not run in the classroom.","Don't run in the classroom.","You don't run in the classroom."],
        answerIndex: 2,
        explanation: "否定の命令文は〈Don't ＋動詞の原形〉です。Don't run in the classroom. となります。",
        choiceHints: ["Don't のあとは原形にします。running ではなく run です。","否定の命令文は Don't で始めます。Not では始めません。",null,"主語 You をつけると「あなたは走りません」というふつうの文になります。命令文は Don't run 〜. です。"],
      },
      {
        id: "j1e-imperative-7",
        question: "___ careful! A car is coming.（気をつけて！車が来ます）",
        choices: ["Is","Are","Being","Be"],
        answerIndex: 3,
        explanation: "be動詞の命令文は原形の Be で始めます。Be careful! で「気をつけて」を表します。",
        choiceHints: ["命令文は動詞の原形で始めます。be動詞の原形は Be です。","Are は主語に合わせた形です。命令文では原形の Be を使います。","命令文は -ing 形では始めません。原形 Be にします。",null],
      },
      {
        id: "j1e-imperative-8",
        question: "「窓を閉めないでください」を表す英文はどれ？",
        choices: ["please を Don't と動詞の間には置きません。文の最初か終わりに置きます。","Don't please close the window.","Please not close the window.","Please doesn't close the window."],
        answerIndex: 0,
        explanation: "please を Don't と動詞の間には置きません。文の最初か終わりに置きます。",
        choiceHints: [null,"please を Don't と動詞の間には置きません。文の最初か終わりに置きます。","否定の命令文は not ではなく don't を使います。","否定の命令文は Don't を使います。doesn't は使いません。"],
      },
    ],
  },
  {
    id: "j1e-there-is",
    subject: "english",
    grade: "中1",
    title: "There is / There are",
    lesson: "「〜があります・〜がいます」は There is / There are で表します。あとにくる名詞が単数なら There is、複数なら There are です。否定は There isn't / There aren't、疑問文は Is there 〜? / Are there 〜? となります。some はふつうの文で、any は否定文や疑問文で使います。",
    items: [
      {
        id: "j1e-there-is-1",
        question: "___ a book on the desk.（机の上に本が1冊あります）",
        choices: ["There is","There are","There be","It is"],
        answerIndex: 0,
        explanation: "a book は単数なので There is を使います。There is a book on the desk. となります。",
        choiceHints: [null,"a book は単数なので There are ではなく There is を使います。","There のあとは be ではなく is や are にします。ここは There is です。","It is 〜 は「それは〜です」という意味です。「〜があります」は There is です。"],
      },
      {
        id: "j1e-there-is-2",
        question: "There ___ two cats under the chair.（いすの下に2匹のネコがいます）",
        choices: ["is","are","be","has"],
        answerIndex: 1,
        explanation: "two cats は複数なので are を使います。There are two cats 〜 となります。",
        choiceHints: ["two cats は複数なので is ではなく are を使います。",null,"There のあとは be ではなく are にします。","There has とは言いません。「〜がいます」は There are です。"],
      },
      {
        id: "j1e-there-is-3",
        question: "There ___ any milk in the glass.（コップの中に牛乳はありません）",
        choices: ["aren't","don't","isn't","not is"],
        answerIndex: 2,
        explanation: "milk は数えられない名詞で単数のあつかいです。否定は There isn't any milk 〜 となります。",
        choiceHints: ["milk は数えられない名詞で単数あつかいです。aren't ではなく isn't を使います。","There 〜 の否定に don't は使いません。isn't にします。",null,"not は is のあとに置きます。is not（isn't）が正しい形です。"],
      },
      {
        id: "j1e-there-is-4",
        question: "There ___ any students in the classroom.（教室には生徒が1人もいません）",
        choices: ["isn't","don't","not are","aren't"],
        answerIndex: 3,
        explanation: "students は複数なので aren't を使います。There aren't any students 〜 となります。",
        choiceHints: ["students は複数なので isn't ではなく aren't を使います。","There 〜 の否定に don't は使いません。aren't にします。","not は are のあとに置きます。are not（aren't）が正しい形です。",null],
      },
      {
        id: "j1e-there-is-5",
        question: "___ there a park near your house? — Yes, there is.（あなたの家の近くに公園はありますか）",
        choices: ["Is","Are","Do","Does"],
        answerIndex: 0,
        explanation: "a park は単数なので Is there 〜? とたずねます。答えも Yes, there is. になります。",
        choiceHints: [null,"a park は単数なので Are ではなく Is を使います。","There 〜 の疑問文に Do は使いません。Is there 〜? とします。","There 〜 の疑問文に Does は使いません。Is there 〜? とします。"],
      },
      {
        id: "j1e-there-is-6",
        question: "___ there any apples in the box? — No, there aren't.（箱の中にリンゴはありますか）",
        choices: ["Is","Are","Do","Have"],
        answerIndex: 1,
        explanation: "apples は複数なので Are there 〜? とたずねます。疑問文では some ではなく any を使います。",
        choiceHints: ["apples は複数なので Is ではなく Are を使います。",null,"There 〜 の疑問文に Do は使いません。Are there 〜? とします。","There 〜 の疑問文に Have は使いません。Are there 〜? とします。"],
      },
      {
        id: "j1e-there-is-7",
        question: "There are some ___ in the park.（公園に何人かの子どもがいます）",
        choices: ["child","a child","children","childs"],
        answerIndex: 2,
        explanation: "There are と some のあとは複数形にします。child の複数形は children です。",
        choiceHints: ["There are のあとは複数形にします。child ではなく children です。","a child は1人なので are とはいっしょに使えません。some のあとは children です。",null,"child の複数形は childs ではなく children です。"],
      },
      {
        id: "j1e-there-is-8",
        question: "There is ___ water in the bottle.（ボトルに水が入っています）",
        choices: ["many","a few","any","some"],
        answerIndex: 3,
        explanation: "water は数えられない名詞です。ふつうの文で「少しある」と言うときは some を使います。",
        choiceHints: ["many は数えられる名詞に使います。water には some を使います。","a few は数えられる名詞に使います。water には some を使います。","any はふつう否定文や疑問文で使います。「少しあります」という文では some です。",null],
      },
    ],
  },
];
