// 高校1年 英語（高1）の文法問題バンク（english_h1）。
// サブエージェントが作問し、別エージェントで文法監査した authored 確定データ。
// 生成AIは出題・採点・解説に使わない（採点は engine が answerIndex 比較）。
import type { QuizUnit } from "@/lib/quiz/types";

export const ENGLISH_UNITS_H1: QuizUnit[] = [
  {
    id: "h1e-present-perfect",
    subject: "english",
    grade: "高1",
    title: "現在完了形",
    lesson: "現在完了形は「have（三人称単数はhas）＋過去分詞」の形で作ります。過去に起きたことが「今」とつながっていることを表します。おもな使い方は3つで、「〜し終えた（完了・結果）」「〜したことがある（経験）」「ずっと〜している（継続）」です。already/yet/ever/never や、期間を表す since（〜から）・for（〜間）などとよく一緒に使います。yesterday など過去の一点を表す語があるときは過去形を使います。",
    items: [
      {
        id: "h1e-present-perfect-1",
        question: "I have ___ finished my homework. （私はもう宿題を終えました。）",
        choices: ["yet","already","ago","since"],
        answerIndex: 1,
        explanation: "「もう〜し終えた」という完了の意味は already で表します。ふつう肯定文の have と過去分詞の間に置きます。",
        choiceHints: ["yet は「まだ・もう」の意味ですが、おもに否定文・疑問文で使います。肯定文には使えません。",null,"ago は「〜前に」という意味で過去形と使う語です。現在完了形には使えません。","since は「〜から（ずっと）」と起点を表す語で、ここには合いません。"],
      },
      {
        id: "h1e-present-perfect-2",
        question: "Have you ___ eaten sushi? （あなたは今までに寿司を食べたことがありますか。）",
        choices: ["ever","yet","already","for"],
        answerIndex: 0,
        explanation: "「今までに〜したことがありますか」という経験をたずねる疑問文では ever を使います。",
        choiceHints: [null,"yet は疑問文では「もう〜しましたか」の完了の意味になり、「今までに」という経験の意味にはなりません。","already は「もう（すでに）」で、おもに肯定文で使います。経験をたずねる文には合いません。","for は「〜の間」と期間を表す語で、経験をたずねる文には合いません。"],
      },
      {
        id: "h1e-present-perfect-3",
        question: "She has lived in Tokyo ___ 2015. （彼女は2015年からずっと東京に住んでいます。）",
        choices: ["for","in","since","from"],
        answerIndex: 2,
        explanation: "「2015年」という過去の一点（起点）から今まで続いているので since を使います。since のあとには「時の始まり」を表す語がきます。",
        choiceHints: ["for は「3年間」のように期間の長さと使います。「2015年」という起点にはsinceを使います。","in は場所や年月そのものを表すときに使い、「〜からずっと」の起点は表せません。",null,"from も「〜から」ですが、現在完了で継続の起点を表すときは since を使うのがふつうです。"],
      },
      {
        id: "h1e-present-perfect-4",
        question: "We have known each other ___ ten years. （私たちは10年間ずっと知り合いです。）",
        choices: ["since","during","for","at"],
        answerIndex: 2,
        explanation: "「10年間」という期間の長さを表すときは for を使います。for のあとには期間を表す語がきます。",
        choiceHints: ["since は「2015年から」のように起点と使います。「10年間」という長さには for を使います。","during は「夏の間」のように特定の期間の名詞と使い、数字の期間の長さには合いません。",null,"at は時刻や一点を表す語で、期間の長さは表せません。"],
      },
      {
        id: "h1e-present-perfect-5",
        question: "「彼はまだ帰ってきていません。」を表す正しい英文はどれ？",
        choices: ["He has not come home yet.","He has not come home already.","He not has come home yet.","He has not came home yet."],
        answerIndex: 0,
        explanation: "否定文は have/has not ＋過去分詞 の形で、「まだ〜していない」は文末に yet を置きます。come の過去分詞は come です。",
        choiceHints: [null,"already はおもに肯定文で使います。否定文で「まだ」を表すときは yet を使います。","not の位置が正しくありません。has not come のように has のあとに not を置きます。","came は過去形です。現在完了形では過去分詞の come を使います。"],
      },
      {
        id: "h1e-present-perfect-6",
        question: "My brother ___ his key, so he can't open the door. （弟はかぎをなくしてしまい、ドアを開けられません。）",
        choices: ["has lost","have lost","lost","has losed"],
        answerIndex: 0,
        explanation: "「なくして、その結果、今開けられない」という結果を表すので現在完了形が合います。主語が三人称単数なので has、lose の過去分詞は lost です。",
        choiceHints: [null,"主語 my brother は三人称単数なので have ではなく has を使います。","過去形 lost だと「なくした」という過去の事実だけになり、今も見つかっていない結果とはつながりません。","losed という形はありません。lose の過去分詞は lost です。"],
      },
      {
        id: "h1e-present-perfect-7",
        question: "「あなたはもう昼食を食べましたか。」を表す正しい英文はどれ？",
        choices: ["Did you have lunch yet?","Have you had lunch yet?","Have you have lunch yet?","Are you had lunch yet?"],
        answerIndex: 1,
        explanation: "「もう〜しましたか」という完了をたずねる疑問文は Have you ＋過去分詞 の形にし、文末に yet を置きます。have の過去分詞は had です。",
        choiceHints: ["Did は過去形の疑問文を作ります。yet と一緒に完了をたずねるときは Have を使った現在完了形にします。",null,"have が2つ続いています。Have you had ... のように2つ目は過去分詞 had にします。","Are では現在完了形になりません。疑問文は Have you had ... の形にします。"],
      },
      {
        id: "h1e-present-perfect-8",
        question: "I ___ this movie last night. （私は昨夜この映画を見ました。）",
        choices: ["have watched","has watched","watched","have watch"],
        answerIndex: 2,
        explanation: "last night（昨夜）という過去の一点を表す語があるので、現在完了形ではなく過去形 watched を使います。",
        choiceHints: ["last night という過去の一点を表す語があるので、現在完了形は使えません。過去形にします。","主語が I なので has は使えません。また過去の一点を表す文なので過去形にします。",null,"have watch は形が不完全です。そもそも過去の一点を表すので過去形 watched を使います。"],
      },
    ],
  },
  {
    id: "h1e-past-perfect",
    subject: "english",
    grade: "高1",
    title: "過去完了形",
    lesson: "過去完了形は「had + 過去分詞」で表します。過去のある時点よりも、さらに前のできごと（大過去）や、その時までの継続・経験を表すときに使います。また「have been + -ing」は今も続いている動作を強調する現在完了進行形です。過去のできごとの前後関係に気をつけて使い分けましょう。",
    items: [
      {
        id: "h1e-past-perfect-1",
        question: "When I arrived at the station, the train ___ already left. （私が駅に着いたとき、電車はもう出てしまっていた。）",
        choices: ["had","has","have","was"],
        answerIndex: 0,
        explanation: "駅に着いた（過去）よりも前に電車が出ていたので、大過去を表す過去完了形「had + 過去分詞」を使います。",
        choiceHints: [null,"has は現在完了形です。過去の話なので had を使います。","have は主語が I 以外の複数などに使う形で、ここでは時制も合いません。","was left では受け身になり、意味が通りません。"],
      },
      {
        id: "h1e-past-perfect-2",
        question: "She told me that she ___ never seen snow before. （彼女はそれまで一度も雪を見たことがないと私に言った。）",
        choices: ["has","had","was","did"],
        answerIndex: 1,
        explanation: "told（過去）よりも前の「それまでの経験」を表すので、過去完了形「had + 過去分詞」を使います。",
        choiceHints: ["has は現在完了形です。told に合わせて過去の had にします。",null,"was seen では受け身になり、経験の意味になりません。","did の後には原形が来ます。seen とはつながりません。"],
      },
      {
        id: "h1e-past-perfect-3",
        question: "By the time we got home, it ___ raining. （私たちが家に着くころには、雨が降り始めていた。）",
        choices: ["has started","was started","had started","start"],
        answerIndex: 2,
        explanation: "got home（過去）よりも前に雨が降り始めていたので、過去完了形「had + 過去分詞」を使います。",
        choiceHints: ["has started は現在完了形です。過去の話なので had started にします。","was started では受け身になり、意味が通りません。",null,"start は原形で、時制を表せません。"],
      },
      {
        id: "h1e-past-perfect-4",
        question: "He ___ for two hours when his friend finally called. （友達がようやく電話してきたとき、彼は2時間ずっと待っていた。）",
        choices: ["had been waiting","has been waiting","was waiting","had been waited"],
        answerIndex: 0,
        explanation: "電話がかかってきた（過去）時点まで2時間ずっと続いていた動作なので、過去完了進行形「had been + -ing」を使います。",
        choiceHints: [null,"has been waiting は現在完了進行形です。過去の話なので had にします。","was waiting だと「2時間ずっと続いた」という継続の強調が弱くなります。","had been waited は受け身の形で、ここでは意味が通りません。「ずっと待っていた」は能動の had been waiting です。"],
      },
      {
        id: "h1e-past-perfect-5",
        question: "I ___ that book before, so I already knew the ending. （私はその本を前に読んだことがあったので、もう結末を知っていた。）",
        choices: ["have read","read","had read","was reading"],
        answerIndex: 2,
        explanation: "「知っていた」（過去）よりも前の経験を表すので、過去完了形「had + 過去分詞」を使います。",
        choiceHints: ["have read は現在完了形です。過去の話なので had read にします。","read（過去形）では「それより前に読んだ」という前後関係が表せません。",null,"was reading は過去のある時点で読んでいる最中を表し、経験の意味になりません。"],
      },
      {
        id: "h1e-past-perfect-6",
        question: "It ___ for three days now, and the roads are still wet. （もう3日間ずっと雨が降っていて、道はまだぬれている。）",
        choices: ["had been raining","has been raining","was raining","rained"],
        answerIndex: 1,
        explanation: "「now（今）」まで続いていて今も影響があるので、現在完了進行形「have been + -ing」を使います。now があるので過去完了ではありません。",
        choiceHints: ["had been raining は過去完了進行形です。now があるので現在の has been にします。",null,"was raining は過去の一場面を表し、今まで続く意味になりません。","rained（過去形）では今も続いている感じが出ません。"],
      },
      {
        id: "h1e-past-perfect-7",
        question: "「昨日私が公園に着く前に、弟はもう帰ってしまっていた」を正しく表す英文はどれ？",
        choices: ["My brother has already gone home before I got to the park yesterday.","My brother already went home before I got to the park yesterday.","My brother had already gone home before I got to the park yesterday.","My brother was already gone home before I got to the park yesterday."],
        answerIndex: 2,
        explanation: "公園に着いた（過去）よりも前に帰っていたので、大過去を表す過去完了形「had + 過去分詞」を使います。",
        choiceHints: ["has gone は現在完了形です。yesterday など過去の話には had を使います。","went（過去形）では「それより前に帰った」という前後関係がはっきりしません。",null,"was gone home は文法的に正しくありません。had gone home が正しい形です。"],
      },
      {
        id: "h1e-past-perfect-8",
        question: "We couldn't get tickets because they ___ out before we arrived. （私たちが着く前にチケットが売り切れていたので、買えなかった。）",
        choices: ["had sold","have sold","sold","are sold"],
        answerIndex: 0,
        explanation: "買えなかった（過去）よりも前に売り切れていたので、過去完了形「had + 過去分詞」を使います。sell out は「売り切れる」という意味です。",
        choiceHints: [null,"have sold out は現在完了形です。過去の話なので had sold out にします。","sold out（過去形）では「それより前に売り切れていた」という前後関係が表せません。","are sold out は現在形です。過去の話なので had sold out にします。"],
      },
    ],
  },
  {
    id: "h1e-modals",
    subject: "english",
    grade: "高1",
    title: "助動詞",
    lesson: "助動詞は動詞の前に置いて「気持ち」や「判断」を加える言葉です。義務(must/have to)、助言(should/had better)、推量(must be/can't be)などを表します。助動詞のあとの動詞はいつも原形です。過去のことを推し量るときは must have p.p.（〜だったにちがいない）のように使います。",
    items: [
      {
        id: "h1e-modals-1",
        question: "You look pale. You ___ be tired.（あなたは青白い顔をしている。疲れているにちがいない。）",
        choices: ["must","can't","may not","need"],
        answerIndex: 0,
        explanation: "「〜にちがいない」という強い推量は must be で表します。can't be は「〜のはずがない」で反対の意味です。",
        choiceHints: [null,"「〜のはずがない」という反対の推量です。","「〜でないかもしれない」で確信が弱すぎます。","この文の形には合いません。"],
      },
      {
        id: "h1e-modals-2",
        question: "He ate a big lunch, so he ___ be hungry now.（彼はお昼をたくさん食べたので、今おなかがすいているはずがない。）",
        choices: ["must","should","can't","would"],
        answerIndex: 2,
        explanation: "「〜のはずがない」という強い否定の推量は can't be で表します。must be は「〜にちがいない」で反対の意味です。",
        choiceHints: ["「〜にちがいない」で反対の意味になります。","「〜のはずだ」で確信が弱く、文脈に合いません。",null,"「〜だろうに」で推量の意味が合いません。"],
      },
      {
        id: "h1e-modals-3",
        question: "Students ___ wear a uniform at this school.（この学校では生徒は制服を着なければならない。）",
        choices: ["may","must","could","would"],
        answerIndex: 1,
        explanation: "「〜しなければならない」という義務は must で表します。may は「〜してもよい」で許可の意味です。",
        choiceHints: ["「〜してもよい」で許可の意味になります。",null,"「〜できた」で義務を表せません。","「〜だろう」で義務の意味になりません。"],
      },
      {
        id: "h1e-modals-4",
        question: "You ___ see a doctor if you feel sick.（気分が悪いなら医者に診てもらうべきだ。）",
        choices: ["should","must not","used to","would rather"],
        answerIndex: 0,
        explanation: "「〜すべきだ」という助言は should で表します。must not は「〜してはいけない」で禁止の意味です。",
        choiceHints: [null,"「〜してはいけない」で禁止の意味になります。","「以前は〜した」で過去の習慣を表します。","「むしろ〜したい」で助言になりません。"],
      },
      {
        id: "h1e-modals-5",
        question: "The ground is wet. It ___ have rained last night.（地面がぬれている。昨夜、雨が降ったにちがいない。）",
        choices: ["should","can't","must","may not"],
        answerIndex: 2,
        explanation: "「〜したにちがいない」という過去の強い推量は must have p.p. で表します。should have p.p. は「〜すべきだったのに」で意味が違います。",
        choiceHints: ["「〜すべきだったのに」で後悔の意味になります。","「〜したはずがない」で反対の意味です。",null,"「〜しなかったかもしれない」で推量が弱すぎます。"],
      },
      {
        id: "h1e-modals-6",
        question: "There ___ be a big park here, but now it's a mall.（ここには以前は大きな公園があったが、今はモールだ。）",
        choices: ["would like to","had better","used to","must"],
        answerIndex: 2,
        explanation: "「以前は〜だった（今は違う）」という過去の状態は used to で表します。今との対比を示すときに使います。",
        choiceHints: ["「〜したい」で希望の意味になります。","「〜したほうがよい」で過去の状態を表せません。",null,"「〜にちがいない」で過去の状態を表せません。"],
      },
      {
        id: "h1e-modals-7",
        question: "It's getting dark. We ___ go home now.（暗くなってきた。もう家に帰ったほうがよい。）",
        choices: ["had better","would like to","used to","may not"],
        answerIndex: 0,
        explanation: "「〜したほうがよい（しないとまずい）」という強めの助言は had better で表します。あとの動詞は原形です。",
        choiceHints: [null,"「〜したい」で希望の意味になります。","「以前は〜した」で過去の習慣を表します。","「〜でないかもしれない」で助言になりません。"],
      },
      {
        id: "h1e-modals-8",
        question: "「（お店で）水を一杯いただきたいのですが。」を表すのはどれ？",
        choices: ["I must have a glass of water.","I would like a glass of water.","I can't have a glass of water.","I used to have a glass of water."],
        answerIndex: 1,
        explanation: "「〜がほしいのですが」という丁寧な希望は would like で表します。I want より上品な言い方です。",
        choiceHints: ["「水を飲まなければならない」で希望になりません。",null,"「水を飲めない」で反対の意味です。","「以前は水を飲んだ」で過去の習慣になります。"],
      },
    ],
  },
  {
    id: "h1e-passive",
    subject: "english",
    grade: "高1",
    title: "受動態",
    lesson: "受動態（じゅどうたい）は「〜される」という意味を表すよ。形は〈be動詞 ＋ 過去分詞（p.p.）〉だよ。be動詞の時制（is/was/will beなど）で「いつのことか」を表すよ。「誰によって」を言うときは by を使うよ。can be done（〜されうる）や have been done（ずっと〜されている）のような形もあるよ。",
    items: [
      {
        id: "h1e-passive-1",
        question: "This letter ___ by Ken yesterday. （この手紙は昨日ケンによって書かれた。）",
        choices: ["was written","is written","wrote","was wrote"],
        answerIndex: 0,
        explanation: "「昨日」だから過去で、「書かれた」だから受動態〈was ＋ 過去分詞〉。write の過去分詞は written だよ。",
        choiceHints: [null,"現在形だから「昨日」に合わないよ。","これは能動態（〜が書いた）だよ。受け身にしよう。","過去分詞は wrote ではなく written だよ。"],
      },
      {
        id: "h1e-passive-2",
        question: "English ___ in many countries. （英語は多くの国で話されている。）",
        choices: ["speaks","is speaking","is spoken","spoken"],
        answerIndex: 2,
        explanation: "「話されている」だから受動態〈is ＋ 過去分詞〉。speak の過去分詞は spoken だよ。",
        choiceHints: ["これは能動態（〜を話す）だよ。受け身にしよう。","進行形で意味が合わないよ。受け身にしよう。",null,"be動詞（is）がないと受動態にならないよ。"],
      },
      {
        id: "h1e-passive-3",
        question: "The window ___ by the boy last night. （その窓は昨夜その男の子に割られた。）",
        choices: ["is broken","was broken","was break","broke"],
        answerIndex: 1,
        explanation: "「昨夜」だから過去、「割られた」だから受動態〈was ＋ 過去分詞〉。break の過去分詞は broken だよ。",
        choiceHints: ["現在形だから「昨夜」に合わないよ。",null,"be動詞の後ろは過去分詞 broken だよ。","これは能動態（〜が割った）だよ。受け身にしよう。"],
      },
      {
        id: "h1e-passive-4",
        question: "The baby was given a nice toy by his aunt.（SVOOの受動態）と同じ内容を表すのはどれ？ （赤ちゃんはおばさんからすてきなおもちゃをもらった。）",
        choices: ["His aunt gave the baby a nice toy.","The baby gave his aunt a nice toy.","A nice toy gave the baby his aunt.","His aunt was given a nice toy."],
        answerIndex: 0,
        explanation: "give A B（AにBを与える）の受動態だよ。「おばさんが赤ちゃんにおもちゃを与えた」が元の能動態。〈His aunt gave the baby a nice toy.〉が正しいよ。",
        choiceHints: [null,"あげた人ともらった人が逆だよ。","語順がおかしくて意味が通らないよ。","これだと「おばさんがもらった」になり内容が変わるよ。"],
      },
      {
        id: "h1e-passive-5",
        question: "The old man ___ by the children. （そのおじいさんは子どもたちに笑われた。）",
        choices: ["was laughed","laughed at","was laughed at","was laughing at"],
        answerIndex: 2,
        explanation: "laugh at 〜（〜を笑う）は群動詞。受動態でも at を残して〈was laughed at〉にするよ。",
        choiceHints: ["at を落としてはいけないよ。laugh at のセットで使うよ。","これは能動態だよ。受け身にしよう。",null,"進行形になっていて意味が合わないよ。"],
      },
      {
        id: "h1e-passive-6",
        question: "This bridge ___ next year. （この橋は来年建てられるだろう。）",
        choices: ["will build","will be built","will built","is built"],
        answerIndex: 1,
        explanation: "「来年〜されるだろう」だから助動詞willの受動態〈will be ＋ 過去分詞〉。build の過去分詞は built だよ。",
        choiceHints: ["これは能動態（〜が建てる）だよ。受け身にしよう。",null,"will の後ろは be built だよ。be が必要だよ。","現在形だから「来年」に合わないよ。"],
      },
      {
        id: "h1e-passive-7",
        question: "These questions ___ by anyone. （これらの問題はだれでも解ける＝解かれうる。）",
        choices: ["can solved","can be solved","can solve","are can solved"],
        answerIndex: 1,
        explanation: "「〜されうる」だから助動詞canの受動態〈can be ＋ 過去分詞〉。solve の過去分詞は solved だよ。",
        choiceHints: ["can の後ろは be solved だよ。be が必要だよ。",null,"これは能動態（〜を解ける）だよ。受け身にしよう。","can と be動詞は同時に並べられないよ。"],
      },
      {
        id: "h1e-passive-8",
        question: "The room ___ cleaned since this morning. （その部屋は今朝からずっと掃除されている。）",
        choices: ["has been","is","has","was been"],
        answerIndex: 0,
        explanation: "「ずっと〜されている」は現在完了の受動態〈have/has been ＋ 過去分詞〉。The room は単数なので has been cleaned だよ。",
        choiceHints: [null,"「ずっと〜されている」には現在完了（has been）が必要だよ。","has の後ろに been がないと受動態にならないよ。","現在完了は has been で、was been とは言わないよ。"],
      },
    ],
  },
  {
    id: "h1e-infinitive",
    subject: "english",
    grade: "高1",
    title: "不定詞",
    lesson: "不定詞は「to + 動詞のもとの形」です。「〜すること」（名詞的）、「〜するための」（形容詞的）、「〜するために」（副詞的）の3つの意味があります。too ~ to（〜すぎて…できない）や ~ enough to（…するのに十分〜）などの表現も覚えましょう。",
    items: [
      {
        id: "h1e-infinitive-1",
        question: "My dream is ___ a doctor.（私の夢は医者になることです。）",
        choices: ["to become","becoming to","become","became"],
        answerIndex: 0,
        explanation: "「〜になること」は名詞的用法の to + 動詞のもとの形で表します。be動詞のあとに来て、主語の説明（補語）になっています。",
        choiceHints: [null,"becoming to という形はありません。名詞的用法は to + 動詞です。","to がありません。dream is のあとには to become が必要です。","過去形は入れません。to のあとは動詞のもとの形です。"],
      },
      {
        id: "h1e-infinitive-2",
        question: "I have a lot of homework ___ today.（私は今日やるべき宿題がたくさんある。）",
        choices: ["doing","do","to do","did"],
        answerIndex: 2,
        explanation: "「〜するための」と前の名詞（homework）を説明するのは形容詞的用法です。名詞のうしろに to + 動詞のもとの形を置きます。",
        choiceHints: ["doing では名詞を説明できません。to do にします。","to がないと名詞を説明できません。",null,"過去形は使いません。to + 動詞のもとの形にします。"],
      },
      {
        id: "h1e-infinitive-3",
        question: "She got up early ___ the first train.（彼女は始発電車に乗るために早起きした。）",
        choices: ["catching","to catch","for catch","catch"],
        answerIndex: 1,
        explanation: "「〜するために」と目的を表すのは副詞的用法です。to + 動詞のもとの形で表します。",
        choiceHints: ["-ing では目的を表せません。to catch にします。",null,"for catch という形はありません。目的は to catch です。","to がありません。目的は to catch で表します。"],
      },
      {
        id: "h1e-infinitive-4",
        question: "This tea is too hot ___ .（このお茶は熱すぎて飲めない。）",
        choices: ["to drink","drinking","for drink","drink to"],
        answerIndex: 0,
        explanation: "「too ~ to …」で「〜すぎて…できない」という意味です。too のあとに形容詞、そのあとに to + 動詞のもとの形を置きます。",
        choiceHints: [null,"too ~ のあとは to + 動詞です。drinking は使えません。","for drink という形はありません。to drink にします。","語順が違います。too hot to drink が正しい形です。"],
      },
      {
        id: "h1e-infinitive-5",
        question: "He is old ___ to drive a car.（彼は車を運転できる年齢だ。）",
        choices: ["too","so","enough","very"],
        answerIndex: 2,
        explanation: "「~ enough to …」で「…するのに十分〜」という意味です。enough は形容詞（old）のうしろに置くのがポイントです。",
        choiceHints: ["too old to では「年をとりすぎて運転できない」となり意味が逆です。","so は enough のようには使えません。",null,"very のあとに to は続けられません。enough を使います。"],
      },
      {
        id: "h1e-infinitive-6",
        question: "It is kind ___ you to help me.（手伝ってくれてあなたは親切ですね。）",
        choices: ["for","of","to","with"],
        answerIndex: 1,
        explanation: "kind（親切な）など人の性質を表す形容詞のときは、of 人 を使います。for ではなく of なので注意しましょう。",
        choiceHints: ["性質を表す kind のときは for ではなく of を使います。",null,"to you では意味がつながりません。of you が正しい形です。","with は使いません。of you にします。"],
      },
      {
        id: "h1e-infinitive-7",
        question: "My mother told me ___ my room.（母は私に部屋を掃除するように言った。）",
        choices: ["clean","cleaning","to clean","cleaned"],
        answerIndex: 2,
        explanation: "「tell 人 to do」で「人に〜するように言う」という意味です。人のあとに to + 動詞のもとの形を置きます。",
        choiceHints: ["to がありません。told me to clean が正しい形です。","-ing は使いません。to clean にします。",null,"過去形は使いません。to + 動詞のもとの形にします。"],
      },
      {
        id: "h1e-infinitive-8",
        question: "I don't know ___ to say in English.（英語で何と言えばよいか分からない。）",
        choices: ["what","how","which","that"],
        answerIndex: 0,
        explanation: "「疑問詞 + to do」で「〜すべきか」を表します。「何と言えばよいか」なので what to say が正しい形です。",
        choiceHints: [null,"how to say は「言い方」で、「何を」の意味にはなりません。","which は選ぶものがあるときに使います。ここは what です。","that to say という形はありません。what を使います。"],
      },
    ],
  },
  {
    id: "h1e-gerund",
    subject: "english",
    grade: "高1",
    title: "動名詞",
    lesson: "動名詞は「動詞のing形」を名詞のように使い、「〜すること」という意味をあらわします。文の主語や目的語、前置詞のあとに置けます。enjoy, finish, stop, give up などのあとは動名詞、want, hope, decide などのあとは to不定詞をとります。remember や stop は、うしろが動名詞か to不定詞かで意味が変わるので気をつけましょう。",
    items: [
      {
        id: "h1e-gerund-1",
        question: "I enjoy ___ soccer with my friends.（友だちとサッカーをするのを楽しんでいます。）",
        choices: ["playing","to play","play","played"],
        answerIndex: 0,
        explanation: "enjoy のうしろは動名詞（-ing）を使います。「〜することを楽しむ」は enjoy playing です。to play や play は使えません。",
        choiceHints: [null,"enjoy のあとに to不定詞は続きません。","動詞の原形ではなく -ing の形にします。","過去分詞ではなく動名詞（-ing）にします。"],
      },
      {
        id: "h1e-gerund-2",
        question: "She decided ___ abroad next year.（彼女は来年、留学することを決めました。）",
        choices: ["studying","study","to study","studied"],
        answerIndex: 2,
        explanation: "decide のうしろは to不定詞を使います。「〜することに決める」は decide to do です。動名詞 studying は使えません。",
        choiceHints: ["decide のあとは動名詞ではなく to不定詞です。","動詞の原形だけでは続けられません。",null,"過去形・過去分詞は続けられません。"],
      },
      {
        id: "h1e-gerund-3",
        question: "Thank you for ___ me with my homework.（宿題を手伝ってくれてありがとう。）",
        choices: ["help","to help","helped","helping"],
        answerIndex: 3,
        explanation: "前置詞 for のうしろは動名詞（-ing）を使います。「〜してくれてありがとう」は Thank you for -ing です。for のあとに to不定詞は続きません。",
        choiceHints: ["前置詞のあとは動詞の原形ではなく -ing にします。","前置詞 for のあとに to不定詞は続きません。","前置詞のあとは過去形ではなく -ing にします。",null],
      },
      {
        id: "h1e-gerund-4",
        question: "We look forward to ___ you again soon.（近いうちにまたお会いできるのを楽しみにしています。）",
        choices: ["seeing","see","to see","saw"],
        answerIndex: 0,
        explanation: "look forward to の to は前置詞なので、うしろは動名詞（-ing）になります。「〜を楽しみにする」は look forward to -ing です。to see としないよう注意しましょう。",
        choiceHints: [null,"動詞の原形ではなく -ing にします。","この to は前置詞なので、動詞の原形は続けません。","過去形ではなく動名詞（-ing）にします。"],
      },
      {
        id: "h1e-gerund-5",
        question: "He is good at ___ pictures.（彼は絵をかくのが得意です。）",
        choices: ["draw","to draw","drawing","drew"],
        answerIndex: 2,
        explanation: "be good at の at は前置詞なので、うしろは動名詞（-ing）を使います。「〜が得意だ」は be good at -ing です。to draw や draw は使えません。",
        choiceHints: ["前置詞 at のあとは動詞の原形にできません。","前置詞 at のあとに to不定詞は続きません。",null,"前置詞のあとは過去形ではなく -ing にします。"],
      },
      {
        id: "h1e-gerund-6",
        question: "On his way home, he stopped ___ some bread at the store.（家に帰るとちゅう、彼はパンを買うために店に立ち寄った。）",
        choices: ["buying","to buy","buy","bought"],
        answerIndex: 1,
        explanation: "stop to do は「〜するために立ち止まる（立ち寄る）」という意味です。ここでは「パンを買うために立ち寄った」なので to buy を使います。stop buying だと「パンを買うのをやめる」という別の意味になります。",
        choiceHints: ["stop buying は「買うのをやめる」で意味が合いません。",null,"動詞の原形だけでは続けられません。","過去形ではなく to不定詞にします。"],
      },
      {
        id: "h1e-gerund-7",
        question: "Please remember ___ the door when you leave.（出るときは、ドアにかぎをかけるのを忘れないでね。）",
        choices: ["locking","to lock","lock","locked"],
        answerIndex: 1,
        explanation: "remember to do は「（これから）〜するのを覚えている＝忘れずに〜する」という意味です。まだしていないこれからの動作なので to lock を使います。remember locking だと「（もう）かぎをかけたのを覚えている」という別の意味になります。",
        choiceHints: ["remember locking は「かぎをかけたのを覚えている」で意味が合いません。",null,"動詞の原形だけでは続けられません。","過去形ではなく to不定詞にします。"],
      },
      {
        id: "h1e-gerund-8",
        question: "「読書は私の趣味です」を表す英文はどれ？",
        choices: ["Read is my hobby.","To reading is my hobby.","Reading is my hobby.","Reads is my hobby."],
        answerIndex: 2,
        explanation: "「読書＝本を読むこと」は動名詞 Reading で主語にできます。Reading is my hobby. が正しい文です。動詞の原形 Read や To reading は主語になりません。",
        choiceHints: ["動詞の原形は主語になれません。","To のあとに -ing は続けられません。",null,"動詞の三単現の形は主語になれません。"],
      },
    ],
  },
  {
    id: "h1e-participle",
    subject: "english",
    grade: "高1",
    title: "分詞",
    lesson: "分詞は動詞を形容詞のように使う形です。現在分詞（-ing）は「〜している」という能動の意味、過去分詞（-ed など）は「〜される・された」という受け身の意味を表します。1語なら名詞の前、語句がつくときは名詞の後ろに置きます。感情を表す動詞は、人が感じるときは -ed、物や事が感情を起こさせるときは -ing を使います。",
    items: [
      {
        id: "h1e-participle-1",
        question: "Look at the ___ baby. She looks so peaceful.（眠っている赤ちゃんを見て。）",
        choices: ["sleeping","slept","sleep","to sleep"],
        answerIndex: 0,
        explanation: "「眠っている赤ちゃん」は「赤ちゃんが眠っている」という能動の関係なので、現在分詞 sleeping を使います。1語で名詞を前から修飾します。",
        choiceHints: [null,"過去分詞。sleep は自動詞なので受け身にはならず、名詞を修飾できません。","動詞の原形。名詞を修飾する形ではありません。","不定詞。ここでは名詞を前から修飾できません。"],
      },
      {
        id: "h1e-participle-2",
        question: "This is a book ___ in easy English.（これはやさしい英語で書かれた本です。）",
        choices: ["writing","wrote","written","write"],
        answerIndex: 2,
        explanation: "「書かれた本」は「本が書かれる」という受け身の関係なので、過去分詞 written を使います。語句（in easy English）がつくので名詞の後ろに置きます。",
        choiceHints: ["現在分詞。「本が書いている」となり意味が合いません。","過去形。文の動詞ではなく名詞を修飾する形が必要です。",null,"動詞の原形。名詞を後ろから修飾する形ではありません。"],
      },
      {
        id: "h1e-participle-3",
        question: "The movie was really ___, so I watched it twice.（その映画はとてもわくわくした。）",
        choices: ["excited","exciting","excite","excitement"],
        answerIndex: 1,
        explanation: "映画は人をわくわくさせる「物・事」なので、-ing の exciting を使います。exciting は「（見る人を）わくわくさせるような」という意味です。",
        choiceHints: ["-ed は人が「わくわくした」ときに使います。主語が movie なので合いません。",null,"動詞の原形。be動詞の後ろで形容詞のように使う形ではありません。","名詞「興奮」。ここでは補語として形容詞の働きが必要です。"],
      },
      {
        id: "h1e-participle-4",
        question: "I was very ___ in the science class today.（私は今日の理科の授業にとても興味を持った。）",
        choices: ["interest","interesting","interested","interests"],
        answerIndex: 2,
        explanation: "人が「興味を持った」と感じるときは -ed の interested を使い、be interested in 〜 で「〜に興味がある」となります。",
        choiceHints: ["動詞・名詞の原形。be動詞の後ろの形容詞にはなりません。","-ing は物・事が「興味を起こさせる」ときに使います。主語が I なので合いません。",null,"名詞・動詞の三単現。ここでは形容詞の働きが必要です。"],
      },
      {
        id: "h1e-participle-5",
        question: "「そこに立っている男性は私の先生です。」を正しく表す文はどれ？",
        choices: ["The man standing there is my teacher.","The man stood there is my teacher.","The standing man there is my teacher.","The man stand there is my teacher."],
        answerIndex: 0,
        explanation: "「立っている男性」は能動なので現在分詞 standing を使い、there がつくので名詞 the man の後ろに置きます。The man standing there が正しい語順です。",
        choiceHints: [null,"stood は過去分詞。stand は自動詞で受け身にできず、意味も合いません。","there という語句がつくので、分詞は名詞の後ろに置きます。前置は不自然です。","stand は動詞の原形。名詞を修飾する分詞の形ではありません。"],
      },
      {
        id: "h1e-participle-6",
        question: "___ TV, I heard the phone ring.（テレビを見ていると、電話が鳴るのが聞こえた。）",
        choices: ["Watched","To watch","Watch","Watching"],
        answerIndex: 3,
        explanation: "分詞構文です。「テレビを見ていると（見ながら）」という能動の意味なので、文頭に現在分詞 Watching を置きます。主語 I が「見る」動作をしています。",
        choiceHints: ["過去分詞。「見られながら」となり受け身で意味が合いません。","不定詞。ここでは分詞構文が自然で、原因や同時動作を表せません。","動詞の原形。文頭で状況を表す分詞構文にはなりません。",null],
      },
      {
        id: "h1e-participle-7",
        question: "The story was so ___ that everyone fell asleep.（その話はとても退屈だった。）",
        choices: ["bored","boring","bore","boredom"],
        answerIndex: 1,
        explanation: "話は人を退屈させる「物・事」なので、-ing の boring を使います。boring は「（人を）退屈させるような」という意味です。",
        choiceHints: ["-ed は人が「退屈した」ときに使います。主語が story なので合いません。",null,"動詞の原形。be動詞の後ろの形容詞にはなりません。","名詞「退屈」。ここでは形容詞の働きが必要です。"],
      },
      {
        id: "h1e-participle-8",
        question: "He was listening to music with his eyes ___.（彼は目を閉じたまま音楽を聞いていた。）",
        choices: ["closed","closing","close","to close"],
        answerIndex: 0,
        explanation: "with + O + 分詞の形です。「目が閉じられている」という受け身・状態なので過去分詞 closed を使い、with his eyes closed で「目を閉じたまま」となります。",
        choiceHints: [null,"現在分詞。「目が（何かを）閉じている」となり意味が合いません。","動詞の原形・形容詞。with の後ろの O の状態を表す分詞が必要です。","不定詞。with + O + 分詞の形では分詞を使います。"],
      },
    ],
  },
  {
    id: "h1e-relative",
    subject: "english",
    grade: "高1",
    title: "関係詞",
    lesson: "関係詞は、2つの文を1つにつなぐことばです。人には who、もの・ことには which、どちらにも that が使えます。「〜の」を表すときは whose、場所は where、時は when、理由は why を使います。先行詞（せんこうし＝説明されることば）が人かものか、そして続くことばの形を見て選びましょう。",
    items: [
      {
        id: "h1e-relative-1",
        question: "I have a friend ___ speaks three languages.（私には3か国語を話す友達がいます。）",
        choices: ["who","which","whose","where"],
        answerIndex: 0,
        explanation: "先行詞が「a friend（人）」で、そのあとに動詞 speaks が続く主格なので who を使います。",
        choiceHints: [null,"which はもの・ことが先行詞のときに使います。","whose は「〜の」を表し、あとに名詞が続きます。","where は場所を表す関係副詞です。"],
      },
      {
        id: "h1e-relative-2",
        question: "This is the book ___ made me cry.（これは私を泣かせた本です。）",
        choices: ["who","whose","which","when"],
        answerIndex: 2,
        explanation: "先行詞が「the book（もの）」で、あとに動詞 made が続く主格なので which を使います。",
        choiceHints: ["who は人が先行詞のときに使います。","whose は「〜の」を表し、あとに名詞が続きます。",null,"when は時を表す関係副詞です。"],
      },
      {
        id: "h1e-relative-3",
        question: "I know a girl ___ father is a doctor.（私はお父さんが医者の女の子を知っています。）",
        choices: ["who","which","whose","whom"],
        answerIndex: 2,
        explanation: "「その女の子の父」という所有の意味で、あとに名詞 father が続くので whose を使います。",
        choiceHints: ["who は主格で、あとに動詞が続きます。","which はもの・ことが先行詞のときに使います。",null,"whom は目的格で、あとに主語＋動詞が続きます。"],
      },
      {
        id: "h1e-relative-4",
        question: "This is the town ___ I was born.（ここは私が生まれた町です。）",
        choices: ["which","where","who","whose"],
        answerIndex: 1,
        explanation: "先行詞が場所（the town）で、あとに完全な文（I was born）が続くので関係副詞 where を使います。",
        choiceHints: ["which のあとには主語や動詞が欠けた不完全な文が続きます。ここは完全な文です。",null,"who は人が先行詞のときに使います。","whose は「〜の」を表し、あとに名詞が続きます。"],
      },
      {
        id: "h1e-relative-5",
        question: "The man ___ I met yesterday was very kind.（私が昨日会った男の人はとても親切でした。）",
        choices: ["which","whose","whom","where"],
        answerIndex: 2,
        explanation: "先行詞が人（The man）で、あとに主語＋動詞（I met）が続く目的格なので whom を使います。",
        choiceHints: ["which はもの・ことが先行詞のときに使います。","whose は「〜の」を表し、あとに名詞が続きます。",null,"where は場所を表す関係副詞です。"],
      },
      {
        id: "h1e-relative-6",
        question: "Do you remember the day ___ we first met?（私たちが初めて会った日を覚えていますか。）",
        choices: ["which","where","when","who"],
        answerIndex: 2,
        explanation: "先行詞が時（the day）で、あとに完全な文（we first met）が続くので関係副詞 when を使います。",
        choiceHints: ["which のあとには不完全な文が続きます。ここは完全な文です。","where は場所を表します。ここは「日＝時」です。",null,"who は人が先行詞のときに使います。"],
      },
      {
        id: "h1e-relative-7",
        question: "Tell me the reason ___ you were late.（あなたが遅れた理由を教えてください。）",
        choices: ["why","which","where","whose"],
        answerIndex: 0,
        explanation: "先行詞が「the reason（理由）」で、あとに完全な文が続くので関係副詞 why を使います。",
        choiceHints: [null,"which のあとには不完全な文が続きます。ここは完全な文です。","where は場所を表します。ここは「理由」です。","whose は「〜の」を表し、あとに名詞が続きます。"],
      },
      {
        id: "h1e-relative-8",
        question: "My grandmother, ___ lives in Osaka, is 80 years old.（私の祖母は大阪に住んでいて、80歳です。）",
        choices: ["that","which","who","whose"],
        answerIndex: 2,
        explanation: "先行詞が人（grandmother）で、コンマ付きの非制限用法では that は使えないため who を使います。",
        choiceHints: ["コンマ付きの非制限用法では that は使えません。","which はもの・ことが先行詞のときに使います。",null,"whose は「〜の」を表し、あとに名詞が続きます。"],
      },
    ],
  },
  {
    id: "h1e-comparison",
    subject: "english",
    grade: "高1",
    title: "比較",
    lesson: "ものごとを くらべる 言い方を 学びます。2つを くらべるときは「比較級 + than（〜よりも）」、同じくらいのときは「as ~ as（〜と同じくらい）」を使います。3つ以上で「いちばん〜」と言うときは「the + 最上級」を使い、はんいは in か of で表します。good は better/best、many は more/most のように、形が変わる語にも気をつけましょう。",
    items: [
      {
        id: "h1e-comparison-1",
        question: "This box is ___ than that one. （この箱はあの箱より重い。）",
        choices: ["heavier","more heavy","heaviest","heavy"],
        answerIndex: 0,
        explanation: "heavy は y を i にかえて -er をつけ、heavier になります。than があるので比較級を選びます。",
        choiceHints: [null,"-er をつける語に more はつけません（二重比較）。","最上級です。than とは使いません。","原級のままでは than と使えません。"],
      },
      {
        id: "h1e-comparison-2",
        question: "My bag is as ___ as yours. （私のかばんはあなたのと同じくらい大きい。）",
        choices: ["bigger","biggest","big","more big"],
        answerIndex: 2,
        explanation: "「as ~ as（〜と同じくらい）」の間には、形の変わらない原級が入ります。だから big が正解です。",
        choiceHints: ["as ~ as の間は原級です。比較級は入りません。","as ~ as の間に最上級は入りません。",null,"as ~ as の間は原級で、more もつきません。"],
      },
      {
        id: "h1e-comparison-3",
        question: "She can run ___ than her brother. （彼女はお兄さんより速く走れる。）",
        choices: ["fast","faster","the fastest","as fast"],
        answerIndex: 1,
        explanation: "than があるので比較級 faster を使います。「〜より速く」の意味になります。",
        choiceHints: ["原級のままでは than と使えません。",null,"最上級は than とは使いません。","as ~ as の形なら than ではなく as が必要です。"],
      },
      {
        id: "h1e-comparison-4",
        question: "This is the ___ movie I have ever seen. （これは今まで見た中で一番おもしろい映画だ。）",
        choices: ["more interesting","interesting","as interesting","most interesting"],
        answerIndex: 3,
        explanation: "長い語の最上級は most をつけます。the most interesting で「一番おもしろい」になります。",
        choiceHints: ["これは比較級です。「一番」には最上級を使います。","原級です。「一番」には最上級が必要です。","as ~ as の形です。「一番」の意味にはなりません。",null],
      },
      {
        id: "h1e-comparison-5",
        question: "Tom is the tallest ___ his class. （トムはクラスの中で一番背が高い。）",
        choices: ["of","in","than","as"],
        answerIndex: 1,
        explanation: "class（クラス＝場所や集団）のような「まとまり」には in を使います。the tallest in his class となります。",
        choiceHints: ["of は all や the three のような「複数のもの」に使います。集団には in です。",null,"than は比較級と使う語です。最上級では使いません。","as は as ~ as で使う語です。ここでは使えません。"],
      },
      {
        id: "h1e-comparison-6",
        question: "This computer is ___ better than mine. （このコンピューターは私のよりずっと良い。）",
        choices: ["very","much","more","so"],
        answerIndex: 1,
        explanation: "比較級 better を「ずっと」と強めるときは much を使います。much better で「ずっと良い」です。",
        choiceHints: ["very は原級を強めます。比較級 better は強められません。",null,"more は better にはつけません（better が既に比較級）。","so は比較級を強める語ではありません。"],
      },
      {
        id: "h1e-comparison-7",
        question: "The harder you practice, ___ you will become. （練習すればするほど、あなたは上手になる。）",
        choices: ["the better","better","the best","the good"],
        answerIndex: 0,
        explanation: "「the 比較級, the 比較級」で「〜すればするほど…」を表します。good の比較級 better に the をつけて the better とします。",
        choiceHints: [null,"この構文では比較級の前に the が必要です。","最上級ではなく比較級を使います。","good は原級です。ここでは比較級 better を使います。"],
      },
      {
        id: "h1e-comparison-8",
        question: "Kyoto is one of the most famous ___ in Japan. （京都は日本で最も有名な都市の一つだ。）",
        choices: ["city","a city","cities","the city"],
        answerIndex: 2,
        explanation: "「one of the 最上級 + 複数名詞」で「最も〜な…の一つ」を表します。city の複数形 cities が入ります。",
        choiceHints: ["one of the ~ の後は複数名詞です。単数 city は使えません。","この形に a はつけず、複数名詞にします。",null,"one of the ~ の後は複数名詞です。the city にはしません。"],
      },
    ],
  },
  {
    id: "h1e-subjunctive",
    subject: "english",
    grade: "高1",
    title: "仮定法",
    lesson: "仮定法は「もし〜だったら」と、今の事実とはちがう話や、ありえないことを想像するときに使います。今のことは「仮定法過去」（If＋動詞の過去形, would／could＋動詞の原形）、過去のことは「仮定法過去完了」（If＋had＋過去分詞, would have＋過去分詞）を使います。be動詞は主語が何でも were を使うのがふつうです。「〜だったらいいのに」という願いは I wish＋仮定法で表します。",
    items: [
      {
        id: "h1e-subjunctive-1",
        question: "If I ___ you, I would study harder.（もし私があなたなら、もっと一生けんめい勉強するだろうに。）",
        choices: ["am","was","were","be"],
        answerIndex: 2,
        explanation: "仮定法過去では、be動詞は主語に関係なく were を使うのがふつうです。「If I were you（もし私があなたなら）」は決まった言い方として覚えましょう。",
        choiceHints: ["これは今の事実を言うときの形です。仮定法では使いません。","会話ではまれに使われますが、正しい仮定法では were を使います。",null,"原形なので If のあとの主語には合いません。"],
      },
      {
        id: "h1e-subjunctive-2",
        question: "If it were sunny, we ___ go to the beach.（もし晴れていたら、私たちは海に行くだろうに。）",
        choices: ["will","would","can","must"],
        answerIndex: 1,
        explanation: "仮定法過去の文では、後ろは「would＋動詞の原形」で「〜するだろうに」という意味になります。今は晴れていない、という事実とちがう想像です。",
        choiceHints: ["will は事実として起こることに使います。仮定法では過去形の would を使います。",null,"can は「〜できる」で、ここでは意味が合いません。could なら仮定法で使えます。","must は「〜しなければならない」で、意味が合いません。"],
      },
      {
        id: "h1e-subjunctive-3",
        question: "If I had more time, I ___ read that book.（もっと時間があれば、その本を読めるのに。）",
        choices: ["could","can","will","may"],
        answerIndex: 0,
        explanation: "仮定法過去では「could＋動詞の原形」で「〜できるのに」を表します。今は時間がない、という事実とちがう話です。",
        choiceHints: [null,"can は現在の事実に使う形です。仮定法では過去形の could を使います。","will は事実に使う形なので、ここでは合いません。","may は「〜かもしれない」で、意味が合いません。"],
      },
      {
        id: "h1e-subjunctive-4",
        question: "If I had studied harder, I ___ passed the exam.（もっと勉強していたら、試験に合格していただろうに。）",
        choices: ["would","will have","would have","had"],
        answerIndex: 2,
        explanation: "過去の事実とちがう想像は「仮定法過去完了」を使い、後ろは「would have＋過去分詞」の形になります。実際には合格しなかった、という意味です。",
        choiceHints: ["would だけでは過去分詞 passed とつながりません。would have が必要です。","will have は事実に使う形で、仮定法過去完了では would have を使います。",null,"had だけでは意味が通りません。ここは would have が正しい形です。"],
      },
      {
        id: "h1e-subjunctive-5",
        question: "If she ___ known the truth, she would have told us.（もし彼女が本当のことを知っていたら、私たちに話していただろうに。）",
        choices: ["knew","has","had","would have"],
        answerIndex: 2,
        explanation: "仮定法過去完了の If のあとは「had＋過去分詞」の形です。ここは had known で「知っていたら」を表します。過去の事実とちがう話です。",
        choiceHints: ["knew は仮定法過去（今のこと）の形です。過去のことには had＋過去分詞を使います。","has known は現在完了で、事実に使う形です。仮定法過去完了ではありません。",null,"would have は主節（後ろ）で使う形です。If のあとには had を使います。"],
      },
      {
        id: "h1e-subjunctive-6",
        question: "I wish I ___ speak English well.（英語を上手に話せたらいいのに。）",
        choices: ["can","could","will","am"],
        answerIndex: 1,
        explanation: "「I wish＋仮定法」で今の願いを表すときは、助動詞は過去形の could を使います。実際にはまだ上手に話せない、という気持ちです。",
        choiceHints: ["can は今できることを言う形です。願いを表す I wish のあとでは could を使います。",null,"will は事実として起こることに使います。I wish のあとでは使いません。","am は be動詞で、後ろの speak と一緒には使えません。"],
      },
      {
        id: "h1e-subjunctive-7",
        question: "I wish I ___ taller.（もっと背が高かったらいいのに。）",
        choices: ["am","was","were","will be"],
        answerIndex: 2,
        explanation: "「I wish＋仮定法過去」の be動詞も were を使うのがふつうです。今の事実とちがう願いを表します。",
        choiceHints: ["am は今の事実を言う形です。願いを表す I wish のあとでは were を使います。","会話ではまれに was も使われますが、正しくは were を使います。",null,"will be は未来のことに使う形で、今の願いには合いません。"],
      },
      {
        id: "h1e-subjunctive-8",
        question: "He talks ___ he knew everything.（彼はまるで何でも知っているかのように話す。）",
        choices: ["as if","even if","if only","so that"],
        answerIndex: 0,
        explanation: "「as if＋仮定法過去」で「まるで〜であるかのように」を表します。実際にはそうではない、という気持ちがふくまれています。",
        choiceHints: [null,"even if は「たとえ〜でも」で、意味が合いません。","if only は「〜でさえあればなあ」で、ここでは意味が合いません。","so that は「〜するために」で、意味が合いません。"],
      },
    ],
  },
];
